### ISSUE TITLE
BETA RELEASE - MACHINE RELEASE

### ISSUE THREAD

**Issue by Buuz135** [Buuz135/Industrial-Foregoing#1]
~~Crossed~~ machines will be added after first beta release

**Agriculture & Food**

- [x] Chronotyper (Animal Independence Selector)
- [x] Composter (Sewage Compost Solidifier)
- [x] Fertilizer (Plant Enrich Material Injector)
- [x] Fisher (Water Resources Collector)
- [ ] ~~Fountain~~
- [ ] ~~Fruit Picker~~
- [x] Harvester (Plant Recolector)
- [ ] ~~Meat Packer~~
- [x] Planter (Plant Sower)
- [x] Rancher (Animal Resource Harvester)
- [x] Sewer (Animal Byproduct Recolector)
- [x] Slaughterhouse (Mob Slaughter Factory)
- [x] Sludge Boiler

**Brewing & Enchanting**
- [x] Auto Anvil (Enchantment Aplicator)
- [x] Auto Brewer (Potion Enervator)
- [x] Auto Disenchanter (Enchantment Extractor)
- [ ] ~~Auto Enchanter~~

**Fuel & Energy**
- [x] BioReactor
- [x] BioFuel Gen
- [x] Lava Fabricator
- [ ] ~~Oil Fabricator~~
- [ ] ~~Steam Turbine~~
- [ ] ~~Steam Boiler~~
- [x] Weather Collector (Water Condensator)

**Mining**
- [x] Block Breaker (Block Destroyer)
- [ ] Block Smasher
- [x] Laser Drill
- [x] Laser Drill Precharger

**Misc**
- [ ] ~~Auto Jukebox~~
- [x] Block Placer (Block Placer)
- [ ] ~~Chunk Loader~~
- [ ] ~~Liquid Crafter~~
- [ ] ~~Unifier~~

**Mob Farming**
- [x] Auto Spawner (Mob Duplicator)
- [x] Breed (Animal Stock Increaser)
- [x] Grinder (Mob Relocator)
- [x] Mob Counter
- [ ] ~~Mob Router~~
- [ ] ~~Veterinary Station~~

**Transport & Storage**
- [x] Conveyor Belt
- [x] Deep Storage Unit
- [x] Enchantment router (Enchantment Refiner)
- [ ] ~~Item Collector~~

**Comment by jambonmcyeah** [comment]
Please don't cancel auto enchanter, I need a way to automate enchantments

**Comment by Sir1usBl4ck** [comment]
Without an XP Extractor it's kinda hard to create the Essence

**Comment by Buuz135** [comment]
Have you tried to kill mobs with a mob relocator?

**Comment by Sir1usBl4ck** [comment]
Yes sir, not sure if it's intentional but the essence required to create a monster in the duplicator is higher than what it yelds so it forces u to have another way of spawning mobs

**Comment by Buuz135** [comment]
Yes, it is.

**Comment by jkroepke** [comment]
@Buuz135 plans for the Fruit picker?

Currently its very hard to auto harvest pam harvest tree fruit on 1.12.

Maybe you can make this machine as a upgrade card for the plant geatherer

**Comment by ShuzzDE** [comment]
Hi!
Do you think you can add the Steam Boiler in the near-ish future? :-)
In combination with Extreme Reactor's turbines those things make for pretty insane, quasi-passive power generation. (Once it's set up you can forget about it and just reap around 28kRF/t).

Pretty please? <3 <3 <3
