### ISSUE TITLE
Incompatabilities

### ISSUE THREAD

**Issue by caligator** [Buuz135/Industrial-Foregoing#10]
Enjoying the mod currently, but found out that theres certain incompatibilities with other mods. 

*The Tree Extractor can not export liquids to nearby containers (even when configured). I tested this with BC fluid pipes and tanks. wooden pipes work, but standard pipes refuse to connect, and it doesnt recognize BC tanks. Also tested Fluiducts from Thermal Expansion; they do not connect at all, and neither do portable tanks. 

*The liquid latex apparently is treated as lava/hot liquid in Thermal Expansion equipment, producing light and detonating base tier piping. 

Will report any other strange interactions if I find them. good job so far-- things are really lookin great with this.

**Comment by Buuz135** [comment]
Machines do not auto eject, do you mean that?

**Comment by caligator** [comment]
no- its not connecting to pipes or tanks period.
