### ISSUE TITLE
Mob Duplicator crash on server

### ISSUE THREAD

**Issue by AdityaGupta1** [Buuz135/Industrial-Foregoing#100]
Industrial Foregoing Version: 1.12.2-1.5.6-93
TeslaCoreLib Version: 1.12-1.0.11
Crashlog (If Any): none
Running in Direwolf20 1.12 pack version 1.10

When placing a Mob Imprisonment Tool containing a Wither Skeleton inside a Mob Duplicator, the server freezes up and stops responding. Entities stop moving, blocks can't be interacted with, etc. This originally was happening with Sponge, but it kept happening even after the server owner removed Sponge.

Here is the mob duplicator in-game, maybe the location it's placed in is causing this?
![Mob Duplicator image](https://i.imgur.com/yYoW9eY.png)

The duplicators are next to and one block below the Industrial Apiary (yellow block). Whenever I place the Mob Imprisonment Tool in either of the duplicators, the server freezes.

**Comment by Buuz135** [comment]
I think its already fixed in 1.5.9, but that setup won't work, there isn't enough space to spawn, you need to make it taller.

In case it's not fixed when the pack its updated make another issue or comment on this one.
