### ISSUE TITLE
(Feature Status) When will Conveyors & Plastic Pipes come back?

### ISSUE THREAD

**Issue by Vaygrim** [Buuz135/Industrial-Foregoing#101]
I'm just asking out of general curiousity, when are the conveyor belts and plastic pipes from the original mod coming back?  Or maybe a machine upgrade that would let them auto-eject and auto-import from adjacent containers / machines?

Keep up the great work, thanks!

**Comment by Buuz135** [comment]
Converyor belts aren't going to be implemented, Simply Conveyors is more advanced. Plastic pipes either, I'm focusing the mod on machinery.

No auto eject either it will come in a system like the Energy Field is done.
