### ISSUE TITLE
Enchantment Extractor not compattible with Redstone Arsenal

### ISSUE THREAD

**Issue by tjsd** [Buuz135/Industrial-Foregoing#103]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.5.9-96
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.11
Redstone Arsenal Version: RedstoneArsenal-1.12-2.3.6.16-universal
Crashlog (If Any): 

Issue: I can not use the Enchantment Extractor to remove enchants from a Redstone Arsenal Flux-Infused Hammer

It has power, books and the hammer ,nothing happens.
![image](https://user-images.githubusercontent.com/7138125/33291635-c436b36e-d3c6-11e7-9226-9a8e8d7284b2.png)

**Comment by Buuz135** [comment]
Thats the power item slot, the slot for the items to get the enchantments removed is below the books.

**Comment by tjsd** [comment]
This is shift left click on item placement, still not "my fault"

**Comment by Buuz135** [comment]
That's intended, it has power so it goes in the power slot.
