### ISSUE TITLE
[Request] Recipe config

### ISSUE THREAD

**Issue by NillerMedDild** [Buuz135/Industrial-Foregoing#104]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.5.11-100
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.11
Crashlog (If Any): 

Hey! I'd really appreciate the ability to revert machine recipes to use the Tesla Core Lib Machine Case again, as opposed to the Thermal Expansion Machine Frame.
I'm trying to gate progression through mods, and TE Machine Frames replacing Machine Cases basicly removes Industrial Foregoing from the Tech Tree. I can ofc find a work-around if you'd rather not implement it.

**Comment by Buuz135** [comment]
I will keep it like this for a while and if it doesn't work out I will change it.
