### ISSUE TITLE
[Suggestion] change Animal Sewage to Sewer

### ISSUE THREAD

**Issue by simpson409** [Buuz135/Industrial-Foregoing#105]
MFR's sewer was able to pick up xp orbs, to make essence, which allowed us to turn liquid xp into essence.. right now there is only one way to get essence and we are forced to use the industrial foregoing mob crusher. 
my suggestion: give the animal sewage a tank for essence, allow it to pick up xp orbs and rename it appropriately.

**Comment by Buuz135** [comment]
Mob Grinder picks up experience and transforms it into essence.
