### ISSUE TITLE
FYI/Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [Buuz135/Industrial-Foregoing#108]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.5.12-101.jar
TeslaCoreLib Version: Tesla Core Lib : 1.12 - 1.0.11

MC/F 1.12/2443

Crashlog (If Any): 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  llibrary (llibrary-1.7.9-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  BCModPlugin (backpacks 1.12 - 3.4.2.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 12/2/17 12:22 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:371)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:362)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:31)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:42)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:628)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:235)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:547)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:371)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:362)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:31)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:42)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:628)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:235)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:547)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 227575816 bytes (217 MB) / 696582144 bytes (664 MB) up to 12831227904 bytes (12236 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 125 mods loaded, 125 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	minecraft{1.12} [Minecraft] (minecraft.jar) 
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	U	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	U	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	U	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	U	bowinfinityfix{rv5} [Bow Infinity Fix] (minecraft.jar) 
	U	simplebedrolls{1.2.1} [Simple Bedrolls] ([1.12]SimpleBedrolls-1.2.1.jar) 
	U	uncraftingtable{1.8-beta6} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta6.jar) 
	U	acintegration{1.5.0} [AbyssalCraft Integration] (AbyssalCraft Integration-1.12-1.5.0.jar) 
	U	abyssalcraft{1.9.4-pre-4} [AbyssalCraft] (AbyssalCraft-1.12-1.9.4-pre-4.jar) 
	U	actuallyadditions{1.12.2-r124} [Actually Additions] (ActuallyAdditions-1.12.2-r124.jar) 
	U	actuallybaubles{1.1} [Actually Baubles] (ActuallyBaubles-1.12-1.1.jar) 
	U	alt{2.0.2} [Additional Loot Tables] (AdditionalLootTables-1.12.1-2.0.2.29.jar) 
	U	allthedrops{1.0.1} [All the Drops] (allthedrops-1.11.2-1.0.1-build-T22.jar) 
	U	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.8 mc1.12.jar) 
	U	architecturecraft{@VERSION@} [ArchitectureCraft] (architecturecraft-1.12-1.20.jar) 
	U	autoreglib{1.3-15} [AutoRegLib] (AutoRegLib-1.3-15.jar) 
	U	backpacks16840{3.4.2} [Backpacks!] (backpacks 1.12 - 3.4.2.jar) 
	U	baubles{1.5.1} [Baubles] (Baubles-1.12-1.5.1.jar) 
	U	betterbedrockgen{6.0.2} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.1.jar) 
	U	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	U	binniecore{unspecified} [Binnie Core] (binnie-mods-1.12.2-2.3.1.jar) 
	U	botany{2.3.1} [Binnie's Botany] (binnie-mods-1.12.2-2.3.1.jar) 
	U	binniedesign{1.0} [Binnie's Design] (binnie-mods-1.12.2-2.3.1.jar) 
	U	extrabees{2.3.1} [Binnie's Extra Bees] (binnie-mods-1.12.2-2.3.1.jar) 
	U	extratrees{2.3.1} [Binnie's Extra Trees] (binnie-mods-1.12.2-2.3.1.jar) 
	U	genetics{2.3.1} [Binnie's Genetics] (binnie-mods-1.12.2-2.3.1.jar) 
	U	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	U	birdsnests{2.0.0} [Bird's Nests] (BirdsNests1.12-2.0.0.jar) 
	U	bookshelf{2.1.441} [Bookshelf] (Bookshelf-1.12.1-2.1.441.jar) 
	U	bushcraft{0.0.1.0} [Bushcraft] (Bushcraft-1.12-0.0.1.0.jar) 
	U	carryon{1.7} [Carry On] (CarryOn MC1.12 v1.7.jar) 
	U	chickens{6.0.2} [Chickens] (chickens-6.0.2.jar) 
	U	chisel{MC1.12-0.0.14.18} [Chisel] (Chisel-MC1.12-0.0.14.18.jar) 
	U	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	U	cleanview{1.12.2-v1} [CleanView] (CleanView-1.12.2-v1.jar) 
	U	clockhud{1.4.0} [Clock HUD] (ClockHUD-1.12-1.4.0.jar) 
	U	commoncapabilities{1.4.0} [CommonCapabilities] (CommonCapabilities-1.12-1.4.0.jar) 
	U	concreteplus{1.1.2} [Concrete Extends] (ConcreteExtends-1.1.2_1.12.jar) 
	U	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.10.jar) 
	U	crafttweaker{4.0.10} [CraftTweaker2] (CraftTweaker2-1.12-4.0.10.jar) 
	U	crafttweakerjei{2.0.0} [CraftTweaker JEI Support] (CraftTweaker2-1.12-4.0.10.jar) 
	U	ctm{MC1.12-0.2.3.9} [CTM] (CTM-MC1.12-0.2.3.9.jar) 
	U	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot (v.1.0.1).jar) 
	U	cyclicmagic{1.8.6} [Cyclic] (Cyclic-1.12-1.8.6.jar) 
	U	cyclopscore{0.10.21} [Cyclops Core] (CyclopsCore-1.12-0.10.21.jar) 
	U	darkutils{1.7.171} [Dark Utilities] (DarkUtils-1.12.1-1.7.171.jar) 
	U	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-6.337-full.jar) 
	U	disenchanter{1.5} [Disenchanter] (disenchanter-[1.12]1.5.jar) 
	U	dungeons2{1.3.1} [Dungeons2!] (Dungeons2-mc1.12-v1.3.1.jar) 
	U	dsurround{3.4.7.2} [Dynamic Surroundings] (DynamicSurroundings-1.12.2-3.4.7.2.jar) 
	U	presets{3.4.7.2} [Presets!] (DynamicSurroundings-1.12.2-3.4.7.2.jar) 
	U	earthworks{1.3.4.3} [Earthworks] (Earthworks-1.12-1.3.4.3.jar) 
	U	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	U	csb_ench_table{1.1.2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2.jar) 
	U	enchdesc{1.0.4} [Enchantment Descriptions] (EnchantmentDescriptions-1.12-1.0.4.jar) 
	U	everlastingabilities{1.3.5} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.5.jar) 
	U	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.6.8.jar) 
	U	fastleafdecay{v13} [Fast Leaf Decay] (FastLeafDecay-v13.jar) 
	U	flatcoloredblocks{mc1.12-6.6} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.6.jar) 
	U	forestry{5.5.6.198} [Forestry] (forestry_1.12.2-5.5.6.198.jar) 
	U	forgeendertech{1.12-3.0.1.0} [Forge Endertech] (ForgeEndertech-1.12-3.0.1.0-build.0012.jar) 
	U	friendlyfire{1.5.5} [Friendly Fire] (FriendlyFire-1.12-1.5.5.jar) 
	U	funores{1.5.7} [Fun Ores] (FunOres-1.12-1.5.7-118.jar) 
	U	gamestages{1.0.62} [Game Stages] (GameStages-1.12.1-1.0.62.jar) 
	U	gottschcore{1.1.2} [GottschCore] (GottschCore-mc1.12-v1.1.2.jar) 
	U	gravelminer{6.1.2} [GravelMiner] (GravelMiner_1.12.1-6.1.2.jar) 
	U	gravestone{1.0.12} [Gravestone] (GraveStone-1.12-Graves-1.0.12.jar) 
	U	guideapi{1.12-2.1.4-57} [Guide-API] (Guide-API-1.12-2.1.4-57.jar) 
	U	waila{1.8.22} [Waila] (Hwyla-1.8.22-B37_1.12.jar) 
	U	ichunutil{7.1.2} [iChunUtil] (iChunUtil-1.12.2-7.1.2.jar) 
	U	iv{3.0.2} [Improved Villagers] (Improved Villagers-3.0.2.jar) 
	U	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	U	industrialforegoing{null} [Industrial Foregoing] (industrialforegoing-1.12.2-1.5.12-101.jar) 
	U	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	U	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	U	jei{4.7.11.100} [Just Enough Items] (jei_1.12.2-4.7.11.100.jar) 
	U	jjraces{1.0.2} [JJ Races] (JJ Races 1.12-1.12.2-v1.0.2.jar) 
	U	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	U	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.8-1.12.jar) 
	U	llibrary{1.7.9} [LLibrary] (llibrary-1.7.9-1.12.jar) 
	U	lootchests{1.2.1} [SeriousCreepers Loot Chests] (lootchests-1.2.1.jar) 
	U	malisisblocks{1.12-6.0.2} [Malisis Blocks] (malisisblocks-1.12-6.0.2.jar) 
	U	malisiscore{1.12-6.0.4} [MalisisCore] (malisiscore-1.12-6.0.4.jar) 
	U	malisisdoors{1.12.2-7.1.0} [MalisisDoors] (malisisdoors-1.12.2-7.1.0.jar) 
	U	malisisswitches{1.12-5.0.0} [Malisis Switches] (malisisswitches-1.12-5.0.0.jar) 
	U	mantle{1.12-1.3.1.21} [Mantle] (Mantle-1.12-1.3.1.21.jar) 
	U	mobfarm{2.2.1} [Mob Farm] (Mob Farm-1.12-2.2.1.jar) 
	U	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	U	modernlamps{1.0.3} [Modern Lights] (ModernLights-1.0.3_1.12.jar) 
	U	moreloottables{0.1.0} [More Loot Tables] (moreloottables-1.12.0-0.1.0.jar) 
	U	moreoverlays{1.13} [MoreOverlays] (moreoverlays-1.13-mc1.12.jar) 
	U	movingworld{1.12-6.342} [Moving World] (movingworld-1.12-6.342-full.jar) 
	U	natura{1.12-4.3.0.17} [Natura] (Natura-1.12-4.3.0.17.jar) 
	U	recipehandler{0.9} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.9(1.12).jar) 
	U	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	U	oreberries{0.4.0} [Oreberries] (oreberries-1.12.x-0.4.0.jar) 
	U	jp.crafterkina.pipes{1.1.0.15} [Pipes] (Pipes-1.12-1.1.0.15.jar) 
	U	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
	U	randomthings{4.0.8} [Random Things] (RandomThings-MC1.12.2-4.0.8.jar) 
	U	randomtweaks{1.12.2-1.13.0.0} [RandomTweaks] (randomtweaks-1.12.2-1.13.0.0.jar) 
	U	reccomplex{1.4.6} [Recurrent Complex] (RecurrentComplex-1.4.6.jar) 
	U	roost{1.2.0} [Roost] (roost-1.12-1.2.0.jar) 
	U	ruins{16.9} [Ruins Mod] (Ruins-1.12.jar) 
	U	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.12-0.0.1b7.jar) 
	U	silentlib{2.2.13} [Silent Lib] (SilentLib-1.12-2.2.13-94.jar) 
	U	icc{0.2.2} [Simple Item Collector Chest] (Simple Item Collector Chest-0.2.2.jar) 
	U	simpleleather{1.12-1.0} [Simple Leather] (simpleleather-1.12-1.0.jar) 
	U	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	U	spawnercraft{4.0.0} [SpawnerCraft] (SpawnerCraft 1.12-4.0.0.jar) 
	U	tconstruct{1.12-2.7.4.34} [Tinkers' Construct] (TConstruct-1.12-2.7.4.34.jar) 
	U	tinkertoolleveling{1.12-1.0.2b.DEV.1a79301} [Tinkers Tool Leveling] (TinkerToolLeveling-1.12-1.0.2b.jar) 
	U	muchmorechickens{1.7} [muchmorechickens] (TMC-1.12-1.7.jar) 
	U	toolbelt{1.7.1} [Tool Belt] (ToolBelt-1.12.0-1.7.1.jar) 
	U	treechopper{1.2.2} [Tree Chopper] (TreeChopper-1.12-1.2.2.jar) 
	U	uncrafted{3.0.1} [Uncrafted] (Uncrafted 1.12  (v.3.0.1).jar) 
	U	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	U	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	U	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	U	vtt{0.6.4} [Villager Trade Tables] (VillagerTrades-1.12-0.6.4.jar) 
	U	wailaharvestability{1.1.12} [Waila Harvestability] (WailaHarvestability-mc1.12-1.1.12.jar) 
	U	wawla{2.5.243} [What Are We Looking At] (Wawla-1.12.1-2.5.243.jar) 
	U	waystones{4.0.17} [Waystones] (Waystones_1.12.1-4.0.17.jar) 
	U	ironic_wdt{1.2} [Weak Drop Tweaks] (WeaKDropTweaks-1.3.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-104.jar)
  vazkii.quark.base.asm.ClassTransformer
llibrary (llibrary-1.7.9-1.12.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
BCModPlugin (backpacks 1.12 - 3.4.2.jar)
  brad16840.core.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.31' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12-forge1.12-14.21.1.2443
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: TEAVSRP2.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by Buuz135** [comment]
Why do I get this crash report?

**Comment by Buuz135** [comment]
Redownload the mod and update to 1.12.2 latest forge

**Comment by Nexusdog** [comment]
I had a crash, IF caused it, I submitted a crash report. You check the crash report for bugs & errors and fix the problem... isn't that how it works?

IF is listed as 1.12 friendly, but instead of the MC 'requires 1.12.x' screen, I was dumped back to launcher with the 'unexpected error' message. If IF is not 1.12 friendly, perhaps it might help to make that clear?

So no, I will not reload & update, not based on these unhelpful comments, sorry.

**Comment by Buuz135** [comment]
Then it won't be fixed because thats what you need to do, update to the latest 1.12.2 forge version, the version you are using is 5 months old, outdated and not supported anymore.

I have removed the 1.12 & 1.12.1 "friendly" tags in curse.
