### ISSUE TITLE
Crash when shift clicking TE Portable Tank in Mob Relocator GUI

### ISSUE THREAD

**Issue by MysticFlowP** [Buuz135/Industrial-Foregoing#11]
https://pastebin.com/raw/Rs9kQCjb

It seems that i can put tank in this slot

![2017-07-07_15 00 12](https://user-images.githubusercontent.com/29012026/27945061-c23bc854-6325-11e7-9cc6-7aba33a3e466.png)

#### Using

- industrialforegoing-1.11.2-0.3-14
- CodeChickenLib-1.11.2-3.0.0.274-universal
- CoFHCore-1.11.2-4.2.6.13-universal
- jei_1.11.2-4.5.0.291
- Tesla-1.11-1.3.0.52
- tesla-core-lib-1.11.2-0.7.1
- ThermalDynamics-1.11.2-2.2.5.10-universal
- ThermalExpansion-1.11.2-5.2.5.18-universal
- ThermalFoundation-1.11.2-2.2.4.12-universal

**Comment by Buuz135** [comment]
That slot id for power, does it happen when you put it in the right slot?

**Comment by MysticFlowP** [comment]
I can't put both the tank and bucket in liquid slot.

**Comment by MysticFlowP** [comment]
Not only Mob Relocator, but also all the machine that has power slot will crashing Minecraft if i put tank in power slot

**Comment by Buuz135** [comment]
Fixed in https://minecraft.curseforge.com/projects/tesla-core-lib/files/2447283
