### ISSUE TITLE
plant gather not chopping trees properly

### ISSUE THREAD

**Issue by jackytuutykcaj** [Buuz135/Industrial-Foregoing#110]
Industrial Foregoing Version: 1.12.2-1.5.11-100
TeslaCoreLib Version: 1.12-1.0.11
Crashlog (If Any): none

Im using a plant gather and sower. If there is more than one sapling planted and one tree grows, it only breaks the bottom log and replants. If theres only one tree, it would cut. I think it might be the vertical range.

**Comment by Buuz135** [comment]
Can you explain better adding some pictures of the setup

**Comment by jackytuutykcaj** [comment]
https://imgur.com/a/0qW9V

**Comment by jackytuutykcaj** [comment]
it got the bottom log but not the rest of the tree

**Comment by Buuz135** [comment]
Do you have some kind of protection?

**Comment by jackytuutykcaj** [comment]
yeah

**Comment by jackytuutykcaj** [comment]
grief prevention

**Comment by jackytuutykcaj** [comment]
does it stop the gather from working?

**Comment by Buuz135** [comment]
Probably

**Comment by jackytuutykcaj** [comment]
does the gather work like a player so i can do /trust on it?

**Comment by jackytuutykcaj** [comment]
wait but it managed to cut a tree once when there were no saplings around it

**Comment by jackytuutykcaj** [comment]
if i replaced the sapling underneath the tree it seemed to cut it down

**Comment by jackytuutykcaj** [comment]
its breaking the bottom log first and ignoring the rest

**Comment by jackytuutykcaj** [comment]
still dont get it? basically i have a plant gather and a plant sower. Whenever a tree grows, the gather breaks the bottom log and not the whole tree.

**Comment by Buuz135** [comment]
Have you tried it somewhere is not protected?

**Comment by jackytuutykcaj** [comment]
no not yet because my partner isnt home. I'll update you when he is on the server.

**Comment by jackytuutykcaj** [comment]
yeah its because of protection

**Comment by jackytuutykcaj** [comment]
once we removed it it started working normaly

**Comment by jackytuutykcaj** [comment]
so it worked when we didnt claim the trees.

**Comment by jackytuutykcaj** [comment]
so i guess its grief preventions fault?

**Comment by Buuz135** [comment]
It could because it allows 1 block to be broken only, it's wierd

**Comment by Buuz135** [comment]
https://github.com/Buuz135/Industrial-Foregoing/commit/42eb5dd393e829b856a5c217377174655bea471b Closed
