### ISSUE TITLE
Plant gatherer not harvesting red orchids from extra utilities 2

### ISSUE THREAD

**Issue by bogger33** [Buuz135/Industrial-Foregoing#116]
Industrial Foregoing Version: 1.12.2-1.5.13-103
TeslaCoreLib Version: 1.12-1.0.11

I planted down a red orchid on some redstone ore, directly in front of my plant gatherer, gathering other things in the area just fine, but it seems that the red orchids, it doesn't know how to deal with. This might also affect ender lilys from the same mod, they take a while to grow, I'll edit in whether or not they work once I know.

e: does not work with ender lillies either

**Comment by Buuz135** [comment]
Ender lillies work if Integration Foregoing, please request Red Orchids there

**Comment by bogger33** [comment]
I'm sorry, I don't understand what you mean. Where should I request red orchids?

Ender lillies are not working for me. Check it out:
https://i.imgur.com/ZG0ZmkX.png

Been that way for hours. The other stuff is getting harvested fine. This is the direwolf20 1.12 modpack if that helps.

**Comment by Buuz135** [comment]
Integration Foregoing adds compatibility between mods, having that mod present will harvest ender lillies, request Red Orchids compat to it.

**Comment by bogger33** [comment]
oh right, I see what you're saying. Sorry, I was reading that as industrial foregoing instead of integration foregoing. had me real confused

**Comment by Buuz135** [comment]
It didnt help that I skiped some words in the phrase
