### ISSUE TITLE
Black Hole Controller deletes whole stack when single item requested.

### ISSUE THREAD

**Issue by ouroborus** [Buuz135/Industrial-Foregoing#118]
Industrial Foregoing Version: 1.12.2-1.5.11-100
TeslaCoreLib Version: 1.12-1.0.11

When a single item is pulled from a stack in a Black Hole Controller via pipes, whatever is in the particular output slot is removed but only one item comes out. This seems to happen when the only items available are those in the output slot (i.e.: The black hole unit itself registers 0 contents). This sometimes, but not always, also causes the BHU's count to go negative.

**Comment by Buuz135** [comment]
Update to 1.5.13-103 and should already be fixed
