### ISSUE TITLE
[Improvement Request] StoneWorks should be able to split a row into 2

### ISSUE THREAD

**Issue by eslachance** [Buuz135/Industrial-Foregoing#120]
Industrial Foregoing Version: n/a
TeslaCoreLib Version: n/a
Crashlog (If Any): n/a

Understanding that having multiple StoneWork blocks is still super trivial and cheap, I'd personally appreciate not having to create 5 of them where we could actually just use 3. Having the ability to send the contents of one row to 2 different rows would be awesome.

For example, I could go Cobble -> Gravel -> Sand -> Glass, but also send Sand to the 5th slot for silicon. 

Alternatively to changing the UI, one could add a way to *accept input* on secondary rows, with a sort of built-in filter that only accepts things that can be produced by the StoneWorks block... maybe? I know that can risk turning it into an autocrafter, however.

**Comment by Buuz135** [comment]
It's easy to make, its op, it doesn't need more OP stuff to it.

**Comment by eslachance** [comment]
Thanks for the quick response! And now, anyone else searching will find this official answer <3
