### ISSUE TITLE
Material Stoneworks Factory can create charcoal from power

### ISSUE THREAD

**Issue by NosajDraw** [Buuz135/Industrial-Foregoing#122]
Industrial Foregoing Version: 1.12.2-1.5.11-100
TeslaCoreLib Version: 1.12-1.0.11

If you set the first job to "stopped" you can then set any or all of the remaining 3 to "Furnace mode" at which point those outputs will now auto-magically be filled with charcoal.

This may be by design, but it seems odd both in terms of it doesn't work like this if you set the first job to "furnace mode" plus whilst cobble gens that in effect creating something from nothing, have a long history in MC, creating charcoal in the same way seems OP.

**Comment by Buuz135** [comment]
It's not an a machine issue, some mod must add some bad furnace recipe, having the input as EMPTY. I guess I could make it not work if the input is empty

**Comment by Yoosk** [comment]
https://a.doko.moe/napbni.webm

**Comment by Buuz135** [comment]
I said that there is a Furnace recipe that makes Charcoal from nothing that what that happens, the machine uses the same as a furnace would
