### ISSUE TITLE
pt_BR Translation

### ISSUE THREAD

**Issue by InterPlay02** [Buuz135/Industrial-Foregoing#124]
Hello!

I've made a pt_BR Translation:
https://pastebin.com/HhhpnuxN

But I want to ask you how can I translate the manual also.

**Comment by Buuz135** [comment]
You currently can't, all the text is fixed.

**Comment by InterPlay02** [comment]
Ok... So... That's it!

Use this translation in to your new versions! xD

**Comment by InterPlay02** [comment]
PS.: I've made some corrections in spelling just now...
Should be fine now. =)
