### ISSUE TITLE
plant sower is not planting seeds

### ISSUE THREAD

**Issue by crimso** [Buuz135/Industrial-Foregoing#125]
Industrial Foregoing Version: 1.12.2-1.6.1-105
TeslaCoreLib Version: 1.12.1-1.0.11
Crashlog (If Any): No crash

Hello,

The plant sower is planting seeds, trees is OK but seeds are not working, please check pictures:

https://imgur.com/a/krKpC

Thank you and please keep up the good work with the mods because is great :)

**Comment by Buuz135** [comment]
Imgur link isnt working

**Comment by crimso** [comment]
oops sorry my misstake, now has to be ok :)

**Comment by Buuz135** [comment]
It appears to be that I derped something
