### ISSUE TITLE
[Feature Request] Range Upgrade for "Mob" Machines

### ISSUE THREAD

**Issue by Xiaminou** [Buuz135/Industrial-Foregoing#128]
I know this is a spiritual successor to MineFactoryReloaded and in MFR this type of machine did not allow Range Upgrades, but I think it should be reconsidered.
I think the Mob Crusher, Mob Duplicator and Mob Slaughter Factory should benefit from the Range Upgrades, including more Range Downgrade for the Mob Duplicator.
Regarding the Mob Duplicator I also think the Work Area should extend from the top of the block instead of being up and down. Basically making it something you would put in the ground like the Plant Sower.

However I also feel that Range Upgrade are too easy to craft for the bonus they provide, even for something as simple as the Planter Sower and the Plant Gatherer. But that's another subject entirely.

**Comment by SpeedySpy52** [comment]
Came here to suggest this and seems you beat me to it. Not being able to do my animal farms in large, natural areas is really aggravating - it's ugly to have pens be only 5x5.
