### ISSUE TITLE
Inventory Sorting Issue

### ISSUE THREAD

**Issue by FoxBotGames** [Buuz135/Industrial-Foregoing#129]
Industrial Foregoing Version: 1.12.2-1.5.13-103
Industrial Meat: 1.12.2-1.02 (in modpack, just used for reference as modifications)
TeslaCoreLib Version: 1.12-1.0.11
Crashlog (If Any): No Crash Log
_Mod versions go minecraft version-mod version_

**Issue**

When using Inventory Sorter (mod by spw, version 1.12.2-1.12.4+52) to 'sort' the inventory of the Animal Feeder all items in the feeder vanish. 

When used inside a Plant Sower the seeds break the 16 items limit (default) and holds stacks of seeds inside its buffer slots, the final slot (bottom right) does not break this rule.
these involve auto input from Thermal Expansion itemducts.

**Comment by FoxBotGames** [comment]
Modpack is GrimCo R&D version 1.0.3

**Comment by Buuz135** [comment]
Thats probably a Inventory Sorter issue, its assuming that the slots have a 64 stack size and can accept any item when sorted.

**Comment by pjc21** [comment]
Also having the same issue with both the Animal Feeder & the Plant Fertilizer.
When middle clicking mouse to sort inventories of the machines all items in machines inventory will disappear.
Modpack: Direwolf20 1.12
Version: 1.4.0
Industrial Foregoing: 1.12.2-1.6.3-107
Inventory Sorter: 1.12.2-1.12.4+52
Tesla-core-lib: 1.12-1.0.12

**Comment by Buuz135** [comment]
Please report it to Inventory Sorter, I cant do anything about it, speacially the Slot limit skipping.

**Comment by Buuz135** [comment]
Kinda fixed in InventorySorter Side

**Comment by beliboba** [comment]
Same for me in all IF machines (atm7 to the sky)
