### ISSUE TITLE
Plant Relocator fails to cut trees properly

### ISSUE THREAD

**Issue by Xiaminou** [Buuz135/Industrial-Foregoing#13]
![2017-07-11_16 42 10](https://user-images.githubusercontent.com/8670392/28095975-d264138e-66a5-11e7-8332-fabfa86784a3.png)
![2017-07-11_20 30 25](https://user-images.githubusercontent.com/8670392/28095976-d2666404-66a5-11e7-892e-79473947e185.png)

Note: I have Fast Leaves Decay

**Comment by Buuz135** [comment]
1.11.2 right?

**Comment by Xiaminou** [comment]
Yes, sorry.
