### ISSUE TITLE
[Feature Request] Removing a Machine Completely

### ISSUE THREAD

**Issue by Darkosto** [Buuz135/Industrial-Foregoing#131]
Would you consider adding the ability to disable machines completely and disallowing the JEI tabs to show for those particular machines? Please! :)

Thank you!
Darkosto

**Comment by Buuz135** [comment]
[industrialforegoing-1.12.2-1.6.4-108.jar.zip](https://github.com/Buuz135/Industrial-Foregoing/files/1564381/industrialforegoing-1.12.2-1.6.4-108.jar.zip)
There you go if you want to break it @Darkosto
