### ISSUE TITLE
fluid crafter internal inventory feature request

### ISSUE THREAD

**Issue by Staegrin** [Buuz135/Industrial-Foregoing#132]
Instead of using the current method of filling one slot at a time when inputting items, taking the items from an internal inventory like the old minefactory version would be easier. 

Example. If you're using this to automate the creation of treated wood planks from immersive engineering 1 bucket of creosote surrounded by 8 planks. If you pump in 8 planks they will all go into one slot and nothing will happen. -> you have to pump in 7 stacks and 1 planks for the machine to start making one set of 8 treated planks.
![2017-12-16_15 50 12](https://user-images.githubusercontent.com/8494635/34071626-f1807286-e278-11e7-9fe9-022ffaf55061.png)
If those 8 planks went into one shared inventory they could be used to finish the recipe.

Of course this could also be fixed by having the option of pumped in items to be spread across the applicable slots in the recipe.   

There is also the possibility of adding oredictionary support for the recipes. 

Previous example -> Using a different type of plank requires putting in a new recipe.

**Comment by Buuz135** [comment]
If you read the book it recomends you to use the Item Splitter

**Comment by Staegrin** [comment]
Ok thanks. 

Still doesn't solve the oredictionary problem

Or a second problem I just looked up what do you do when a recipe requires more than one liquid?

![2017-12-16_16 08 29](https://user-images.githubusercontent.com/8494635/34071741-69a7e706-e27b-11e7-8c9c-c4691d31d0d6.png)
Giving it lava (liquid) and water buckets will still not run to give obsidian.
![2017-12-16_16 08 34](https://user-images.githubusercontent.com/8494635/34071742-6d41bd42-e27b-11e7-9f1f-06fdd7118b6d.png)

**Comment by Buuz135** [comment]
Oh I missed the oredictionary part, I dont plan to add it currently, but maybe?

Having 2 fluids won't work as I doesn't which fluid to really pick so the crafter just avoids recipes that have 2 fluids, I could check for a default fluid being the tank one.
