### ISSUE TITLE
Plant Gatherer does not want to harvest Simple Corn

### ISSUE THREAD

**Issue by tgstyle** [Buuz135/Industrial-Foregoing#134]
Industrial Foregoing Version: 1.12.2-1.6.3-107
TeslaCoreLib Version: 1.12-1.0.12
Simple Corn Version: 1.12-2.3.5

The Plant Sower places corn without issue, however the Plant Gatherer does not want to harvest them. Could this be added?

**Comment by Buuz135** [comment]
Please, move this issue to Integration Foregoing issue tracker. That mod handles cross mod interaction.
