### ISSUE TITLE
Black hole unit + AE2 Storage bus

### ISSUE THREAD

**Issue by Goten87** [Buuz135/Industrial-Foregoing#135]
Industrial Foregoing Version: 1.5.13-103
TeslaCoreLib Version: 1.0.11
Crashlog (If Any): 
Modpack: Direwolf20 1.12 - 1.3

if i add a storage bus from AE2 on a Black hole unit it can read content but it cannot insert it from the storage bus

**Comment by Buuz135** [comment]
Are the settings on the bus correct, it has the both ways mode?

**Comment by Goten87** [comment]
yes

**Comment by Buuz135** [comment]
Can't replicate, can you add pictures of your setup? ![](https://i.imgur.com/2AMn5HL.gif)

**Comment by Goten87** [comment]
we have AE2 channels off

![2017-12-17_00 41 02](https://user-images.githubusercontent.com/1938598/34075312-0a7c2664-e2c3-11e7-9403-c81d3164fd1a.png)
![2017-12-17_00 41 11](https://user-images.githubusercontent.com/1938598/34075313-0e58a302-e2c3-11e7-96ec-57d3ed8c3125.png)

**Comment by Buuz135** [comment]
So you can insert but you can't extract, right?

**Comment by Goten87** [comment]
no the otherway arount
i can extract but not insert

**Comment by Buuz135** [comment]
Does the terminal allow you to put the items in and go to somewhere else or it doesnt allow you to do that?

**Comment by Goten87** [comment]
it will go to the drives but the priority of the storage bus is 400 higher then the rest exept the trashcan thats 1000 with filter items

**Comment by Buuz135** [comment]
Try if a normal hopper can insert to the BHU, if it can its an issue with your AE

**Comment by Goten87** [comment]
well a export bus can insert into it

**Comment by Buuz135** [comment]
Then its an issue with the priorities of you AE, nothing to do with the BHU

**Comment by Goten87** [comment]
ok let me test some stuff in single player on a server now but lets see what happens if its only a storage bus on the network

**Comment by Goten87** [comment]
oke i think its a AE2 bug sins i have it on insert only and its still showing the items in the terminal we are now gonne restart the server see if that fixes it
