### ISSUE TITLE
Information request: Essence fluid XP value?

### ISSUE THREAD

**Issue by desht** [Buuz135/Industrial-Foregoing#137]
Industrial Foregoing Version: any

Just a request for information, with a view to some cross-mod (PneumaticCraft: Repressurized / Modular Routers) support: what is the XP conversion ratio of your "essence" fluid?  I.e. how much XP does 1 mB of Essence represent?

Thanks!

**Comment by Buuz135** [comment]
So currently it is theXPOrbValue*20*essenceMultiplier. Where the essenceMultiplier is a config value with default 1
