### ISSUE TITLE
[FEATURE] Break all the leaves from a tree at one time so Fast Leave decay doesn't do it's work before the log is chopped

### ISSUE THREAD

**Issue by Buuz135** [Buuz135/Industrial-Foregoing#139]

**Comment by faceofcat** [comment]
that might be laggy for big trees... break the leafs first... logs last... that should solve problems with that.

**Comment by Buuz135** [comment]
It does that already but sometimes FLD gets triggered when half of them are broken

**Comment by faceofcat** [comment]
that sucks.
