### ISSUE TITLE
Laser Base and Drills

### ISSUE THREAD

**Issue by Xiaminou** [Buuz135/Industrial-Foregoing#14]
You can place blocks between the base and the drills and it will stick work:
https://youtu.be/TtsxavRQXlw

Also I tried changing which ores the laser generates but now it's only generating vanilla ores, am I doing something wrong or is it bugged?
https://pastebin.com/DBykqd2i

Minecraft: 1.11.2
Industrial Foregoing: 0.3-16
Forge: 2393

**Comment by Buuz135** [comment]
Try this version for the ores, I might derped a bit. https://mega.nz/#!u0ZhjLxI!lZCIOI1AuJITbT69mHfO4YbDY32iB95Ilyi_FN8LhY8

**Comment by Xiaminou** [comment]
Almost, now it's generating Ores but not using the metadata, it's generating basalt from IC² instead of uranium ore, and copper ore from TE instead of all the different ores.

**Comment by Buuz135** [comment]
Okay, I will get and update tomorrow, I have it fixed now

**Comment by Xiaminou** [comment]
Alright, thanks.

**Comment by Xiaminou** [comment]
I just noticed it's also not generating dense ores or mekanism's osmium, I think they're all metadata 0.

**Comment by Xiaminou** [comment]
![2017-07-15_14 46 09](https://user-images.githubusercontent.com/8670392/28239442-698faeb2-696c-11e7-9905-c38ee626b3f0.png)

Thank you.
