### ISSUE TITLE
Tree planter and harvester

### ISSUE THREAD

**Issue by OrionU** [Buuz135/Industrial-Foregoing#142]
Industrial Foregoing Version:  industrialforegoing-1.12.2-1.6.3-107
TeslaCoreLib Version: 
Crashlog (If Any): 

I am playing on FTB Direwolf version 1,4,0 and somehow the tree planter /  harvester  both stopped working, they dont plant tree's  and harvesting tree's also stopped working, they have power and the harvester have a valid output. It worked in the older version, havent made a change in the settings.

**Comment by Buuz135** [comment]
Is the machine paused or you have change the redstone settings on the machine?

**Comment by OrionU** [comment]
The machine is not paused and i havent changed anything on the machines, its just like they are operating with ghost logs. I hear the sound of leaves being harvested, but there are no trees.

**Comment by Buuz135** [comment]
Are you using some sort of protection plugin?

**Comment by OrionU** [comment]
No not that i am aware of, it happened when the server got updated to 1.4.0 , after that it stopped working.

**Comment by Buuz135** [comment]
Can't replicate try breaking and placing the machines

**Comment by OrionU** [comment]
Ok what i dit that seem to fix it, is unclaim the chunks. So when claiming a chunk normally keeps them loaded, when i unclaimed the treefarm it started to work, but then the tree farm doesnt produce when i am offline.

**Comment by Buuz135** [comment]
Are you using FTBUtils to claim them? Does it happen again when reclaimed?

**Comment by OrionU** [comment]
Yes i use FTBUtils to claim, when i reclaim the treefarm stops working. When unclaiming it starts again.

**Comment by Buuz135** [comment]
Can't replicate it, neither in SP and MP can you send me a picture of your setup?

**Comment by OrionU** [comment]
![2017-12-21_20 55 12](https://user-images.githubusercontent.com/34738042/34272657-61132ca8-e691-11e7-84a8-573d82f1264a.png)

as you see i have like 1 powercell for the energy, then the itemducts to get the items to my drawers and sapplins go first to planter rest gets voided in a drawer with a void upgrade.

**Comment by Buuz135** [comment]
It doesn't even happen in the DW Pack, the wierd thing is that it plays the harvest sound because it will never do that.

**Comment by OrionU** [comment]
Ive never had something like this happening, i guess its because of the loaded chuncks?

**Comment by Buuz135** [comment]
Don't think so

**Comment by SolarEclipz** [comment]
Actually I am having this same issue with ATM3. I noticed if I have claimed chunks it will not plant or harvest. The Plant Sower will make the sound and I will lose the sapling, but nothing will get planted. The only options are Member, Ally, and None for FTB utilities manager. If I remove Chunk load/claim there is no issues. Playing in MP world btw.

**Comment by Buuz135** [comment]
Thats the missing piece of the issue! The Fake Player settings! Thanks!

**Comment by Buuz135** [comment]
@OrionU Issue fixed by changing the Fake Player Status in the Team Settings Menu to ally or member
