### ISSUE TITLE
Fluid Crafter is not working

### ISSUE THREAD

**Issue by tgstyle** [Buuz135/Industrial-Foregoing#146]
Industrial Foregoing Version: 1.12.2-1.6.4-111
TeslaCoreLib Version: 1.12-1.0.12

I put the recipe in, put in the fluid. Nothing happens.
![2017-12-27_14 05 54](https://user-images.githubusercontent.com/5832709/34393382-3ba00068-eb0f-11e7-8723-82a52967625c.png)
![2017-12-27_14 06 26](https://user-images.githubusercontent.com/5832709/34393383-3d589988-eb0f-11e7-8ec1-781bdbac8bad.png)

**Comment by tgstyle** [comment]
2nd screen switched to other oredictionary entry for slag.

**Comment by Buuz135** [comment]
You need to lock the inventory, it says it in the manual.

**Comment by tgstyle** [comment]
Made no difference.
![2017-12-27_17 01 50](https://user-images.githubusercontent.com/5832709/34396408-b8f044d4-eb27-11e7-9c0d-c102af96f31a.png)

**Comment by Buuz135** [comment]
Are you sure that the recipe uses IE slag?

**Comment by tgstyle** [comment]
Yes.
![2017-12-27_17 07 35](https://user-images.githubusercontent.com/5832709/34396483-baba0bd2-eb28-11e7-8a64-96f19c9722ca.png)
![2017-12-27_17 08 56](https://user-images.githubusercontent.com/5832709/34396485-bc265912-eb28-11e7-90a8-3ee753afbd3d.png)

It is not just this recipe, I cannot get any recipe to work.

**Comment by tgstyle** [comment]
Version 107 works fine.

**Comment by Buuz135** [comment]
The fix is already in curse btw! :D

**Comment by tgstyle** [comment]
Thanks!
