### ISSUE TITLE
[Request] Non-pink slime recipe options

### ISSUE THREAD

**Issue by charlesbevans** [Buuz135/Industrial-Foregoing#148]
I'm not a fan of industrial slaughter in MC. I play an animal friendly game. I don't even like mob spawners. I'd like to see a way to create a pink slime substitute or have an alternative in recipes, even if it's only a config option.

**Comment by Buuz135** [comment]
Use Craftweaker to change the recipes. Making config options to change recipes are bit tedious, I have done it once, I don't want to repeat the experience.

**Comment by charlesbevans** [comment]
As reasons go, that's pretty reasonable. But, it was worth the ask.
Thank you for the great work and for the quick and considered response.
