### ISSUE TITLE
Machines using power when idle.

### ISSUE THREAD

**Issue by Unnoen** [Buuz135/Industrial-Foregoing#150]
Industrial Foregoing Version: 1.12.2-1.6.5-112
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): N/A

Issue: Machines will use their full power requirement even when idle/not working.
Expected: Machines will only use power when completing a work action.

**Comment by Buuz135** [comment]
Thats how they work, even though you can't see anything phisical happening, If the use power, they are doing something.

**Comment by Unnoen** [comment]
So a sower with no seeds in it should be constantly using power?

**Comment by Buuz135** [comment]
Yes, its scanning the area for spots to plant.

**Comment by Unnoen** [comment]
Why would it be scanning to plant if it has no seeds?
If all the spots are full of seeds, shouldn't it stop scanning?

Just seems very odd that completing actual work actions (planting seeds) uses the same if not less than sitting idle.

**Comment by Buuz135** [comment]
The EnderIO farming station used 80RF/t just by existing, I dont see any complaints there. It uses just 80RF/second when idle.

**Comment by Unnoen** [comment]
I guess I'm comparing it to MFR, I'm fairly sure there was no idle power drain, or at least it was much smaller than the work power drain.

**Comment by jfbarras** [comment]
I agree with Unnoen here that this is different from MFR. If Buuz135 wants it like that not much to do. Here are some middle-ground options:
- have a separate, configurable, idle power drain
- include an 'efficiency upgrade' with an upfront cost but no running cost
