### ISSUE TITLE
Better Translatability?

### ISSUE THREAD

**Issue by InterPlay02** [Buuz135/Industrial-Foregoing#151]
Hello!

Ahh... I don't want to bore you guys, but... What about adding a line in the lang file for each of these descriptions lines here:
![Item description](https://user-images.githubusercontent.com/23037423/34444326-79b8ab4c-ecb4-11e7-93e6-a6539fda3f02.jpg)
And also for that "Hold Shift for more info" thing...

Btw... Take a look at Tesla Core Lib page, here on github. I've done a pt-BR.lang file for it also!

Industrial Foregoing Version: industrialcraft-2-2.8.35-ex112
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12

**Comment by Buuz135** [comment]
Can you help me find anything that can't be translated, a part from what you mentioned and Book Pages, that I'm going to add too.

**Comment by InterPlay02** [comment]
That Redstone Control Thing... It seem not to be present in Tesla Core Lib, nor in Ind Foreg...
And, maybe Those info shown in waila/hwyla/one probe... I don't remember everything now, but I can take a look for you. But I'm going to bed now... Tomorrow, maybe... =]
