### ISSUE TITLE
No Reaction to Crescent Hammer

### ISSUE THREAD

**Issue by MarshTheBacca** [Buuz135/Industrial-Foregoing#152]
Industrial Foregoing Version: 1.6.5-112
TeslaCoreLib Version: 1.0.12
Minecraft Version: 1.12.2

I use your mod in my custom modpack along with the addon "Integration Foregoing". Every other machine reacts to a right-click with a crescent hammer from Thermal Foundation but the machines in this mod. I know it's a small issue but the amount of times I have to break it instead is just inconvenient.
You could call this a suggestion if this feature wasn't intended.

Thanks for any replies :)

**Comment by Buuz135** [comment]
This already works: https://i.imgur.com/74L4fq2.gifv

**Comment by MarshTheBacca** [comment]
Hey, that's not the issue I was outlining! It's when you sneak+right click the machines they don't break, also they don't retain their inventory.
