### ISSUE TITLE
Plant Sower does not work with Cocoa Beans

### ISSUE THREAD

**Issue by Solairn** [Buuz135/Industrial-Foregoing#155]
Does not accept cocoa beans to be "planted" on suitable jungle wood above.
Industrial Foregoing Version: 1.12.2-1.6.3-107
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any):

**Comment by Solairn** [comment]
The plant gather does not harvest mature cocoa beans either

**Comment by Buuz135** [comment]
Duh! Because Cocoa beans aren't a plant they are a fruit! I will add a Fruit Picker soon ™️
