### ISSUE TITLE
[ISSUE]Item Splitter has Inconsistent I/O, Breaking with Crescent Hammewr

### ISSUE THREAD

**Issue by MarshTheBacca** [Buuz135/Industrial-Foregoing#157]
Industrial Foregoing Version: 1.6.5-122
TeslaCoreLib Version: 1.0.12

![2017-12-31_20 20 18](https://user-images.githubusercontent.com/34864792/34464042-0e93954c-ee68-11e7-876d-ff149dc8f716.png)
![2017-12-31_20 12 30](https://user-images.githubusercontent.com/34864792/34464045-397af372-ee68-11e7-920f-8d00062b5643.png)
![2017-12-31_20 12 03](https://user-images.githubusercontent.com/34864792/34464049-57cbf6b4-ee68-11e7-9a22-f8a612cc10cf.png)
![2017-12-31_20 12 09](https://user-images.githubusercontent.com/34864792/34464053-766d7ed0-ee68-11e7-8e98-54bedd6e014d.png)
![2017-12-31_20 25 21](https://user-images.githubusercontent.com/34864792/34464063-bf1edd5e-ee68-11e7-81c0-7c300791309f.png)
![2017-12-31_20 12 25](https://user-images.githubusercontent.com/34864792/34464067-e28206b8-ee68-11e7-8e7f-75e8745123f3.png)
![2017-12-31_20 12 28](https://user-images.githubusercontent.com/34864792/34464071-f6fe26d0-ee68-11e7-9e20-6c31170208b4.png)

The I/O configuration doesn't match the sides? It only outputted items when I enabled the right-hand side, and it outputted to the front side. I do have another one of these Item Splitters for another machine and I placed it over and over again to see if the direction it is placed from has any part to play in it. That Item Splitter has no issues whereas the one in the screenshots does, probably due to the direction I placed it from.

ALSO, you misunderstood my previous issue, the crescent hammer does indeed rotate the machines, but "SHIFT"+"RIGHT-CLICK" doesn't break the machine. Also, it would be a nice feature for the machines to retain their inventory when broken which is a feature in the mod "Mekansim".

Thanks :)

**Comment by Buuz135** [comment]
I didn't misunderstood the issue, the SHIFT part wasn't mentioned, use the tesla wrench
