### ISSUE TITLE
[1.12] Cannot Export Items

### ISSUE THREAD

**Issue by EmosewaGamer** [Buuz135/Industrial-Foregoing#16]
I have not tested it with every machine, but it's safe to say that the Latex Processing Unit cannot export items.

**Comment by Buuz135** [comment]
Do you mean that they don't autoeject?

**Comment by EmosewaGamer** [comment]
Well, yeah. I even tried to see if it's a certain side, but it is not.

**Comment by Buuz135** [comment]
Machines do not auto eject, you need to pull from them with something else.

**Comment by EmosewaGamer** [comment]
I am using an itemduct from TE

**Comment by Buuz135** [comment]
Does it connect to the machine?

**Comment by EmosewaGamer** [comment]
Wait... mvn, forgot that the rubber gotten from the Processing unit needs to be crafted together before being smelted. I guess that it didn't pick it up because I had a Redstone Furnace on the other end.
