### ISSUE TITLE
[Feature Request] Enhance Mob Imprisonment Tool label for Villagers

### ISSUE THREAD

**Issue by calloatti** [Buuz135/Industrial-Foregoing#160]
In #144 you added the mob name to the MIT, a very useful feature. (Thanks!)

Is it too much to ask to add the type of villager when there is a villager imprisoned instead of just "Villager"?

Having to respawn every MIT with a villager to check what kind of villager you have gets tiresome fast.

**Comment by Buuz135** [comment]
I can't, there is a MC bug where Careers are different between client and server and it would be displayed wrong.
