### ISSUE TITLE
Bad performance with Tree Fluid Extractor

### ISSUE THREAD

**Issue by JoeSGT** [Buuz135/Industrial-Foregoing#161]
Industrial Foregoing Version: 1.12.2-1.6.6-163
TeslaCoreLib Version:  1.12-1.0.12
Crashlog (If Any):  --none-

when you setup a basic Tree Fluid Extractor
about 210 of them they start to cause lag here an image of this i had created a flat land test server with this and recorded the timings report
https://gyazo.com/36885d43e182191fdd8be6f4dc9b05fd
if you had a huge network server players are going to make a farm with this
and here is the timings report 
![66acc0dffe57db05db253c174a3928ad](https://user-images.githubusercontent.com/30296350/34502511-c31889f8-efe1-11e7-87bc-296e2f7fcc99.png)
https://timings.aikar.co/?id=d612ac676d224ec8981aa128752a3faa

EDIT: i forgot to mention i used this 
https://github.com/Buuz135/Industrial-Foregoing/commit/9a1793109ac928bc4f6bc945b61a646b2a6d18f4
commit to test it out

**Comment by Buuz135** [comment]
All of this only takes 7ms using the /forge tps command. I hope everything is good now. ![](https://i.imgur.com/huUEj9f.jpg) ![](https://i.imgur.com/aY02bvr.png)
