### ISSUE TITLE
[Feature Request] Integrate Bioreactor with Pam's HarvestCraft

### ISSUE THREAD

**Issue by RobertBouillon** [Buuz135/Industrial-Foregoing#162]
Industrial Foregoing Version: 1.12.2-1.6.3-107
TeslaCoreLib Version: 1.12-1.0.12

Love the mod. Playing on DW20 1.12. Bioreactor has a lean selection of consumables. Any chance you'd be willing to add pam's pickings to what it can cook?

**Comment by Buuz135** [comment]
Other mod integration is handled in Integration Foregoing, use it to have Pams stuff in the bioreactor.
