### ISSUE TITLE
Mob Duplicator spawns Slimes above the working area

### ISSUE THREAD

**Issue by calloatti** [Buuz135/Industrial-Foregoing#164]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.6.5-112
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): n/a

This is how the Mob Duplicator is set up. There is a glass ceiling one block above the working area.

![image](https://user-images.githubusercontent.com/12817862/34548778-affcc6f2-f0e2-11e7-8ce5-99f647e04463.png)

This is what happens when it is activated to duplicate slimes. Slimes spawn above the working area and then somehow noclip through the glass ceiling.

![image](https://user-images.githubusercontent.com/12817862/34548800-d42c8904-f0e2-11e7-962f-a1a28d8330af.png)

**Comment by Buuz135** [comment]
I blame that glass, it doesn't happen with normal glass, try moving the spawner 1 block lower

**Comment by InterPlay02** [comment]
If I know how this mod work, I would blame you setup idea. Slimes are bigger than the space above the working area. The working area (I think) means that those are the blocks they can spawn. So, What if a Big Slime spawns on the top most blocks of the working area? Probably it will escape the through that glass, or whatever you place there. Unless you build this down in the ground and have at least 10~15 solid blocks above it.

But, as I said. I don't know what I'm talking about.
