### ISSUE TITLE
Helping with the Translation

### ISSUE THREAD

**Issue by InterPlay02** [Buuz135/Industrial-Foregoing#166]
Hello!

You asked me for help to find anything that can't be translated!
So, here it is:

In the item splitter:
![faltando traduzir 3](https://user-images.githubusercontent.com/23037423/34570804-febe8214-f153-11e7-8a17-abab34a6df51.png)
![faltando traduzir 4](https://user-images.githubusercontent.com/23037423/34570825-09a3e8e0-f154-11e7-98af-161ebb9b7f3b.png)

In the Laser Base:
![faltando traduzir 5](https://user-images.githubusercontent.com/23037423/34570843-1ae83390-f154-11e7-86e9-96091e6d14d8.png)
And I have a question: The Laser Base don't was supposed to be rendering a laser beam from the bottom?
![faltando traduzir 6](https://user-images.githubusercontent.com/23037423/34570884-3deccbe4-f154-11e7-9ecd-c6f707ac0ea8.png)
In this image, all the laser drills are fully charged, the laser base IS working, but not rendering the laser beam. This was supposed to be like so?

In the Laser Drill:
![faltando traduzir 7](https://user-images.githubusercontent.com/23037423/34571018-991779f6-f154-11e7-97b3-5ac884d48a6a.png)

In the Stoneworks Machine:
![faltando traduzir 8](https://user-images.githubusercontent.com/23037423/34571045-b1b433aa-f154-11e7-8bf0-8bb77e64a91c.png)
![faltando traduzir 9](https://user-images.githubusercontent.com/23037423/34571046-b1d7e692-f154-11e7-9ebb-81cb660b5781.png)
![faltando traduzir 10](https://user-images.githubusercontent.com/23037423/34571049-b21017d8-f154-11e7-87bb-4604074b7d8f.png)
![faltando traduzir 11](https://user-images.githubusercontent.com/23037423/34571052-b27ec0a2-f154-11e7-87ee-ecdc10b424b6.png)
![faltando traduzir 12](https://user-images.githubusercontent.com/23037423/34571054-b2d4a15c-f154-11e7-8e86-1fa03213ee52.png)

In the Force Field Addon:
![faltando traduzir 14](https://user-images.githubusercontent.com/23037423/34571115-d63930ae-f154-11e7-8693-4b6c81bff4bf.png)

I couldn't find these lines in the language file of Ind Foreg neither Tesla Core Lib.
And that "Show working area" also... I couldn't find it anywhere...
PS.: I have a new lang file for the newer version, that I will upload soon. (If not uploaded yet)

**Comment by Buuz135** [comment]
The laser drill doesn't have the render at the bottom because it doesnt need direct vision to the void.

**Comment by InterPlay02** [comment]
I see.... Well... Even with that, you could make a laser beam. This would be really cool.
Because... It is a **LASER** Drill...
