### ISSUE TITLE
[Feature] Fluid Pump to push liquids into adjacent Black Hole Tank

### ISSUE THREAD

**Issue by donqixot** [Buuz135/Industrial-Foregoing#175]
Industrial Foregoing Version: 1.12.2-1.6.6-113
TeslaCoreLib Version: 1.12-1.0.12

Would it be possible to add a feature so that Fluid Pump push liquids into adjacent Black Hole Tank without any pipes from other mods? Thanks!

**Comment by Buuz135** [comment]
No, this mod doesn't push or pulls anything. And I don't find it a good idea for the mod.
