### ISSUE TITLE
[1.12.2] Feature: support Immersive Engineering Hemp

### ISSUE THREAD

**Issue by hron84** [Buuz135/Industrial-Foregoing#177]
The latest Plant Gatherer cannot harvest IE hemp crop. Plant Sower plants it correctly, but while other plants become harvested, hemps are not. Please support these crops.

**Comment by Buuz135** [comment]
Are you using Integration Foregoing?

**Comment by hron84** [comment]
No, I think not. FTB Revelation lacks that mod I think.

**Comment by Buuz135** [comment]
Then use it and request it to be added, it adds that kind of interaction.
