### ISSUE TITLE
More config entries, more enhancements

### ISSUE THREAD

**Issue by Warrock3280** [Buuz135/Industrial-Foregoing#178]
«IF» is awesome itself, but it needs more config options such as internal energy buffer.
Also compatibility with more types of upgrades (e.g. TE upgrade kits) would be great.

**Comment by Warrock3280** [comment]
UPD:

**Comment by Buuz135** [comment]
This is not an TE addon. And it already has too many config options, internal energy buffers for the machines doesnt matter.
