### ISSUE TITLE
not sure if its a bug

### ISSUE THREAD

**Issue by CharCharthemonkey** [Buuz135/Industrial-Foregoing#179]
Industrial Foregoing Version: 1.12-1.4
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): no crash logs

basically when locking a black hole unit or tank to only keep 1 item type in it it doesnt work and allows random items in even know its locked to 1 item type

**Comment by Buuz135** [comment]
If you are really in v1.4 of the mod, update it, it's a 4 month old version
