### ISSUE TITLE
#179 again

### ISSUE THREAD

**Issue by CharCharthemonkey** [Buuz135/Industrial-Foregoing#180]
Industrial Foregoing Version: 1.12.2-1.7.0-114
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): no crash

i derped on mod mumber but in #179 is the issue i just got the mod number wrong on accident cause i looked at the wrong mod but the same issue is still in

**Comment by Buuz135** [comment]
Not for me for the future, this happens when the BHU is locked and empty it allows to input anything.

**Comment by CharCharthemonkey** [comment]
well i have it locked to only allow say diamond essence but it literally allows anything to go in from it
