### ISSUE TITLE
conflit 

### ISSUE THREAD

**Issue by animetheque** [Buuz135/Industrial-Foregoing#181]
Industrial Foregoing Version: 1.12.2-1.7.0-114
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): 

https://pastebin.com/ZSB1U17A

https://pastebin.com/0vnbJTHH

https://pastebin.com/JtqzDHFR

message in launcher : The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game

**Comment by Buuz135** [comment]
Use forge version 1.12.2

**Comment by animetheque** [comment]
forge 14.21.1.2443 , 1.12 , which version to use?

thx

**Comment by animetheque** [comment]
works without any other mod with my forge

**Comment by Buuz135** [comment]
Forge 1.12.2 - 14.23.1.2590

**Comment by animetheque** [comment]
i search a compatible version of mod for MY forge , thx

**Comment by animetheque** [comment]
it ok , all is update , thx
