### ISSUE TITLE
[Suggestion] OreDict Items

### ISSUE THREAD

**Issue by EmosewaGamer** [Buuz135/Industrial-Foregoing#183]
I suggest adding the oredict entries that MFR used so that the MFR integration some mods have works with IF. The mods that detect the oredict entries, not the mod.

**Comment by Buuz135** [comment]
Can you elaborate more?

**Comment by EmosewaGamer** [comment]
Pink Slimeballs having the OreDict entries slimeball and slimeballPink, Plastic having itemPlastic, Fertilizer having dyeBrown and fertilizer,...
