### ISSUE TITLE
[Suggestion] Change the way Black Hole Tank works with items that can hold fluid.

### ISSUE THREAD

**Issue by calloatti** [Buuz135/Industrial-Foregoing#184]
Right now if you right click with an item that has some fluid in a Black Hole Tank, a bucket of fluid gets transferred from the item to the Black Hole Tank.

I suggest the following behavior, similar to how IE tanks work:

When you right click a BHT with an empty item that can hold fluid, fill up the item with the fluid.

When you right click a BHT with an item full of fluid, empty the fluid into the BHT.

When you right click a BHT with a partially filled item, fill up the item with the fluid.

This way you don't have to open up the BHT UI with your hand, change to the meat feeder. and click 128 times to fill it up.

**Comment by Buuz135** [comment]
Why are you closing your issues?

**Comment by calloatti** [comment]
Because I assumed you were just going to ignore them? If that is not the case please accept my apologies.

**Comment by Buuz135** [comment]
I have them fixed already, they arent pushed
