### ISSUE TITLE
[Feature Request] Animal Rancher should collect eggs

### ISSUE THREAD

**Issue by joselitosn** [Buuz135/Industrial-Foregoing#187]
As the title suggests, the Animal Rancher should include Chickens eggs by either sucking them or preventing them from spawning and generating an egg drop.

The Mob Crusher already pickup items in it's working area, maybe the Rancher could do the same but filtering to only eggs. 

There are ways to collect eggs with hoppers and blocks from other mods, but I still think it would be nice if the Rancher was the AIO solution for all animals.

Industrial Foregoing Version: 1.12.2-1.7.0-114
TeslaCoreLib Version: 1.12-1.0.12

**Comment by Buuz135** [comment]
As you said use other mods because mobs can drop more stuff than just eggs, they can drop feathers if some mod is installed

**Comment by joselitosn** [comment]
Shouldn't mod integration be moved to Integration Foregoing? I'm just asking because if I remember correctly the original MFR did handle Feathers and Eggs.

Not saying that you have to copy the exact features of it, but since the original intention is to mimic it's features and improve upon them, it might be worth taking a shot at it.

Also if you're willing to accept, I might make a PR for it.
