### ISSUE TITLE
[Bug] Mob Crusher voids items

### ISSUE THREAD

**Issue by joselitosn** [Buuz135/Industrial-Foregoing#188]
The Mob Crusher pickups items that are in it's working area as long as there are mobs in it. But if it's inventory is full, any picked items are voided. That is a problem if you drop something by mistake in the working area.

Industrial Foregoing Version: 1.12.2-1.7.0-114
TeslaCoreLib Version: 1.12-1.0.12

**Comment by calloatti** [comment]
Just want to mention that the Mob Crusher also voids xp orbs if the internal essence tank is full instead of leaving the orbs alone. (To be picked up by another machine that converts orbs to xp bottles for example)

**Comment by joselitosn** [comment]
I think it's kind of okay to xp be voided, since it's your responsability to drain it. But if it was ever decided that machines should not void fluids, the machines should probably stop working.

Anyways, I didn't test the patch yet but shouldn't the code test if the item lifespan is bigger than one minute before setting it to one minute?

https://github.com/Buuz135/Industrial-Foregoing/blob/df33a0ffae5520d1638308e535ea63ea53c9309c/src/main/java/com/buuz135/industrial/tile/mob/MobRelocatorTile.java#L97

**Comment by Buuz135** [comment]
No, the lifespan means how much it can live not how much it lived

**Comment by joselitosn** [comment]
Oh, nice! Thanks for clarifying and thank you for the patch. 👍
