### ISSUE TITLE
[Feature Request] Animal Feeder should handle more than one kind of animal at once

### ISSUE THREAD

**Issue by joselitosn** [Buuz135/Industrial-Foregoing#189]
If you have more than one kind of animal inside of the working area of the Animal Feeder, some animals are not fed. I'm not sure if it's meant to be like that by design or if it's just how the code works right now.

Industrial Foregoing Version: 1.12.2-1.7.0-114
TeslaCoreLib Version: 1.12-1.0.12

**Comment by Buuz135** [comment]
Do you have more than 35 mobs in the area, it will stop feeding if its too full.

**Comment by joselitosn** [comment]
I've taken a look at the code and what was exactly happening.

One of my animals died, leaving one pair uneven. What happens is the code get stuck at that animal, because it finds the first breedable animal and try to find it's matching pair. But since it can't find a pair it stops at that animal. All other animals are not bred.
