### ISSUE TITLE
[Suggestion] Speed Upgrades for some machines

### ISSUE THREAD

**Issue by darkman1984** [Buuz135/Industrial-Foregoing#198]
Industrial Foregoing Version: 1.7.0-114
TeslaCoreLib Version: 1.0.12

Hi there :)

I really love the Mod since i played Minecraft with MFR, but i really miss some Speed Upgrades. Is it possible that you add one for some machines like the plant gatherer and so on?

By the way: Is it possible that you implement that the mob duplicator uses more RF per mob depending on which difficulty the mob is? Would be great! 

Thx :)
DaRkMaN

**Comment by Buuz135** [comment]
Use tesla core lib speed addons
