### ISSUE TITLE
[1.12][1.1-23] Unable to craft block

### ISSUE THREAD

**Issue by RhyaCeri** [Buuz135/Industrial-Foregoing#20]
Forge: 2424
Version: 1.1-23

Issue: Unable to craft the 'Animal Growth Increaser' block, block doesn't show up to be able to craft in the crafting station/table.

![image](https://user-images.githubusercontent.com/30450339/28598206-00a2766a-719a-11e7-83d6-3cdd0515ba52.png)

**Comment by Buuz135** [comment]
I might  have forgotten to add a recipe, if you have crafttweaker installed feel free to add a recipe for it until next version comes out. 😛
