### ISSUE TITLE
Ticking block entity crash

### ISSUE THREAD

**Issue by cowardlyDog** [Buuz135/Industrial-Foregoing#201]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.7.1-115
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): https://pastebin.com/HidUyE3M

**Comment by Buuz135** [comment]
Se comments in #200

**Comment by cowardlyDog** [comment]
Thanks!

**Comment by cowardlyDog** [comment]
Hey I see you removed the last version 1.7.1-115 from curseforge, in case it helps using 1.12.2-forge1.12.2-14.23.1.2577 didn't solve the crash. What's causing it is the plant gatherer having full energy apparently, I had to remove that block with MCEdit to stop it from crashing.
