### ISSUE TITLE
The "plant gatherer" and the "plant sower" issue/bug

### ISSUE THREAD

**Issue by Klen97** [Buuz135/Industrial-Foregoing#203]
Industrial Foregoing Version: 1.7.0
In the FTB Revelation Modpack I am in a server, the  "plant gatherer" and the "plant sower" doesn't work. It worked for like 2 days, nonstop, I used them to farm birch trees. But suddenly stopped working (I had a big laggat that time but it's from my side, so not from the server). The plant gatherer don't chopping the trees, and the plant sower don't plant the saplings. Tha plant sower output the sound (when you plant a sapling) but the sapling doesn't appear. It have everything to run.

At the machine's hub there is everything O.K.

We tryed to relocate to another chunk but that don't worked. Than we restarted the server and the bug reamined. 

(It's the FTB Revelation pack 1.4 version)

What can we do for fixing that ?

**Comment by Buuz135** [comment]
Is the area protected with FTBUtils?

**Comment by Klen97** [comment]
Utils ? Is that the protecting thing with the teams ? It's brotected by me

**Comment by Buuz135** [comment]
Change your `Fake Player Status`  in the Team Settings Menu to ally or member

**Comment by Klen97** [comment]
Awwwww Yeah I found the issue than, If I set the block editing to "member" it's doesn't work

**Comment by Klen97** [comment]
Yeah, thank you, it was the problem :)
