### ISSUE TITLE
Spawners won't spawn Pink Slimes when changed.

### ISSUE THREAD

**Issue by JadeDrgn** [Buuz135/Industrial-Foregoing#204]
Industrial Foregoing Version: 1.7.0-114
TeslaCoreLib Version: 1.12-1.0.12

Whenever I change a monster spawner to spawn pink slimes, whether it's with creative or Actually Additions Spawn Changer, Pink Slimes will not spawn from them at all. Draconic Evolutions' "Stabilized Spawner" also does not spawn them, though I believe it's related to them not spawning from the normal spawner anyway. They do spawn fine from a mob duplicator however.

**Comment by Buuz135** [comment]
I think I can live with that, using my own mod to spawn them.
