### ISSUE TITLE
Block Placer & Breaker don't work on server

### ISSUE THREAD

**Issue by ShinyChunks** [Buuz135/Industrial-Foregoing#206]
Industrial Foregoing Version: 1.7.1
TeslaCoreLib Version: 1.12-1.0.12

The block breaker and the block placer don't seem to work for me on my server. I tried the exact same setup in single player and it works...
Any idea how to fix that?

**Comment by Buuz135** [comment]
Is the area protected?

**Comment by ShinyChunks** [comment]
Yeah that also came in my mind right now. It works now, so nevermind.
But thanks for the quick reply ;)
