### ISSUE TITLE
Broken CraftTweaker integration

### ISSUE THREAD

**Issue by NillerMedDild** [Buuz135/Industrial-Foregoing#208]
Hey!

The CraftTweaker method `LaserDrill.remove(IItemStack output);` doesn't seem to work.

[Script](https://gist.github.com/NillerMedDild/8d1988b29ce09b1d011bddae50bc1132)
The LaserDrill.remove entries start at line 72.
I get no errors, and the rest of the script works just fine.

Industrial Foregoing Version: industrialforegoing-1.12.2-1.7.1-116
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
CraftTweaker2-1.12-4.1.1
Crashlog (If Any):

**Comment by NillerMedDild** [comment]
Screenshots taken in the same instance:
![billede](https://user-images.githubusercontent.com/21295394/35766161-ef0e182a-08d2-11e8-9c79-0b2b1a17883f.png)

That ore is removed on line 78

![billede](https://user-images.githubusercontent.com/21295394/35766169-06c55e2e-08d3-11e8-8bad-8489631a307c.png)

**Comment by Buuz135** [comment]
Don't use craftweaker 4.1, it seems that it broke everything

**Comment by Buuz135** [comment]
Btw, if you are talking about the cobalt and ardite ore chunk, they have metadata

**Comment by NillerMedDild** [comment]
I downgraded CraftTweaker and the issue persists.

Ah you're right about that, corrected the metadata. Still all the other entries are correct, and those ores haven't been removed.

![billede](https://user-images.githubusercontent.com/21295394/35767534-0025f086-08ee-11e8-9488-5ad4fad15eb0.png)
Matching the script line 78

**Comment by NillerMedDild** [comment]
Fixing the Ardite/Cobalt entries removed the ore chunks correctly, however ores from Thermal Foundation, RFTools and Mystical Agriculture still aren't removed, so I'm guessing the bug isn't in Industrial Foregoing.

**Comment by Buuz135** [comment]
You might want to try to remove some Integration Foregoing features

**Comment by NillerMedDild** [comment]
Nice, thank you!
