### ISSUE TITLE
[1.11.2] Crash when re-entering a world

### ISSUE THREAD

**Issue by Xiaminou** [Buuz135/Industrial-Foregoing#21]
Crash when re-loading a singleplayer world, happens every time but not for every world.

Crash Report: [crash-2017-07-29_20.19.59-server.txt](https://github.com/ForestryMC/Binnie/files/1185139/crash-2017-07-29_20.19.59-server.txt)
**mezz edit**: https://gist.github.com/mezz/2983889706ec3d231b378806c82fd8da

Environnement: Singleplayer
Minecraft: 1.11.2
Binnie's: 2.1.0.8
Forestry: 5.3.4.152
Forge: 2425
Modlist: [list.txt](https://github.com/ForestryMC/Binnie/files/1185137/list.txt)

https://github.com/ForestryMC/Binnie/issues/231#issuecomment-318857368

**Comment by Buuz135** [comment]
Can you try this version please? http://dyonovan.com:8111/repository/download/IndustrialForegoing_1112/140:id/build/libs/industrialforegoing-1.11.2-0.3-20.jar

**Comment by Xiaminou** [comment]
Yep, looks like that fixed it.

**Comment by Buuz135** [comment]
Nice, I will have a release today
