### ISSUE TITLE
Option to disable cobblestone replacement while pumping liquids

### ISSUE THREAD

**Issue by Yzelast** [Buuz135/Industrial-Foregoing#211]
Industrial Foregoing Version: 1.12.2-1.6.5-112
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): none

Hi guys, i wanna ask if would be difficult to add an option to just pump a liquid without replacing it with cobblestone, the industrial foregoing pump is the only one in my pack that i don't use cuz it's annoying to have a river replaced with cobblestone after work.

**Comment by Buuz135** [comment]
If you want water, you can use the water condensator

**Comment by Yzelast** [comment]
I know that i can use it, but the problem is that the pump replaces water source with cobblestone, i was asking an option to only remove the source block. In my pack water is not infinite so the condensator is not an nice option...
