### ISSUE TITLE
What is the 4 dark green slots in the gui for?

### ISSUE THREAD

**Issue by scifibob** [Buuz135/Industrial-Foregoing#212]
Industrial Foregoing Version: 1.6.6
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): none

I can't seem to find any documentation for these slots.
There is no hint in the gui.

**Comment by Buuz135** [comment]
What dark green slots? The ones in the right?

**Comment by scifibob** [comment]
Yeah

**Comment by Buuz135** [comment]
For addons
