### ISSUE TITLE
Resource fisher stops working after about an hour or less.

### ISSUE THREAD

**Issue by NamesReed** [Buuz135/Industrial-Foregoing#214]
Industrial Foregoing Version: 1.7.0-114
TeslaCoreLib Version: 1.10.12
Crashlog (If Any): 

I'm only feeding about 30 rf/t to it.  But after 30 mins to an hour it continues to use RF, but stops gathering anything.

breaking and replacing it didn't seem to fix it, but breaking and replacing in a different chunk did seem to fix it. 

Also relogging or travelling to another dimension fixes it.

**Comment by Buuz135** [comment]
You will have to let me know if it's really fixed in the version 1.8.0 that will come out soon as it is a wierd thing to test.
