### ISSUE TITLE
Plant Interactor stops working.

### ISSUE THREAD

**Issue by Lethann** [Buuz135/Industrial-Foregoing#215]
Industrial Foregoing Version:  1.7.0
TeslaCoreLib Version: 1.0.12
Crashlog (If Any): none

Running FTB Revelations modpack v1.4.0 - Solo survival game

Like some other reports, I had this working fine then all of a sudden it stopped working, I think specifically after I added a range extender (lvl 3).  Funny thing is my sandbox creative game has the big lvl 12 and it's going strong after hours and hours and save and reloads. I've tried some of the suggestions I've seen before: breaking it; exiting game; jumping into the mining dimension;  breaking it & moving it to mining dimension; changing team member settings, claiming chunks, trying to reload or clear chunks, anything I could think of. This isn't just with pam's stuff either. It's not picking up regular minecraft crops either (all in this modpack are set to keep their places once interacted with).

It's using a micro tick of RF (-4RF) but not doing a full cycle. Almost like it's stuck on the 0 range extender? Not sure what is causing it. I'll ask my husband if he's having the same issue on his survival game.

**Comment by Buuz135** [comment]
Use v1.7.1
