### ISSUE TITLE
[1.12] A few feature requests/possible bugs

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [Buuz135/Industrial-Foregoing#216]
Industrial Foregoing Version: 1.6.6-113
TeslaCoreLib Version: 1.12- 1.0.2
Crashlog (If Any): None

Was going to suggest upgrading books in the enchantment applicator, but I noticed it was an 1.11 bug that it wasn't doing that, well now it's not doing that in 1.12

A fluid convertor would be nice, as well as a way to get EXP from mob essence.

I'm pretty sure this was fixed in the next few versions, but in case it wasn't mekanism pipes seem to be attempting to insert into the output slot in black hole units.

Speaking of black hole units, do they void excess? If not an upgrade to do that would be nice.

A way to dupe enchanted books would be good too, with essence and power of course. Bibliocraft is the only mod I've seen that's added a way...

**Comment by Buuz135** [comment]
I will think about some of the stuff
