### ISSUE TITLE
Lava Fabricator does not output lava

### ISSUE THREAD

**Issue by trentet** [Buuz135/Industrial-Foregoing#217]
Industrial Foregoing Version: 1.6.6
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): N/A

I've found that the Lava Fabricator does not allow me to output lava through hardened fluiducts or directly through a fluid transposer. I've watched multiple tutorials involving the MineFactory Reloaded version of the Lava Fabricator, and all of them allow you to simply connect fluiducts to the lava fabricator and then to a tank of some kind and it would automatically begin outputting the lava. Without this feature, lava must be gathered manually from the fabricator, and this is incredibly inefficient and renders the fabricator almost useless. This also prevents some large and incredibly efficient power systems from being created.

**Comment by Buuz135** [comment]
Use a servo, it wont "prevent" anything
