### ISSUE TITLE
Server crash - Block placer - Forestry crosspost.

### ISSUE THREAD

**Issue by ProsperCraft** [Buuz135/Industrial-Foregoing#218]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.7.2-117
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): 

https://github.com/ForestryMC/ForestryMC/issues/1984

**Comment by Buuz135** [comment]
Fixed on Forestry side
