### ISSUE TITLE
Suggestion for the rancher

### ISSUE THREAD

**Issue by blockbreaker1361** [Buuz135/Industrial-Foregoing#219]
Would it be possible for there to be either a config option or an option in the machine itself to adjust the effect radius of the rancher machine? I believe the default radius is 7x7. I would like to see it go from 3x3 up to 7x7 or higher and your upgrades would still work the same.

**Comment by Buuz135** [comment]
Currently my system doesnt allow me to specify which range upgrades can go in, I will change it in the future.

**Comment by InterPlay02** [comment]
Or you could just add some downgrade addons. So we can decide what will be the size of the affected area of any machine.
