### ISSUE TITLE
[Request]Spawn exact copy

### ISSUE THREAD

**Issue by Thedrummonger** [Buuz135/Industrial-Foregoing#22]
I was wondering if it would be possible to allow the mob duplicator to spawn an exact copy of a mob.
Thanks!

**Comment by Buuz135** [comment]
I thought of adding it and some people thought it would be a bit cheaty as you can depend anything because you can make entities carry anything. Maybe in the future with something very complicated.

**Comment by Thedrummonger** [comment]
Yeah that would be an issue. Didn't minefactoryreloaded have a method to force mobs spawned with the auto-spawner to not drop what they're holding? Could something like that be done?
