### ISSUE TITLE
Extraction from Black Hole Tank with fluid container

### ISSUE THREAD

**Issue by PG-Fuury** [Buuz135/Industrial-Foregoing#222]
Couldn't find a way to fill my ImmE Jerrycan with ImmP Gasoline from the BHT itself, so I had to resort to pumping to a TE portable tank and filling from there.

Is this intentional? Or could an extraction field be added to the GUI?

**Comment by Buuz135** [comment]
What version are you using?

**Comment by PG-Fuury** [comment]
current FTB:Revelation version, 1.12.2-1.7.0-114

**Comment by Buuz135** [comment]
In 1.7.1 should already work better and fill containers when rightclicked
