### ISSUE TITLE
Link to CraftTweaker is wrong

### ISSUE THREAD

**Issue by Zer0Lyfe** [Buuz135/Industrial-Foregoing#225]
new Link:
http://crafttweaker.readthedocs.io/en/latest/#Mods/Industrial_Foregoing/IndustrialForegoing/

Old link:
http://crafttweaker.readthedocs.io/en/latest/#Mods/IndustrialForegoing/IndustrialForegoing/

**Comment by Buuz135** [comment]
Fixed
