### ISSUE TITLE
Ore Processor not accepting many kinds of ore

### ISSUE THREAD

**Issue by Saklad5** [Buuz135/Industrial-Foregoing#226]
Industrial Foregoing Version: 1.6.6 (1.12.2-1.12-2)
TeslaCoreLib Version: 1.12-1.0.12 (1.0.12)

The Ore Processor is one of the only ways to automatically Fortune ores, and I don’t know of any other way that doesn’t involve placing blocks in the world. Unfortunately, it seems that the list of valid ores is incredibly limited, as I have confirmed the following cannot be inserted in the Direwolf20 1.12-1.7.1 modpack:

- Dimensional Shard Ore (RFTools)
- Ender Draconium Ore (Draconic Evolution) (Oddly enough, Draconium Ore works fine)
- Aquamarine Shale (Astral Sorcery) (Bizarrely, it also cannot be broken down by a Refined Storage Destructor with a Fortune Ⅲ upgrade, but can be broken manually with a Fortune tool)

This is extremely irritating, as there is no way of seeing what is supported and what isn’t.

I don’t really understand why there is a limit on the blocks that are accepted at all, honestly. Just accept all items that can be placed, and emulate breaking them with Fortune Ⅲ the same way you do now.

**Comment by Buuz135** [comment]
Can you check if those blocks have an oredictionary entry?

**Comment by Saklad5** [comment]
Ah, I see part of the problem. You’re filtering for OreDictionary entires that start with 'ore', I assume, and for some reason Nether Draconium and Ender Draconium does not have an entry despite being the same block ID with a different damage value. Dimensional Shard Ore does not have an entry at all. I might have to go bug those mod authors about that if they don’t already know.

Aquamarine Shale, however, _does_ have an entry as oreAquamarine.

**Comment by Buuz135** [comment]
Aquamarine Shale is using a Deprecated method to get the drops from https://github.com/HellFirePvP/AstralSorcery/blob/8611d9558db776cf74d96b0b9be3b1377a471ea0/src/main/java/hellfirepvp/astralsorcery/common/block/BlockCustomSandOre.java#L78 and should be change to the method `Block#getDrops(NonNullList<ItemStack> drops, IBlockAccess world, BlockPos pos, IBlockState state, int fortune)`

**Comment by Saklad5** [comment]
That explains why the Refined Storage Destructor wasn’t working. Thanks. In that case, it seems like this is all the fault of other mods. I’ll close this issue.
