### ISSUE TITLE
Ticking Block Entity Crash

### ISSUE THREAD

**Issue by Moobien** [Buuz135/Industrial-Foregoing#227]
I crafted and placed 3 Plant interactors with no problems, the first one hooked up to power fine but the second one crashed my game. since then I am unable to get into that world due to crashing.

Industrial Foregoing Version: industrialforegoing-1.12.2-1.7.2-117
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): 

https://gist.github.com/Moobien/36a21a035b17b4931ff3ceb703fc5d13
https://gist.github.com/Moobien/6ba1c1faa1be0ed4dbc625dacccbf1fa

**Comment by Moobien** [comment]
Updated the mod to industrialforegoing-1.12.2-1.8.0-118 and the crash persists

**Comment by Buuz135** [comment]
That looks like a Gentle harvest issue more than Industrial Foregoing one

**Comment by Moobien** [comment]
Will remove it and test. Will raise an issue with them and link it to here.
