### ISSUE TITLE
[1.12] Crash with Mekanism Cables

### ISSUE THREAD

**Issue by MasterGeneral156** [Buuz135/Industrial-Foregoing#23]
**Forge:** 14.21.1.2443 for 1.12
**Industrial Foregoing:** 1.12-1.1-24
**Mekanism:** Homebaked 9.3.3 (https://github.com/thommy101/Mekanism/tree/1.12_firstpass)

Anyway, what happens is a server mate of mine places the Harvester, and attempts to power it with Mekanism Cables, which causes a crash. Other RF Transportation mods appear to work fine, just not Mekanism cables.

Crash Report: https://pastebin.com/B3At7Rp2

If I need to report to someone else, please let me know :P

**Comment by Buuz135** [comment]
It just got reported where it belongs so don't worry about it https://github.com/faceofcat/Tesla-Core-Lib/issues/7
