### ISSUE TITLE
FTB Utilities breaks machines that place/break blocks

### ISSUE THREAD

**Issue by StrayanDropbear** [Buuz135/Industrial-Foregoing#231]
Industrial Foregoing Version: 1.8.1-120
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): 

For some strange reason FTB Utilities is breaking machines that place/break blocks. After some testing I've figured out its the team permission for "Required Level for Block Editing". If that option is set to "member" no machines can place/break blocks, but if its "none or "ally" it works. 

I'm not sure who's at fault here, I can submit a bug report for FTB Utilities if needed.

**Comment by Buuz135** [comment]
I don't think I can do much about it, it seems that the Fake Player option changes randomly on update. People have reported that the machines were working before and suddenly stopped working.

**Comment by TheCodedOne** [comment]
Fixed from LatvianModder/FTBLib@6f1d7a5
