### ISSUE TITLE
Plant Machines stop functioning inside a colonie (Minecolonies)

### ISSUE THREAD

**Issue by boosterdev** [Buuz135/Industrial-Foregoing#232]
Once a colonie is established, plant machines within range of the colonie will stop functioning, it gets power but that's about it.

Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.1-120
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): N/A

**Comment by Buuz135** [comment]
I can't do much about it, if Minecolonies stopa fake players from doing stuff I can't override it.

**Comment by boosterdev** [comment]
ah ok, ill trash minecolonies then :+1:

**Comment by boosterdev** [comment]
Disabling 

> B:enableColonyProtection=false 

Allows fake players, this is safe on single player, or on a server where you build with friends.
