### ISSUE TITLE
Protein Generator doesn't accept Tesla addons/upgrades

### ISSUE THREAD

**Issue by Budgiebrain994** [Buuz135/Industrial-Foregoing#234]
Industrial Foregoing Version: 1.7.1
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): --

Speed and Energy upgrades by TeslaCoreLib aren't accepted in the Protein Generator.
They work correctly in the Protein Reactor.

I took a look at the source code and it looks like it doesn't accept them as it's a generator-type block. Have I got the right idea? I thought that a speed upgrade could help the rate at which protein is converted into power.

Thanks for the mod, it's awesome :)

**Comment by Buuz135** [comment]
Yes, it is intended as you can use multiple generators/reactor
