### ISSUE TITLE
All fluids emit light, most fluids have a temperature that sets players on fire

### ISSUE THREAD

**Issue by thehobojoe** [Buuz135/Industrial-Foregoing#237]
Industrial Foregoing Version: 1.7.2
TeslaCoreLib Version: 1.0.12

From FluidRegistry: https://github.com/Buuz135/Industrial-Foregoing/blob/master/src/main/java/com/buuz135/industrial/proxy/FluidsRegistry.java

Every fluid with a temperature of 600 sets players on fire. That list includes meat, latex, sewage, sludge, biofuel, and protein. Also, less of a bug but more missing functionality, every fluid has the same viscosity settings.

This is an issue I'd be happy to fix myself - I've been wanting to contribute to this mod and adding back missing fun things from MFR like status effects from fluids is something I'd like to do. Assuming the author is willing to take a PR for that. :)

**Comment by Buuz135** [comment]
The only fluid that doesn't make much sense having it that hot is latex but latex but you can change them if you want. Just don't add interacting effects as the straw already does it.
