### ISSUE TITLE
Disabling sewer power requirements in config does not work

### ISSUE THREAD

**Issue by thehobojoe** [Buuz135/Industrial-Foregoing#238]
Industrial Foregoing Version: 1.7.2
TeslaCoreLib Version: 1.0.12

setting `energyForWork` to `0` or setting `workDisabled` to `true` (not entirely sure what this setting is supposed to do) fails to actually disable any power requirements, the sewer still won't collect anything without power.

**Comment by Buuz135** [comment]
Energy settings only apply to newly placed machines not already placed ones.
