### ISSUE TITLE
Plant Gatherer Won't Harvest Wood With Range Upgrade

### ISSUE THREAD

**Issue by PessimisticBastard** [Buuz135/Industrial-Foregoing#239]
Industrial Foregoing Version: 1.12.2-1.8.2-121
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): N/A

The plant gather I'm using seems to be having issues harvesting trees when the range upgrade is in it. If I take the range upgrade out of the machine, let it start gathering, then put the upgrade back in, it will harvest all the wood in range. Have to keep taking it out and putting it back in to make it work.

**Comment by Buuz135** [comment]
Just to make sure, is the area protected?

**Comment by PessimisticBastard** [comment]
I have the chunk claimed with FTB Utilities, but that hasn't stopped it from working before. This is just a singleplayer world, if it makes any difference.

**Comment by Buuz135** [comment]
Check if the FTBU Fake player setting is allowed

**Comment by PessimisticBastard** [comment]
Where would that be under?

**Comment by Buuz135** [comment]
On the gear in the top left of your inventory

**Comment by PessimisticBastard** [comment]
There doesn't appear to be a setting for fake player under any of the tabs.

**Comment by Buuz135** [comment]
Can I get some pics of your setup?

**Comment by Aphyxia** [comment]
I have the same problem. Trees are not being gathered. When I remove the range upgrade and instantly put it back it starts working again but it seems slower than before. But after a while it stops gathering again...
Area is chunk loaded.
I was on version 117 before updating to the latest.

**Comment by Buuz135** [comment]
I need pictures of your setups please!

**Comment by PessimisticBastard** [comment]
Sorry, I was busy all of yesterday. Here's a picture: https://i.imgur.com/Lolqtl4.png

**Comment by Buuz135** [comment]
Can you show me the working area of it?

**Comment by Buuz135** [comment]
I found the issue! Dont panic!

**Comment by KITbutler** [comment]
Not sure if this is the same problem, but as of V121 the Plant Gatherer breaks when dimension hopping, at least via Compact Machines. The chunks are claimed and loaded by a ChickenChunks chunkloader, everything works fine in V120.

Might be a recurrence of #185 or similar issues.

**Comment by PessimisticBastard** [comment]
Working area?

**Comment by Buuz135** [comment]
What do you mean by break  KITbutler do they stop working when you are not in the dimension?

Can you try this version out @PessimisticBastard 
[industrialforegoing-1.12.2-1.8.3.jar.zip](https://github.com/Buuz135/Industrial-Foregoing/files/1753133/industrialforegoing-1.12.2-1.8.3.jar.zip)

**Comment by KITbutler** [comment]
As in the previous issue the machine seems to eternally run in an "idle" state flickering between 0 and 3 RF/t as if there were no valid targets in range. Breaking and replacing the machine fixes it temporarily.

I have not checked my harvest while in a different dimension, this is only the state I find them in after returning.

**Comment by Buuz135** [comment]
It might be the same issue try the version out

**Comment by KITbutler** [comment]
Appears to be fixed, at least I didn't get any stalls from relogging into a different world and back again, Aroma's mining world portal and Compact Machines where V121 has a near 100% failure rate.

**Comment by PessimisticBastard** [comment]
Issue's closed, but I thought I should say that it appears to have fixed the issue. Nice going!

**Comment by Aphyxia** [comment]
Issue is fixed but the surrounding area wood collection is rather lackluster. This is what my wood farm's surroundings look like now: https://gyazo.com/3ca983b819f6b7ce9d92bbdd663fba12
Previously it cleared all this.
