### ISSUE TITLE
Meat Feeder issue

### ISSUE THREAD

**Issue by Guybrush0** [Buuz135/Industrial-Foregoing#240]
Industrial Foregoing Version: 1.8.3
TeslaCoreLib Version: .0.12

playing on server, using the meat feeder dc's the client when trying to feed player,

**Comment by mcdodge34** [comment]
I can relate to this issue, I wanted to get the new saturation promised by the 122 update from 121, so I put the meet feeder in my backback and did a little exercise so I would need some food, when I wanted to get the feeder back into my inventory, I got Internal server error, I cannot connect to my server anymore, I will need to resort to a fresh backup

**Comment by boosterdev** [comment]
#253
