### ISSUE TITLE
Plant Gatherer not harvesting trees. 

### ISSUE THREAD

**Issue by KahnWolfe** [Buuz135/Industrial-Foregoing#241]
Industrial Foregoing Version: 1.12.2 1.8.2-121
TeslaCoreLib Version: 1.12.2-1.0.12
Crashlog (If Any): None

The plant gatherer is locking up since I went to this updated version in the Direwolf20 Pack. All the harvesters broke and are no longer harvesting trees. Occasionally taking range upgrades out and putting them back in clears the issue. Other times simply cutting down one or two trees manually clears it. Generally though it is acting like it is stuck on a block that it doesn't know what to do with and hangs up on that particular block. Once that block is cleared or its search resets it starts working again, but then will randomly just stop and go back to being hung once more. The power constantly flickers like it is in idle mode and waiting for something to harvest, but it never actually performs an action of its own accord.

**Comment by Buuz135** [comment]
Duplicate #239
