### ISSUE TITLE
Items of Black Hole Unis disappearing in inventory

### ISSUE THREAD

**Issue by EscolarProgramming** [Buuz135/Industrial-Foregoing#242]
Industrial Foregoing Version: 1.6.6
TeslaCoreLib Version: 1.12-1.0.12
Crashlog (If Any): No Crashlog

There is a bug with the Black Hole Units, when you Shift-click to fast in Black Hole Units to put items instant in your inventory. You can add 4-5 stacks of items without problems, but when you add more the items are very buggy. You can see them in your inventory, but when you close the GUI and open another inventory, most of the stacks are disappearing and again in the Unit. They don't get lost, because when you look into the Unit the disappeared stacks are in it again, but it's very annoying if you can only take a few stacks with you.
I hope you can understand the problem :)

**Comment by Buuz135** [comment]
That's a lag issue, I can't do much, but I will try to make something about it
