### ISSUE TITLE
Animal rancher continues to milk even when internal tank is full

### ISSUE THREAD

**Issue by Ezence** [Buuz135/Industrial-Foregoing#243]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.2-121
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12

It makes using this mod with Animania difficult because each time a cow is milked they need to drink water. Ideally, if the internal tank is full the machine should stop milking cows.

**Comment by boosterdev** [comment]
I agree with that.

**Comment by ChloeDawn** [comment]
This bug is present again in 1.15 (industrial-foregoing-1.15.2-2.3.3-e356e61)

**Comment by Spongman** [comment]
this is still present in 1.16: industrial-foregoing-1.16.5-3.2.9.1-fbef27c

energy is used even when the tank is full.

however, if there are sheep and none have wool, then no energy is used.
