### ISSUE TITLE
Plant Gatherer doesn't work with range addon 6( It was working previously) 

### ISSUE THREAD

**Issue by GizliKodcu** [Buuz135/Industrial-Foregoing#244]
Industrial Foregoing Version: 1.8.2-121
TeslaCoreLib Version: 1.0.12
Crashlog (If Any): 
Plant Gatherer doesn't work with range addon 6( It was working previously). In front of it there was fully filled 13x13 farm of logs and it didn't chop them down. Once i took out the range addon it did however.

**Comment by Buuz135** [comment]
Duplicate #239
