### ISSUE TITLE
suggestion: round robin for input into resourceful furnace

### ISSUE THREAD

**Issue by DoomSquirter** [Buuz135/Industrial-Foregoing#248]
might be good if resourceful furnace uses round robin to input items coming in to utilize the 3 items at a time cooking?

this, vs just filling first slot, then second, then third.

**Comment by Buuz135** [comment]
Just enchant the addon and it will insert it so fast that you wont need it

**Comment by DoomSquirter** [comment]
enchant addon?  What?

No clue what you're talking about there, but the issue isn't that it's moving items in fast enough, it's that if you don't have enough items coming in to make a complete stack, it's still not cooking more than one item at a time, but I guess that issue could go both ways so you're way is probably better.

**Comment by AssB0ys** [comment]
Came here to ask this also. I am trying to automate the resourceful furnace but it only accepts items in the first(of the three) slot so it doesn't smelt three items at a time unless you input manually.
