### ISSUE TITLE
Petrified Fuel Generator intended that way?

### ISSUE THREAD

**Issue by davqvist** [Buuz135/Industrial-Foregoing#25]
MC 1.12.1
Forge 2446
IF 1.1-25

Sorry, but I was wondering if the Petrified Fuel Generator is intended the way it is, that it doesn't extend the burn time of the fuel, rather keep the burn time always the same and instead change the power produced.
Because the way it is, I feel that this is very unbalanced. If it is intended, I wonder if you could at least add a config option to rather extend the burn time. This would be very helpful for my pack. Thanks in advance.

**Comment by Buuz135** [comment]
Its not unbalanced, a stick produces a little power and a block of coal a big burst of power.

**Comment by davqvist** [comment]
So, it's intended that way? It's for sure inbalanced as you can generate multiple thousands of RF from a generator, I can't think of another single block gen in modded that can generate that much power in a short amount of time. Betatesters of mine agree, Anyway, if it's intended that way, fair enough, just wanted to check as I wasn't sure. 

Any chance there will a config option to change that?

**Comment by Buuz135** [comment]
It is intended but I will add a config too

**Comment by davqvist** [comment]
Thanks very much.

**Comment by davqvist** [comment]
So I updated to 1.1.1-27 which is supposed to add it, but I can't find the config.
I looked at the code and it is supposed to be timeModifier, but searching for that in the config file didn't result in a find, also deleting the config and regenning didn't work.

**Comment by Buuz135** [comment]
It's in the first line, hard to miss...

**Comment by Buuz135** [comment]
```
petrified_fuel_generator {
        # Time modifier for the burning time. (FuelBurningTime/%value%) [range: 1 ~ 2147483647, default: 20]
        I:timeModifier=20

        # Machine can perform a work action [default: false]
        B:workDisabled=false
    }
```

**Comment by davqvist** [comment]
Does not show up for me, weird.

**Comment by Buuz135** [comment]
Are  you sure you are using the  correct version, a clean instance generates it.

**Comment by davqvist** [comment]
What? It did now, sorry for bothering you, I might have messed up somehow.

**Comment by Buuz135** [comment]
Don't worry about it.
