### ISSUE TITLE
[1.12.2] [1.8.0-118] Range Addons do not effect Plant Interactor's vertical range

### ISSUE THREAD

**Issue by Sandriell** [Buuz135/Industrial-Foregoing#252]
Industrial Foregoing Version: 1.8.0-118
TeslaCoreLib Version: 1.0.12

Range addons do not have any effect on the vertical range of the Plant Interactor, which makes it pretty useless for harvesting some things within Pam's Harvestcraft- a mod specifically states to be supported.

I was trying to set it up to harvest both coconuts and cinnamon trees and with any increase in the vertical range it would take me 5 separate machines to properly harvest them all. Currently all it does is harvest the bottom block from the cinnamon tree trunk.

**Comment by Lethann** [comment]
It would be nice if there was a vertical range addon to deal with the trees. Most of them I just place on the same level as the fruit but the really annoying trees like Cinnamon and Paper. being able to use the horizontal range with a vertical set would make this a life saver for the orchards.
