### ISSUE TITLE
MeetFeeder Ticking crash

### ISSUE THREAD

**Issue by dash16** [Buuz135/Industrial-Foregoing#253]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.3-122.jar
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): https://pastebin.com/GMJBLXNL

I'm pretty sure I nailed down this crash to the MeetFeeder.  As soon as I placed it in my player inventory, my client crashed.  Whenever I try to re-open the world, it crashes again.

**Comment by boosterdev** [comment]
yep once I get hunger I also crash, client only server stays online

**Comment by dash16** [comment]
I edited my player inventory to remove the feeder, and the crashes stopped.
