### ISSUE TITLE
Tree gatherer randomly stops

### ISSUE THREAD

**Issue by Bobbert1921** [Buuz135/Industrial-Foregoing#255]
Industrial Foregoing Version: 1.8.3-122
My tree gatherer will just randomly stop chopping trees even tho it has plenty of power and the inventory is not full. if i pull the range addon out of it for a minute and put it back in it will run for a while then stop again.

**Comment by asukaceres** [comment]
Same issue here, plant gatherer ignores trees (and plants) within its working range after gathering trees for some time. Pull and put range addon fixes issue for a minute then it comes back.

![2018-03-04_12 38 33](https://user-images.githubusercontent.com/7995545/36942261-183a8c5a-1fa9-11e8-840f-2855bf231bf3.png)

Screenshot shows onions are fully grown, as well as a bunch of grown Jungles trees ignored by plant gatherer. Working area is shown too. Plant Fertilizer with bone meal is also utilized.

Tested with vanilla Dark Oak trees and Jungle trees, with range 3 addon. 

DW20 1.12.2 pack (version 1.9.0)
Industrial Foregoing Version: 1.8.2-121

**Comment by Buuz135** [comment]
@Bobbert1921 are you sure that you are in version 1.8.3?
@asukaceres update to 1.8.3
