### ISSUE TITLE
Suggestion: OreBerries compatibility + Harvester (which gives Essence)

### ISSUE THREAD

**Issue by TNTUP** [Buuz135/Industrial-Foregoing#256]
Industrial Foregoing Version: 1.7.1
TeslaCoreLib Version: 1.0.12
Crashlog (If Any): N/A

Title. Tried to attempt this https://youtu.be/jDXiU3g-4As?t=2m52s (Only this is missing, the rest is available to craft in 1.12.2^^

**Comment by Buuz135** [comment]
Have you tried the Plant Interactor?

**Comment by TNTUP** [comment]
No, I will try that! Been googling for solutions for XP berry farming^^ WIll test that one!

**Comment by TNTUP** [comment]
Yes it works now! Wasn't aware the interactor could do it (I had typed the wrong keyword!) Closing^^
