### ISSUE TITLE
Swimming in Sludge/Sewage blocks turns screen white

### ISSUE THREAD

**Issue by Level-5-Pidgey** [Buuz135/Industrial-Foregoing#257]
Industrial Foregoing Version: 1.12-1.8.3-122
TeslaCoreLib Version: 1.12-1.0.13

Sorry if the version numbers above are incorrect. I am unsure whether this is a mod issue, or something created by another mod in my install, but whenever I fully submerge my player in Sewage/Sludge blocks the screen turns white (until I bob above the water again).

Apologies if this isn't because of your mod in advance.

**Comment by boosterdev** [comment]
well i just tried this, i burn to death, only screen i get is "You Died"
