### ISSUE TITLE
[Suggestion] Add a Shear function to the Plant Gatherer. 

### ISSUE THREAD

**Issue by Cr1t1calReaper** [Buuz135/Industrial-Foregoing#263]
Hello there, 

I'm currently playing Enigmatica 2 Expert, and I was a little sad when I learned there was no easy option for getting leaves automatically. So I thought I'd suggest it, since it's the only thing I've thought that this lovely mod needs. 

Cheers, 
Cr1t1cal

**Comment by Buuz135** [comment]
There is a leaf shearing addon
