### ISSUE TITLE
[1.12.2] Incopatible with Applied Energistics Storage Bus.

### ISSUE THREAD

**Issue by Project579** [Buuz135/Industrial-Foregoing#266]
Industrial Foregoing Version: 1.8.5-127
TeslaCoreLib Version: 1.0.13
Crashlog (If Any): No crash
Applied Energistics 2 Version: rv5 stable 10

The Black Hole Controller and Black Hole Unit when connected to an Applied Energistics ME Storage Bus cause an In Real Life Network bug that makes the ME system send Huge amounts of packets to clients that access it, this bug was already reported here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2363

**Comment by Buuz135** [comment]
Are you inserting or removing items constantly ?

**Comment by Project579** [comment]
Yes i'm inserting items from a quarry that is probably whats causing the problem i'm not even sure if it can be fixed, I may just have to set up a lot of drives and still limit Items to not more then around 100K each.

**Comment by Buuz135** [comment]
It cant be fixed because if you want "live feed" of the changes it needs to send a packet
