### ISSUE TITLE
More storage for a blackhole Unit

### ISSUE THREAD

**Issue by nolimet** [Buuz135/Industrial-Foregoing#267]
Using a long instead of a interger for the storage of items in a Black Hole Unit and a Black Hole Tank.

Looked up the NBT tag for minecraft there seems to be support for a long wich is a 64bit integer 
allowing for a maximum value of 9,223,372,036,854,775,807 instead of 2,147,483,647. 
If it was intentional then just ignore this suggestion.

[https://minecraft.gamepedia.com/NBT_format](https://minecraft.gamepedia.com/NBT_format)

**Comment by Buuz135** [comment]
Why do you need more space, its big enough
