### ISSUE TITLE
Death.Attack.Mob_Crusher

### ISSUE THREAD

**Issue by ifficles** [Buuz135/Industrial-Foregoing#268]
Industrial Foregoing Version: 1.8.5
TeslaCoreLib Version: 1.0.13
Crashlog (If Any): None

  More of "Pointing this out".  I used to get messages stating "zombie, skeleton, creeper, and so on, was killed by [IF],"  Now, the only message that I get is death.attack.mob_crusher.  Lower left corner

Thanks for looking

![2018-03-18_16 33 43](https://user-images.githubusercontent.com/961490/37605237-c3702d42-2b60-11e8-9901-9f1509c7b68c.png)

**Comment by Buuz135** [comment]
Hopefully fixed in https://github.com/Buuz135/Industrial-Foregoing/commit/f0a70b1110aa7a1955910995dd6cc15451cfebaf
