### ISSUE TITLE
[suggestion] Make essence forge xp compatible?

### ISSUE THREAD

**Issue by Kazzamkablam** [Buuz135/Industrial-Foregoing#27]
Would be nice if XP from other mods could be used for the enchanting/disenchanting stuff.

**Comment by Buuz135** [comment]
There is no such thing a Forge XP Compatible, each fluid is different.

**Comment by Kazzamkablam** [comment]
My derp there, meant interchangeable with xp fluid from mob grinding utils or ender io (once it ports).

**Comment by ShaunDreclin** [comment]
Seconded, one way to solve this would be to allow the sewer block (Animal byproduct recollector) to suck up exp orbs and convert them to essence, that's how it used to work in MFR

**Comment by Buuz135** [comment]
As a secret feature, the Mob Relocator picks up xp orbs in its working area

**Comment by ShaunDreclin** [comment]
Ooooh nice! That works fine for me :D
