### ISSUE TITLE
Server Crashing with java.awt.Color not found

### ISSUE THREAD

**Issue by MiningPickaxe** [Buuz135/Industrial-Foregoing#272]
Industrial Foregoing Version: 1.12.2-1.8.5-127
TeslaCoreLib Version: 1.12-1.0.13
Crashlog (If Any): https://pastebin.com/CKU0Ptsm

When I start up my Server under Linux, Java 8u161, it crashes and gives the provided crashlog. What is the issue here?

**Comment by Buuz135** [comment]
You might be missing some forge libraries, please reinstall forge
