### ISSUE TITLE
Crash from ticking block entity

### ISSUE THREAD

**Issue by IchigoGames** [Buuz135/Industrial-Foregoing#275]
Industrial Foregoing Version :industrialforegoing-1.12.2-1.8.6-131
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.13
Crashlog (If Any): https://pastebin.com/nZpiP021

I cant say why this is happening or how to reproduce it but from what i can see on the crash report it looks like a ticking block entity from industrialforegoing is crashing my server started after update to the version listed above.

**Comment by Katzen48** [comment]
We are experiencing this error too.
