### ISSUE TITLE
Rubber and Plastic ore dictionary usage

### ISSUE THREAD

**Issue by Robijnvogel** [Buuz135/Industrial-Foregoing#276]
Industrial Foregoing Version: 1.12.2-1.7.0-114

Re-opening of #31 's first sub-issue:
"This mod's recipes don't accept other mods' rubber/plastic (like IndustrialCraft's rubber)."

Observation:
It seems like you DO add the Plastic Sheets material to the itemRubber ore dictionary entry, however, you are not using this entry as an input for your own crafting recipes.

Consideration:
Also: Why are the Plastic Sheets equivalent to Rubber? Wouldn't it make more sense for the Dry Rubber Balls to be equivalent to those? That way, you could craft the IF Plastic Sheets from other mods' Rubber as well.

Proposal:
1. Add the Dry Rubber to the itemRubber ore dictionary entry instead of the Plastic Sheets.
2. Use the itemRubber ore dictionary entry as the input for your rubber-to-plastic smelting recipe.

**Comment by boosterdev** [comment]
[oredict-fix.zs.txt](https://github.com/Buuz135/Industrial-Foregoing/files/1870878/oredict-fix.zs.txt)

**Comment by Robijnvogel** [comment]
@boosterdev thank you for the effort, but this is a change proposal, not a request for help. :)

+ I'm quite proficient at ZenScript myself and I really wonder if it's a good idea to remove items from an ore dictionary entry.

**Comment by boosterdev** [comment]
well yes, plastic is not rubber, and like you said, his recipes are not oredict based.

**Comment by Robijnvogel** [comment]
^Edited

**Comment by Buuz135** [comment]
So many pack have worked around this that it might break a lot of stuff, maybe for 1.13
