### ISSUE TITLE
Plant Interactor won't Work

### ISSUE THREAD

**Issue by Pringels09** [Buuz135/Industrial-Foregoing#280]
Industrial Foregoing Version: 1.8.6
TeslaCoreLib Version: 1.0.12
Crashlog (If Any): 
I tried makeing a farm with the plant interactor on a Direwolf20 1.12.2 server. But this stupid thing wont work : 
![2018-04-03_00 27 54](https://user-images.githubusercontent.com/23477312/38219568-7cd0dcac-36d6-11e8-8dc0-67b580440247.png)
And in an exact replica of it on a singleplayer world works.

**Comment by Buuz135** [comment]
First of all, its very rude to call stupid someelse work. Secondly, it is an issue with FTBUtils, make sure you have the right setting in the Fake Player Setting to allow or whatever it is.
