### ISSUE TITLE
Block breaker dupes shulker box and contents 

### ISSUE THREAD

**Issue by superfluke** [Buuz135/Industrial-Foregoing#288]
Placing a shulker box containing items in front of a block breaker causes the the contents of the box to drop as items in world and places an empty shulker box in the block breaker inventory, additionally a shulker box drops in world as if harvested with a pick and containing all items. 

Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.7-132
TeslaCoreLib Version: Tesla-1.12.2-1.0.63

**Comment by Saklad5** [comment]
I find it bizarre that the Shulker Box is the source of so many issues, even though near-omnipresent mods like Thermal Expansion have had the same mechanic for ages.
