### ISSUE TITLE
Can the Plant Fertilizer accept Chicken Manure from the mod Hatchery?

### ISSUE THREAD

**Issue by Alarinth** [Buuz135/Industrial-Foregoing#291]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.7-132.jar
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.13
Crashlog (If Any): N/A

Any chance the item Chicken Manure (hatchery:chickenmanure) could be accepted in the Plant Fertilizer? It's my main source of fertilizing in my current mod pack.

**Comment by Buuz135** [comment]
Add it to the "fertilizer" oredictionary entry as you have been told before.
