### ISSUE TITLE
Enchantment Applicator not accepting some enchantable items as inputs

### ISSUE THREAD

**Issue by superfluke** [Buuz135/Industrial-Foregoing#296]
The Enchantment Applicator does not accept some items as inputs that are enchantable on an anvil, such as
- Forestry pickaxe and scoop
- Vanilla Shield 

Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.9-138
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): n/a

Edit: after more testing it seems these items do not actually work in the vanilla enchanting table either, but enchantments can be applied through an anvil. Updated the issue to reflect that

**Comment by TheCodedOne** [comment]
Forestry tools & the vanilla shield don't specify they're enchantable, this is not something IF should work around, if they're meant to be enchantable report to their respective owners
