### ISSUE TITLE
Plant Sower sometimes does not plant seeds.

### ISSUE THREAD

**Issue by NerdCraft** [Buuz135/Industrial-Foregoing#3]
1.11.2
0.1.0-BETA
forge: 13.20.0.2304
tesla: 1.11-1.3.0.51
tesla core lib: 1.11.2-0.7.0

**Comment by Buuz135** [comment]
Are we talking about wheat seeds?

**Comment by NerdCraft** [comment]
Yes

**Comment by Buuz135** [comment]
Anything in the filter or any mods that mess around with planting seeds?

**Comment by NerdCraft** [comment]
Nothing in the filter. Mod list:
![sem titulo](https://cloud.githubusercontent.com/assets/13489837/26367745/fc2e069a-3fc5-11e7-8969-bda3cf083031.png)

**Comment by Buuz135** [comment]
Can I get some pics of the setup?

**Comment by NerdCraft** [comment]
test with potatoes
![2017-05-23_14 47 26](https://cloud.githubusercontent.com/assets/13489837/26368068/e68c9378-3fc6-11e7-814d-6c0494da8f26.png)

**Comment by Buuz135** [comment]
On the corners are not planted right?

**Comment by NerdCraft** [comment]
see this video 
https://youtu.be/cGgFilgeSYM

**Comment by Buuz135** [comment]
OHHH, that's intended, the machine keep checking 1 block in an order each time does work.

**Comment by NerdCraft** [comment]
ok, thanks :V

**Comment by Buuz135** [comment]
I have plans to add in the near an operation upgrade that increases how many operations does each time it works.
