### ISSUE TITLE
The Plant Gatherer does not pick up apples.

### ISSUE THREAD

**Issue by ProsperCraft** [Buuz135/Industrial-Foregoing#301]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.9-138.jar 
TeslaCoreLib Version:  tesla-core-lib-1.12-1.0.13.jar

When harvesting oak trees, the gatherer does not pick up the apples.

**Comment by Buuz135** [comment]
Like on the ground?

**Comment by ProsperCraft** [comment]
Right, it just leaves them all over the ground, and doesn't pick any up.

**Comment by ProsperCraft** [comment]
What if every 60 seconds or so the machine checks the ground for harvest products?
