### ISSUE TITLE
Getting Started - Power Generation

### ISSUE THREAD

**Issue by Vva70** [Buuz135/Industrial-Foregoing#303]
Industrial Foregoing Version: 1.8.9-138
TeslaCoreLib Version: 1.0.13
Crashlog (If Any): N/A

Is it intended that the mod, though it has its own power generation, cannot be started without power generation from another mod? All of the generators require plastic to craft. But to produce plastic requires power to be provided to the Latex Processing Unit.

**Comment by Buuz135** [comment]
Intended
