### ISSUE TITLE
Plant interactor doesn't collect Canola, Canola seeds

### ISSUE THREAD

**Issue by neoc666** [Buuz135/Industrial-Foregoing#305]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.5-127
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.13

Is it intended that it doesn't always pick up anything that drops from an interaction? Works for potatoes, doesn't work for Canola.

**Comment by Buuz135** [comment]
I cant do much about that, AA drops the items in the ground instead of adding them to the player inventory of or firing a Harvest event which I do get for the potatoes. (As Pam's does fire the event)
