### ISSUE TITLE
Some compatibilities issues

### ISSUE THREAD

**Issue by zlainsama** [Buuz135/Industrial-Foregoing#31]
1. This mod's recipes don't accept other mods' rubber/plastic (like IndustrialCraft's rubber).
2. This mod's mob spawner(Mob Duplicator) don't properly check the available space, making the mob can spawn inside blocks and suffocating.
3. I had a crash when biofuel generator output its energy to an powercell from rftools. ([CrashReport](https://pastebin.com/RjGT3wVm), this probably wasn't your mods' fault, i'm just letting you know)

Edit:
4. RefinedStorage won't put items in an empty BlackHoleUnit, even if it's an locked one. (I mean, through ExternalStorage)
Edit2:
5. Some mobs can be spawn&killed indefinitely through duplicator and relocator(like Wither Skeleton and Endermen), the essence they generated by killing them are far more than they needed to spawn.

**Comment by Buuz135** [comment]
Just letting you know that I saw this and I'm fixing them, even though the commits aren't pushed 😛

**Comment by zlainsama** [comment]
@Buuz135 
I found a new bug.
Enchantment related.
The Invoker can trigger on items that are not enchantable causing Essence and Power be used for nothing.
The Aplicator can force enchantments on items that are not enchantable. (like putting Efficiency on IC2 drills)

**Comment by Buuz135** [comment]
The invoker doesn't allow items that can't be inserted.
And I will leave the Aplicator like that :P
