### ISSUE TITLE
Removing Ores from Laser Drill with CraftTweaker Removes All Ores Except Ore Listed in Removal

### ISSUE THREAD

**Issue by superfluke** [Buuz135/Industrial-Foregoing#311]
Trying to remove an ore with craft tweaker will actualy set that ore as the only valid output for the laser drill.
`mods.industrialforegoing.LaserDrill.remove(<minecraft:gold_ore>);`
![image](https://user-images.githubusercontent.com/20022336/39279440-1e035418-48c7-11e8-83a3-f39363be140a.png)

Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.10-141
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): n/a

**Comment by TheCodedOne** [comment]
does it actually only output the removed item or is it only JEI thats showing it like that?

**Comment by superfluke** [comment]
It seems like it does only output that ore. I had a user complain they had got 4 stacks of an ore I had removed before they got even a single coal. I tested it and got 6 gold ore with the screen shot above before I made the report.
