### ISSUE TITLE
Mob Crusher causing performance issues

### ISSUE THREAD

**Issue by Sir-Will** [Buuz135/Industrial-Foregoing#312]
The Mob Crusher is causing performance issues and lag spikes, any chance this can be improved?

![](https://i.imgur.com/Pnv3i8H.jpg)
industrialforegoing-1.12.2-1.8.5-127
tesla-core-lib-1.12-1.0.13

**Comment by TheCodedOne** [comment]
Incase you are blind you might have noticed that the lag you are pointing out is not caused by IF but is infact caused by either vanilla minecraft or sponge.
