### ISSUE TITLE
protein generator is voiding biofuel

### ISSUE THREAD

**Issue by vinyl90** [Buuz135/Industrial-Foregoing#316]
Industrial Foregoing Version: 1.8.8-136
TeslaCoreLib Version: 1.0.13.8
Crashlog (If Any): 
(note) I'm playing on Ender IO server.
Also it is only voiding x amount but I don't know the set amount and the generator before this one works.

**Comment by Buuz135** [comment]
It's not voiding fluid, the Protein Reactor only accepts Protein. The book has a typo.

**Comment by vinyl90** [comment]
Ok thx
