### ISSUE TITLE
Support AgriCraft Crops

### ISSUE THREAD

**Issue by brennie** [Buuz135/Industrial-Foregoing#317]
Presently, the Plant Gatherer cannot harvest AgriCraft crops. I tried the Plant Interactor, but that ended up with all the plants all over the ground. There was room in the inventory, so it wasn't a full inventory issue.

Industrial Foregoing Version: 1.8.11
TeslaCoreLib Version: 1.12.2-1.0.14

**Comment by Vislor** [comment]
Just an FYI, I submitted a PR to AgriCraft 2 days ago to add support for the Plant Gatherer.  It is under review at this time.

**Comment by Buuz135** [comment]
Oh! Neat!

**Comment by Buuz135** [comment]
Handled in industrial foregoing
