### ISSUE TITLE
Incompatibility with Binnies Latex.

### ISSUE THREAD

**Issue by kraft2004** [Buuz135/Industrial-Foregoing#32]
Hi, this is a small problem we're having on any pack that has Binnies Mods installed. When one uses Industrial Foregoing's Tree Fluid Extractor with Binnies installed, it makes Binnies Mods Latex. That would not be a problem, wasn't it for the fact that the Latex Processing Unit doesn't accept Binnies Latex.
I hope you can take a look on that :)

**Comment by Buuz135** [comment]
Can I get more info about it, like modlist, setup, mod versions? Because it's 100% imposible, they have different registry names, Binnies uses `binnie.latex` and mine `latex`. I couldn't even replicate the issue.

Any ideas @mezz ?

**Comment by kraft2004** [comment]
Sorry for not providing this info before. We are using Radon 1.1.5. It has not been updated in a while, but right now I can't even make a modpack with Binnies load (1.12.1 and 1.12 Twitch Profiles that include only Binnies and Industrial Foregoing). It just suicides and gives a error about Binnies Trees.
On Radon, the mod versions are 2.2.0.7 for Binnies and 1.1-25 for Industrial Foregoing. TeslaCoreLib is 1.0.7. At least Radon boots up.
For the modlist, https://minecraft.curseforge.com/projects/radon/relations/dependencies

**Comment by kraft2004** [comment]
The issues seem to only be appearing on Radon. They have been fixed on the newer version. Time to make Elucent update the pack. Sorry for wasting your time.

_Now I look like a idiot._
