### ISSUE TITLE
BHU throughput limitations - possible lag producer

### ISSUE THREAD

**Issue by xBlizzDevious** [Buuz135/Industrial-Foregoing#325]
Industrial Foregoing Version: 1.8.10-143
TeslaCoreLib Version: 1.0.13
Crashlog (If Any): N/A

So I've switched from Quantum Storage Units (~150 of them) on storage buses with my ME system to a mostly-drives/cells-but-a-few-BHUs-as-well setup. This is mostly to reduce lag as nothing can handle the previous setup without serious lag.

It appears that BHUs don't have the (seemingly) unlimited throughput that quantum storage units and deep storage units had before them as a storage cell in an ME port is not emptying as quickly into a BHU as it does with a QSU.

Also, I had an issue that when sorting my items into new drives, the BHUs on storage buses weren't receiving any items, even though they had a higher priority than the drives/cells; this wasn't an issue at all with the QSUs. It appears that an item interface with item lasers (Actually Additions) has a similar problem on feeding items in. This seems to cause some lag on my server as well - I haven't had any "server can't keep up" warnings for days but since I've started feeding items into the BHUs, I've been getting very regular ~"310 ticks behind" notices.

If you want any more details, please ask here or on the ATM3 Discord as I see you there a lot too.

**Comment by xBlizzDevious** [comment]
Just noticed another issue - also AE2 related. The contents of the BHU are showing in my ME system even though the storage bus is set to "insert only" and "report only accessible items".

**Comment by TheCodedOne** [comment]
Can you run a profiling test with visualvm?

**Comment by xBlizzDevious** [comment]
I'm not familiar with VisualVM but I'll see if I can figure it out.

I assume it needs to be run on the server, not the client, yes? Or do you want both?

**Comment by TheCodedOne** [comment]
server yes

**Comment by xBlizzDevious** [comment]
OK, I think I've got it running correctly but I'm not sure. I've run the profiling on CPU but I don't know what I'm looking for and can't see a way to export the info it gathered.

What exactly do you need?

**Comment by Buuz135** [comment]
I have no issues here https://i.imgur.com/x3epo4d.gifv
Or here https://i.imgur.com/xEAvZOd.gifv

**Comment by xBlizzDevious** [comment]
Yeah, I'm starting to think it wasn't specifically an issue with the Black Hole Units - more that it was just not being handled well by my server.

I have since moved things about more and moved the Black Hole Units into two Black Hole Controllers - a quick test showed the issue was no longer there.
