### ISSUE TITLE
Disabling and re-enabling with EnderIO conduits, visual glitch

### ISSUE THREAD

**Issue by rbandboy** [Buuz135/Industrial-Foregoing#329]
Industrial Foregoing Version: 1.9.0-163
TeslaCoreLib Version: 1.0.14
Crashlog (If Any): none

![2018-05-13_21 45 05](https://user-images.githubusercontent.com/4001839/39977480-71fb3408-56f7-11e8-8cd6-f4d93c5c41bf.png)

This occurred when I paused the Spores Recreator via the in-machine play/pause button, then re-enabled.  Should this be on EnderIO's github instead?

**Comment by EpicSquid** [comment]
Please put one on the enderio issue board as well

**Comment by TheCodedOne** [comment]
This does look more like an issue with enderio due to the fluid still rendering. Please report there, if it turns out it is an issue with IF just reply to this issue
