### ISSUE TITLE
Crash when putting water bottle into wrong Potion Brewer slot

### ISSUE THREAD

**Issue by Noah-Wagner** [Buuz135/Industrial-Foregoing#336]
Industrial Foregoing Version: 1.9.1-166
TeslaCoreLib Version: 1.0.14
Crashlog (If Any): 

```
java.lang.NullPointerException: Ticking block entity
	at net.ndrei.teslacorelib.utils.FluidUtils.fillFluidFrom(FluidUtils.kt:60)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:16)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:22)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.processInputInventory(fluidextensions.kt:27)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processFluidItems(SidedTileEntity.kt:541)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processImmediateInventories(SidedTileEntity.kt:211)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.processImmediateInventories(ElectricMachine.kt:298)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:989)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
```

When a water bottle is put into the top slot of the water resource portion of the Potion Brewer UI, the game crashes.

**Comment by Buuz135** [comment]
I cant even put the water bottle in the slot

**Comment by Buuz135** [comment]
What slot exactly?

**Comment by Noah-Wagner** [comment]
If I put a water bottle into this slot, regardless of power situation or inventory, my game crashes and I cannot reload that world.

![](https://i.imgur.com/l5ytPhO.png)

**Comment by Buuz135** [comment]
I can't put a water bottle in that slot without extra mods, some other mod must be adding a capability to the water bottle and doing it wrong.

**Comment by Mario90900** [comment]
Actually no, he is correct. The bit of information that he was missing though, and what took me a bit to replicate this myself, is that you first need the machine to go from "Filling with Water" step to "Adding Ingredient". Once it is in the Adding Ingredient step, you are allowed to place the water bottle in that indicated slot above, and it does crash the game instantly - likely because a water bottle is not a tank.

I ended up having this same bug on a server I put together, and I was able to replicate it with only Industrial Forgoing, Integration Forgoing, Ender IO (for easy power and water transfer), and the core mods needed to run this on a separate instance. Once you do this though, the block will crash the server/world as soon as it is loaded again, probably as the bottle is still sitting in the slot. It looks like the separate steps change things for what can go in which slots. Hopefully this helps you narrow it down!

**Comment by Shybella** [comment]
```I can't put a water bottle in that slot without extra mods, some other mod must be adding a capability to the water bottle and doing it wrong.```

Is there a possibility of adding a failsafe here?

**Comment by KinnaT** [comment]
This occurred in FTB Revelation (details [here](https://ftb.gamepedia.com/FTB_Revelation) with full list of mods). Client and self-hosted multiplayer server both crashed.

**Comment by 84danie** [comment]
Also experienced this in FTB Revelation- same exact error/crash report as original report and same cause.

**Comment by FliegendeWurst** [comment]
Still an issue in FTB Sky Odyssey

**Comment by bizleycraft** [comment]
Just happened to me in Sky Factory 4.

**Comment by FliegendeWurst** [comment]
@Buuz135:

Another mod may be "doing it wrong", but that's no excuse to crash the game. Any mod should handle errors gracefully.

**Comment by Yousei9** [comment]
Still happening.
Closing a crash report with a reason like "another mod enabled you doing something wrong" is unacceptable.
Handle your errors properly or at least give us a way to fix servers caught in restart loops by this.

**Comment by Andrubes** [comment]
@Yousei9 I haven't done a lot of coding in minecraft. How do you open the console to type that line without loading the world?

**Comment by koen1993** [comment]
@Andrubes "writing nvm got it" is bad taste, at least write what/how you got it.   
go to \minecraft\config\endercore\endercore.cfg 
set the two lines to false:  
>   B:bottleFluidHandler=false
>   B:fluidContainerBottles=false   

reload the world and break the potion brewer. Props for solution to https://ftb.gamepedia.com/Potion_Brewer  
reset the config to default, and you can play normaly...
