### ISSUE TITLE
[1.12.1] Sower & Plant Recollector HUGE delay with full energy

### ISSUE THREAD

**Issue by CreeperShift** [Buuz135/Industrial-Foregoing#34]
Hi,
I'm using Industrial Foregoing 1.1.1-33 on a Forge dedicated server (no sponge) with Forge version 2462.
In a chunk with no other machinery, my Sower and Plant Recollector have HUGE delays and sometimes don't plant/harvest at all for a good 5-10 minutes despite being at full energy:

Here you can see the area with crops:
http://i.imgur.com/ulLqPfO.png

Plant Sower has full energy and crops:
http://i.imgur.com/O2jZfol.png

Plant Recollector has free slots:
http://i.imgur.com/1mSHVVx.png

All of them have the same range upgrade.

As you can see my crop field still has fully grown crops and empty spaces. Even after the 5 minutes of taking screens and writing this it's currently still like this with only few harvested (1-2 out of 20-30 that are grown) and still empty spots.

I'm not sure if this is by design or a bug, let me know if I can get you more information.

**Comment by Buuz135** [comment]
The way it works, as it did in MFR, every time a works it checks for a block, the next time it checks for the next... So it needs to go around all the area to work until it comes back. There are speed upgrades for the machines though, but I will try to speed it up in the non working cycles.

**Comment by CreeperShift** [comment]
Ah I did not know there were speed upgrades. I'll give those a try and report back.
