### ISSUE TITLE
[Question/Issue?] Got Plant Gatherer nerfed?

### ISSUE THREAD

**Issue by accessdenied0** [Buuz135/Industrial-Foregoing#342]
Industrial Foregoing Version: 1.12.2-1.9.2-170
TeslaCoreLib Version: 1.0.14
Crashlog (If Any): -

I recently noticed that the Plant Gatherer harvested the plant I put on my farmland instead of "right clicking" it. 

Got the Plant Gatherer nerfed in the way, that he needs a planter now? I seemed to have missed it in the changelogs, if so.

**Comment by Buuz135** [comment]
The Plant Gatherer always needed a Planter. You need to use a Plant Interactor

**Comment by accessdenied0** [comment]
FailFish... my bad. Sorry for the inconvenience
