### ISSUE TITLE
Tree fluid extractor crashes server

### ISSUE THREAD

**Issue by SirDumb** [Buuz135/Industrial-Foregoing#343]
Industrial Foregoing Version: 1.12.2-1.9.0-163
TeslaCoreLib Version: 1.12.2-1.0.14
Crashlog (If Any): 
[crash-2018-05-26_00.02.12-server.txt](https://github.com/Buuz135/Industrial-Foregoing/files/2042951/crash-2018-05-26_00.02.12-server.txt)
[crash-2018-05-27_21.25.55-server.txt](https://github.com/Buuz135/Industrial-Foregoing/files/2042952/crash-2018-05-27_21.25.55-server.txt)

Randomly crashed the server and would crash on start until i removed the block with mcedit. Happend twice so 2 crashlogs.
Edit: Playing on FTB Continuum

**Comment by Buuz135** [comment]
Update the mods/pack
