### ISSUE TITLE
Plant Interactor wont collect items anymore

### ISSUE THREAD

**Issue by blackoutroulette** [Buuz135/Industrial-Foregoing#351]
I updated my FTB Revelation to version 2.0.0 and my plant interactor wont pick up vanilla wheat or seeds after cutting it down.

**Comment by Buuz135** [comment]
Thats not an issue on my side, the machine just right clicks the plants and gets the drops if an event is fired or its added into the fake player inventory. With the addition of mods must have changed how it works.
