### ISSUE TITLE
BHU server crash. 

### ISSUE THREAD

**Issue by Chachava** [Buuz135/Industrial-Foregoing#353]
Industrial Foregoing Version: 1.12.2-1.9.0-163
TeslaCoreLib Version: 1.12.2-1.0.14
Crashlog (If Any): https://pastebin.com/ia8jE59a

We're playing on a Foolcraft 3 server, up until recently we've been playing on version 1.0.0 with very few issues, recently we've tried updating to both 1.2.0 and 1.3.0, each time the server has crashed in any area with a BHU, this appears to happen even when placing down a fresh BHU. It appears that the mod doesn't get updated between pack versions which leads me to believe it's a pack issue rather than a mod issue, but the pack devs suggested posting an issue here as well.

**Comment by Buuz135** [comment]
Update the mod, not my fault if the pack dev doesnt update the mod, its not that hard.
