### ISSUE TITLE
Plant Interactor not storing items.

### ISSUE THREAD

**Issue by Furious1964** [Buuz135/Industrial-Foregoing#355]
Industrial Foregoing Version: 1.10.0.173
TeslaCoreLib Version: 1.0.14.10
Crashlog (If Any): 

It just drops the items on the floor and stores nothing.

**Comment by Buuz135** [comment]
Does it work with a hopper?

**Comment by Furious1964** [comment]
I can use vacuum chests and absorption hoppers to get the items, but shouldn't this be working right? I don't know what's gone wrong.

**Comment by Buuz135** [comment]
How are you piping the items in?

**Comment by Furious1964** [comment]
You don't pipe item into it but out of it. The device acts as a right clicker to auto-harvest crops and it should collect and store them to be piped out later.

**Comment by Buuz135** [comment]
Same response as https://github.com/Buuz135/Industrial-Foregoing/issues/351
