### ISSUE TITLE
Plant Sower and Plant Gatherer not working

### ISSUE THREAD

**Issue by buddhaj** [Buuz135/Industrial-Foregoing#356]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.9.0-163
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.14
Crashlog (If Any): 

These have absolutely broken for me. They will no longer plant or harvest vanilla crops or pam's harvestcraft crops. I broke them and replaced them. I swapped out how their redstone signal works. The planter will go and make the farmland but not plant anything.

**Comment by buddhaj** [comment]
![2018-06-10_11 28 56](https://user-images.githubusercontent.com/11291253/41205057-afababb0-6ca1-11e8-9f15-9c0cfcfd75d6.png)
![2018-06-10_11 29 11](https://user-images.githubusercontent.com/11291253/41205058-afc5eb9c-6ca1-11e8-91ea-d7599bbb6afc.png)
![2018-06-10_11 29 17](https://user-images.githubusercontent.com/11291253/41205059-afde8b52-6ca1-11e8-8175-53fe2737d824.png)
![2018-06-10_11 29 27](https://user-images.githubusercontent.com/11291253/41205060-aff515fc-6ca1-11e8-8b62-a01065a0393e.png)
![2018-06-10_11 29 52](https://user-images.githubusercontent.com/11291253/41205061-b00ef6a2-6ca1-11e8-8de5-24e3ac8a9653.png)
![2018-06-10_11 29 58](https://user-images.githubusercontent.com/11291253/41205062-b026b864-6ca1-11e8-8c13-1930725cee9f.png)

**Comment by buddhaj** [comment]
Its the weirdest thing
![2018-06-10_11 33 59](https://user-images.githubusercontent.com/11291253/41205102-31723e20-6ca2-11e8-9510-09decf18a59e.png)
![2018-06-10_11 33 45](https://user-images.githubusercontent.com/11291253/41205103-31879158-6ca2-11e8-88a0-450ed8f74991.png)

**Comment by Buuz135** [comment]
Is your area protected by ftb utils?

**Comment by buddhaj** [comment]
Yes it is

**Comment by buddhaj** [comment]
Took the areas out of the team area and it kicked back in gear

**Comment by Buuz135** [comment]
So it works?

**Comment by buddhaj** [comment]
Yeah its working now.

**Comment by Buuz135** [comment]
You need to update FTBUtils, its was an issue on their side
