### ISSUE TITLE
Planter and other machines not working with GP.

### ISSUE THREAD

**Issue by Shybella** [Buuz135/Industrial-Foregoing#357]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.4-124
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.13
Crashlog (If Any): 

Similar to #356 but with Griefprevention. I used gpdebug to capture the source to trust and does not work. The source comes up as "fakeplayer:[if]".

Thanks

**Comment by Buuz135** [comment]
Try `fakeplayer:[IF]`. If it doesn't work I wont be able to add support

**Comment by Shybella** [comment]
Nope, does not work.

**Comment by Buuz135** [comment]
Sorry I cant add support for GP
