### ISSUE TITLE
No range mods

### ISSUE THREAD

**Issue by Kilmatar** [Buuz135/Industrial-Foregoing#36]
As I wrote in comments at CurseForge - there are no range mods available ingame.
Also in sourcecode I can see their receipts. I was try to create mods using this info for no luck. Looks like all this mods is missing.

Client startup log is too big for PasteBin, so here is DropBox link: https://www.dropbox.com/s/gqymt8m0hbcaxcs/fml-client-latest.log?dl=0

**Comment by Buuz135** [comment]
Can I get the modpack?

**Comment by Kilmatar** [comment]
Forge 14.21.1.2443

Dropbox link to archived MOD/Config folders: https://www.dropbox.com/s/wva705np6eniph2/IFNoRangeMods.zip?dl=0

Dropbox link to Curse/Twitch exported profile: https://www.dropbox.com/s/p2d6hh8gnkcqkz6/Kilmatar%27s%201.12%20Test-1.1.zip?dl=0

**Comment by Buuz135** [comment]
Range addons are there:
![](https://i.imgur.com/WBFihEo.png)
They are just hidden from NEI, with JEI alone works perfectly. They have recipes too.

**Comment by Buuz135** [comment]
But still is an issue on my end that I just fixed for the next version that I hope I can release today
