### ISSUE TITLE
Enchantment Extractor not giving Eff X Book back

### ISSUE THREAD

**Issue by DJ411** [Buuz135/Industrial-Foregoing#362]
Industrial Foregoing Version:     1.10.0-173
TeslaCoreLib Version:    1.0.14

I was given a pickaxe from a lucky block with Eff X and Fortune 3. I got 2 books, 1 was blank and one was Fortune 3. Is this a bug or would a mob pack disable this?

**Comment by Buuz135** [comment]
I dont think Enchanted books are allowed to have that high enchanted level
