### ISSUE TITLE
Laser drill and Laser Base

### ISSUE THREAD

**Issue by Jordan-Slade** [Buuz135/Industrial-Foregoing#367]
Industrial Foregoing Version: 
TeslaCoreLib Version: 
Crashlog (If Any): 
The names on the laser drill and laser bases should really be switched if one doesn't do research into the items they are likely to end up making 4 laser bases and 1 laser drill. This means that they will have one item to supply power and 4 to produce ore. So those names really need to be switched.
Second is a suggestion more than an issue but I think the laser shooting down to the ground feature and the requirement of hitting bedrock in order for the laser to run should be re-added in just as it was in the 1.7.10. It also made a lot more sense when the lasers would damage players in 1.7.10.

**Comment by Buuz135** [comment]
First: Nah, you can clearly see in the block texture what is what. 
Second: This is not a straight port of MFR stuff has changed.
