### ISSUE TITLE
[FEATURE] Add support for meat feeder to extract fluid from OpenBlocks tanks

### ISSUE THREAD

**Issue by ProfessorCool** [Buuz135/Industrial-Foregoing#368]
The meat feeder seems to work all right with other modded fluid tanks, but the meat feeder can currently only deposit fluid in an OpenBlocks tank, with no way of extracting it. It'd be really nice if you could add the same functionality to the OpenBlocks tank that the other fluid tanks already possess, allowing the meat feeder to fill up from the tank.

**Comment by Buuz135** [comment]
Shouldnt that be on OpenBlocks side if it works good with every other tank?
