### ISSUE TITLE
Blinking Conveyor doesn't teleport player in survival mode

### ISSUE THREAD

**Issue by Snownee** [Buuz135/Industrial-Foregoing#369]
Industrial Foregoing Version: 1.10.1
TeslaCoreLib Version: 1.0.14

**Comment by Buuz135** [comment]
Not an issue https://streamable.com/i3xt9

**Comment by Buuz135** [comment]
I will keep it as it is for safety reasons

**Comment by Snownee** [comment]
At least could you please don't let player get stuck there?

**Comment by Buuz135** [comment]
The change the Y teleport
