### ISSUE TITLE
Some recipes will not work

### ISSUE THREAD

**Issue by BlameXeno** [Buuz135/Industrial-Foregoing#372]
Industrial Foregoing Version: 1.7.10-114
TeslaCoreLib Version: 1.0.12
Crashlog (If Any): None

I own a modpack named Foregoing Revamped (which is ironic since I did not name it after IF). Recently some players have reported not being able to craft various IF machinery like the Latex Processing Unit. Help?

**Comment by Buuz135** [comment]
You are using a half a year old version,  have you considered updating?
