### ISSUE TITLE
Interaction issue with Carry On

### ISSUE THREAD

**Issue by 2ndkirbyever** [Buuz135/Industrial-Foregoing#374]
I used Carry On to move a material stonework factory last night. After I did and hooked it up to power, I noticed that all of my power was gone. I soon figured out why: the material stonework factory was taking max int FE/tick. It seems that if you use Carry On to transport a material stonework factory, it causes the factory to take max int FE/tick until you break and replace it.
This is the power usage before using Carry On:
![This is the power usage before using Carry On](https://user-images.githubusercontent.com/16438720/42126068-0d1e6954-7c47-11e8-9cd7-95da84618482.png)
And this is the power usage after using Carry On:
![And this is the power usage after using Carry On](https://user-images.githubusercontent.com/16438720/42126070-1eebe670-7c47-11e8-988f-a0a9ff15548f.png)

Industrial Foregoing Version: 1.10.2-178
TeslaCoreLib Version: 1.12.2-1.0.63

**Comment by Buuz135** [comment]
I don't support carry on, you can blacklist industrial foregoing in their configs
