### ISSUE TITLE
Ore Dictionary Converter GUI not coping

### ISSUE THREAD

**Issue by Wiseacre-Software** [Buuz135/Industrial-Foregoing#375]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.10.1-176.jar
TeslaCoreLib Version: Tesla Core Lib : 1.0.14.10
Crashlog (If Any): None

Playing Modern Skybock 3: Departed modpack. GUI below shows irrespective of GUI Scale setting.

![image](https://user-images.githubusercontent.com/10398416/42129760-dfa38308-7d11-11e8-8723-0b8c5132f481.png)

**Comment by Buuz135** [comment]
Update to latest
