### ISSUE TITLE
[Suggestion/question] Resourcefull furnace

### ISSUE THREAD

**Issue by stabstalker** [Buuz135/Industrial-Foregoing#377]
Industrial Foregoing Version: 1.8.11
 With the resourcefull furnace is it possible that it will autosort between the 3 input slots so it will use them evenly if there are only 30 items in instead of just the first top slot.

**Comment by Buuz135** [comment]
You can use the Item Splitter for that

**Comment by stabstalker** [comment]
in JEI it says the item splitter is for the output of a machine and i was talking about the input slot inside the machine... (when ur looking inside the actual machine)

**Comment by stabstalker** [comment]
![furnace](https://user-images.githubusercontent.com/40744372/42139303-9f5d8c4c-7d8b-11e8-8689-59ce799112dd.png)
so it will split the lead evenly in those 3 slots

**Comment by Buuz135** [comment]
No, the Item Splitter will push items into inventories leaving only the specified item item amount on that inventory.

**Comment by stabstalker** [comment]
aah ok i get it thanks for ur time
