### ISSUE TITLE
Can't Insert Items into the Ore Dictionary Converter

### ISSUE THREAD

**Issue by superfluke** [Buuz135/Industrial-Foregoing#378]
Tried inserting the following items by just picking up and clicking, shift clicking, and using a hopper. Cannot get items into the machine.

![image](https://user-images.githubusercontent.com/20022336/42191137-3bb09a5a-7e2f-11e8-9a17-c6629322c683.png)

Industrial Foregoing Version: industrialforegoing-1.12.2-1.10.2-178
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.14

**Comment by Buuz135** [comment]
You need to put an item in the blue slot first.

**Comment by Buuz135** [comment]
What did you try? It only works with some times that have an specified oredictionary entry

**Comment by superfluke** [comment]
I tried all the items in the screen shot. Sapling, slimeball, log, fake dye

**Comment by Buuz135** [comment]
It only works with  {"ore", "ingot", "nugget", "gem", "dust", "block", "gear", "plate"};

**Comment by superfluke** [comment]
Ahh, I see. I think it would be helpful to mention that it only works on those types of items in the manual.

**Comment by tristan-hull** [comment]
Is it possible that this will ever work for logWood? There are often times where many different kinds of wood are acquired, which is a storage nightmare and there isn't a great way to convert between them.
