### ISSUE TITLE
Possible conflict with RoughMobs

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [Buuz135/Industrial-Foregoing#381]
Industrial Foregoing Version: 1.12.2-1.10.1-176
TeslaCoreLib Version: 1.12.2-1.0.14
Crashlog (If Any):  https://pastebin.com/NSqpasnh

Hello!

I've been playing a custom minecraft pack that has RoughMobs and Industrial Foregoing. For some reason, after using a drop of evil and trying to use the Mob Crusher from I got a server crash. I'll probably also report this back for the developers of RoughMobs.

It also seems to have something to do with Endermans :)

Thanks for the GREATE work!

**Comment by Buuz135** [comment]
That looks like RoughMobs trying to teleport the fake player that I use to kill the mobs. The issue is on their side.
