### ISSUE TITLE
Feature req: Harvester and Sludge Boiler

### ISSUE THREAD

**Issue by tyggna** [Buuz135/Industrial-Foregoing#383]
Industrial Foregoing Version:  1.12.2-1.10.2-178
TeslaCoreLib Version:  1.12.2-1.0.14

Feature request

Add in the harvester and sludge boiler machines from MineFactory Reloaded.  Upgrades would be nice, but just having the machines work would be great (plus agricraft compatibility)

**Comment by TheCodedOne** [comment]
Both of these machines exist in IF already under different names, Plant Gatherer and Sludge Refiner

**Comment by tyggna** [comment]
Awesome, you're amazing, thank you!
