### ISSUE TITLE
Harvester, No operation or gui

### ISSUE THREAD

**Issue by twincitygamer** [Buuz135/Industrial-Foregoing#384]
Industrial Foregoing Version: 1.12
TeslaCoreLib Version: 1.0.13
Crashlog (If Any): 
Currently running a custom mod pack and just added this mod. Seems that the harvester is a bit broken. If i place it down and right click on in nothing happens. acts like a normal vanilla minecraft block.

**Comment by Buuz135** [comment]
Thats not an industrial foregoing version

**Comment by DKnightADRI** [comment]
![untitled](https://user-images.githubusercontent.com/12832161/42419092-71370406-82ae-11e8-937c-ba6dfb80524a.png)

**Comment by DKnightADRI** [comment]
![untitled](https://user-images.githubusercontent.com/12832161/42419124-d5ad4bd4-82ae-11e8-9c5e-87ff8279cde9.png)

**Comment by twincitygamer** [comment]
industrial foregoing version: 1.3.1-61

update: it not just the plant gatherer its a majority of the machine from the mod pack. not sure what is happening here. Im guessing there is a conflicting mod or something.

**Comment by Buuz135** [comment]
You are using a very old version, update the mod

**Comment by twincitygamer** [comment]
when i try to run a updated version i get an fml notifiation saying its not supported in this minecraft version

**Comment by Buuz135** [comment]
Update forge? That version is from last year
