### ISSUE TITLE
[Bug] Plant gatherer not felling full tree

### ISSUE THREAD

**Issue by Brailagise** [Buuz135/Industrial-Foregoing#385]
Industrial Foregoing Version: 1.9.0-163
TeslaCoreLib Version:  1.0.14
Crashlog (If Any): N/A

Plant gatherer seems to be sporadically only harvesting trees to there "stump". This happens intermittently and it will go back and get them on other rounds but this causes less saplings to be down at a time leading to reduced wood production. Screenshot URL below / screenshot attached

https://imgur.com/a/ThcjDXO
![2018-07-09_10 05 10](https://user-images.githubusercontent.com/41010248/42455751-16b5d044-8361-11e8-998b-4cf95ff6a456.png)

**Comment by Buuz135** [comment]
Try updating the mod.
