### ISSUE TITLE
startup crash 1.12-1.2.1-48

### ISSUE THREAD

**Issue by stclaus4** [Buuz135/Industrial-Foregoing#39]
this is a start up crash the the last version didn't give me any issues -48 vs. -43
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Industrial Foregoing (industrialforegoing)

https://pastebin.com/Yq7e1WBR   <-- for the full

**Comment by Buuz135** [comment]
Use the latest Tesla core lib
