### ISSUE TITLE
Mob Duplicator crashing client crash when playing on server

### ISSUE THREAD

**Issue by NattyPew** [Buuz135/Industrial-Foregoing#390]
Industrial Foregoing Version: 1.12.2-1.9.0-163 (direwolf20 version)
TeslaCoreLib Version: 1.12.2-1.0.14 (direwolf20 version)
Crashlog (If Any): 
[crash-2018-07-12_22.25.44-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/2190237/crash-2018-07-12_22.25.44-client.txt)

**Comment by Buuz135** [comment]
Thats shows RFTools in the report
