### ISSUE TITLE
Tree fluid extractor requires wooden log to be placed vertically

### ISSUE THREAD

**Issue by Zajozor** [Buuz135/Industrial-Foregoing#394]
Industrial Foregoing Version: 1.10.3
TeslaCoreLib Version: 1.12.2-1.0.14
Crashlog (If Any): -

When a wooden log is placed in front of a tree fluid extractor, to extract latex the log needs to be placed vertically (as in most trees), when placed in any other direction, the tree fluid extractor does not work.
Not sure if it is a feature or a bug, yet most block placers from other mods happen to place blocks in different directions (actually additions placer, refined storage constructor, ..) without a configuration option. For them to place to log in the correct direction, an unintuitive placement is required.

I would like to request either a change to the functionality, or a change to the in-game manual for the machine, to include clear statement about this requirement for the log rotation. It is pretty hard to find out the cause of the problem, took me a while.

Thanks.

**Comment by Buuz135** [comment]
Update the mod
