### ISSUE TITLE
Plant Sower not planting every time/seeds (Mystical Agriculture ones)

### ISSUE THREAD

**Issue by Zeldri** [Buuz135/Industrial-Foregoing#395]
Industrial Foregoing Version: 1.12.2-1.10.1-176
TeslaCoreLib Version: 1.12.2-1.0.14 (1.0.14)
Pack : DNS Techpack
Crashlog (If Any): Nope

I'm happy to see "Minefactory reloaded" back :D Thx for the work. But I'm having an issue (I think ?) with the plant sower. (And btw I think there are a problem with Xnet mods, because I had trouble to get energy into machines, but I don't know which mods is actually buggy)
Like in this screenshot you can see that the sower has seeds, and the field isn't full

https://imgur.com/a/JPmeZQb

To actually get the plant sower plant it, I need to move/take the seeds in the plant sower and it will get back to work but it's kind of annoying

(Sry for the english :/ Not my native language)

**Comment by Buuz135** [comment]
Each colored slot is a defined area where to plant stuff. To change that lock all the slots with a seed filter.

**Comment by Zeldri** [comment]
OH OK ! Sorry :/, this feature was in Minefactory ??

**Comment by Buuz135** [comment]
Yes
