### ISSUE TITLE
Plant gatherer gone wild

### ISSUE THREAD

**Issue by sevy7389** [Buuz135/Industrial-Foregoing#396]
Industrial Foregoing Version: 1.10.4
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): no crash

I really like your mod and use it all the time in the modpack that I do for myself. But in the last pack I got a little problem when I use the plant gatherer with no range addon it collect log in a very very large area. I was wordering if it is a bug or a conflict. Here is a image to explain better.

https://imgur.com/a/MeND9tS

**Comment by Buuz135** [comment]
Its not really a bug, its just that all the trees are connected and seen as one.

**Comment by Buuz135** [comment]
The distance can be changed in the config

**Comment by sevy7389** [comment]
Thanks
________________________________
De : Buuz135 <notifications@github.com>
Envoyé : 21 juillet 2018 16:42
À : Buuz135/Industrial-Foregoing
Cc : sevy7389; Author
Objet : Re: [Buuz135/Industrial-Foregoing] Plant gatherer gone wild (#396)


The distance can be changed in the config
