### ISSUE TITLE
enchanted books from the dissenchanter have incorrect nbt.

### ISSUE THREAD

**Issue by Dryxen** [Buuz135/Industrial-Foregoing#4]
Books have nbt value ench: instead of StoredEnchantments: rendering them completly unusable in vanilla anvils and modded recipies requireing specific enchanted books.

**Comment by Mohron** [comment]
Why was this issue closed @Buuz135? I can verify the enchantments generated but the disenchanter are unusable...

**Comment by Buuz135** [comment]
Because I thought I fixed it, are old books or new ones?

**Comment by Mohron** [comment]
Ah, okay it just looked like it was closed with no response and we were worried. Thanks for fixing it, new books work perfect! 👍

**Comment by Buuz135** [comment]
Yeah, looking in the commit https://github.com/Buuz135/Industrial-Foregoing/commit/7d653d137e45207bd7282aff4f897e60fa23f38e shows why

**Comment by Mohron** [comment]
We just missed that, thanks for the fast response.

**Comment by Buuz135** [comment]
No problem, but you did scare me a little

**Comment by Mohron** [comment]
Blame @Dryxen he scared me! I hate when it's nearly impossible to get bugs fixed in an otherwise fantastic mod.
