### ISSUE TITLE
[Suggestion] Add some way to use fertilizers from other mods in the Plant Fertilizer

### ISSUE THREAD

**Issue by mindofsiren** [Buuz135/Industrial-Foregoing#400]
Industrial Foregoing Version: 1.12.2-1.10.7-204
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): None

Attempting to use Mystical Fertilizer from Mystical Agriculture in the Plant Fertilizer but it isn't compatible. Not sure if there is a specific reason for the incompatibility but it would be a nice thing to have.

**Comment by Buuz135** [comment]
You can add fertilizers by adding the item to the `fertilizer` OreDictionary entry
