### ISSUE TITLE
Regarding Plant Gatherer, Plant Sower and Plant Fertilizer..

### ISSUE THREAD

**Issue by ckjr** [Buuz135/Industrial-Foregoing#401]
Industrial Foregoing Version: 1.12.2-1.10.7-204
TeslaCoreLib Version: 1.12.2-1.0.15.13
Crashlog (If Any): None

I was playing Foolcraft 3 recently, and I noticed that these 3 machines are consuming RF at the max rate even though they are idle. That happened also when their both their inventories and working areas are empty. Is this intended?

**Comment by Buuz135** [comment]
Intended
