### ISSUE TITLE
Moving BH Controller with Mekanism Cardboard box deletes all black holes

### ISSUE THREAD

**Issue by FeedTheChunk** [Buuz135/Industrial-Foregoing#402]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.10.0-173
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.14
Crashlog (If Any): None

Moved a Black Hole Controller using a Cardboard Box from Mekanism.  After placing, the entire inventory  of the controller was removed, eight black holes and all of the items.

**Comment by Buuz135** [comment]
IF Tiles don't like to be moved, don't moved them
