### ISSUE TITLE
Max Baby Separator Range?

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [Buuz135/Industrial-Foregoing#407]
Industrial Foregoing Version:  1.10.6
TeslaCoreLib Version: 1.12.2-1.0.5
Crashlog (If Any): None

Hello, sorry for creating an issue just for this, but I was playing and I noticed that even when I put a emerald addon on the Animal Baby Separator, it only extends as much as 6 range. I managed to test it with a Tier8 and a Tier11 (NQuartz and Emerald). In both cases it doesn't go over tier6 and I wanted to know if is something that might be related to a config in the server.

Is this a normal behaviour?
Thanks in advance.

![image](https://user-images.githubusercontent.com/293596/43988302-e999914c-9d08-11e8-98d9-f057909c8213.png)

**Comment by Buuz135** [comment]
If you look at the tooltip of the machine it says the max range of it
