### ISSUE TITLE
[Bug?] Machines can get achivements

### ISSUE THREAD

**Issue by FnordMan** [Buuz135/Industrial-Foregoing#41]
Something rather minor, not sure if this is intentional or not. The screenshot pretty much says it all, loaded up my (single player) world to that bit of amusement. 

![2017-09-09_16 02 56](https://user-images.githubusercontent.com/7041560/30243886-6679df12-9578-11e7-86bb-09aec7e43074.png)

**Comment by josephcsible** [comment]
This is a Forge bug, not an Industrial Foregoing bug. MinecraftForge/MinecraftForge#4255
