### ISSUE TITLE
Ticking block entity  with white inverted  lense and Laser Drill

### ISSUE THREAD

**Issue by lays24mc** [Buuz135/Industrial-Foregoing#417]
When I used the white lense in the laser drill, the game crasehd. Can you help?

Industrial Foregoing Version: 1.12.2-1.7.3
TeslaCoreLib Version: 1.12.2- 1.0.15
Crashlog (If Any): https://pastebin.com/dxrdpTsb

**Comment by Buuz135** [comment]
Try, updating the mod
