### ISSUE TITLE
Planter planting wierdly.

### ISSUE THREAD

**Issue by JanRK** [Buuz135/Industrial-Foregoing#419]
Industrial Foregoing Version: 1.12.2-1.11.1-206
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): N/A

https://imgur.com/a/wmgjK2W

The planter is planting Apple Oak Sapling 1 square outside it's working area. Tried to replacing the planter, but same issue. Also tried a new planter another place, and same issue. Energy usage seems like it is often planting, even when it's not doing anything. 

Same planter works normally with oak saplings.

**Comment by Buuz135** [comment]
I cant do much about it as Forestry saplings need a wierd special planting for it
