### ISSUE TITLE
Mod doesn't recognize Osmium or Yellorium when added to config

### ISSUE THREAD

**Issue by FnordMan** [Buuz135/Industrial-Foregoing#42]
Subject line says it all, I added a couple lines to the ores section of the laser base and the changes aren't taking by the looks of things, it isn't showing up in JEI as an option. 

ores section of the config follows, the two I added are on the bottom. 
        S:ores <
            4 oreGold 0 6
            12 oreIron 0 10
            15 oreCoal 0 12
            11 oreLapis 0 8
            3 oreDiamond 0 4
            14 oreRedstone 0 6
            0 oreQuartz 0 4
            5 oreEmerald 0 2
            13 oreUranium 0 3
            4 oreSulfur 0 8
            10 oreGalena 0 6
            0 oreIridium 0 2
            14 oreRuby 0 7
            11 oreSapphire 0 7
            12 oreBauxite 0 5
            12 orePyrite 0 5
            14 oreCinnabar 0 8
            12 oreSphalerite 0 4
            15 oreTungsten 0 3
            0 oreSheldonite 0 1
            3 orePlatinum 0 2
            13 orePeridot 0 7
            11 oreSoladite 0 4
            14 oreTetrahedrite 0 4
            8 oreTin 0 8
            10 oreLead 0 5
            7 oreSilver 0 5
            1 oreCopper 0 10
            0 oreYellorite 0 3
            0 oreOsmium 0 8
         >

**Comment by Buuz135** [comment]
Version?

**Comment by FnordMan** [comment]
Derp, running 1.12.1, version 1.2.1-48  (the latest on curseforge)t

**Comment by Buuz135** [comment]
If you look [here](https://github.com/Buuz135/Industrial-Foregoing/blob/master/CHANGELOG.md) and in the curse changelog it says that the config support for it was removed in favor of Crafttweaker

**Comment by FnordMan** [comment]
FYI: I wouldn't have had to ask this if you had a wiki or any kind of documentation. I couldn't find ANY info about how to do this and the changelog never came up in any of the searches.

**Comment by Buuz135** [comment]
I just made it: https://github.com/Buuz135/Industrial-Foregoing/wiki/Crafttweaker-Support
