### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by UltiMaxCZ** [Buuz135/Industrial-Foregoing#428]
Industrial Foregoing Version: 1.9.2-170
TeslaCoreLib Version: 1.0.14

Without Industrial Foregoing server works fine, with it doesn't start. In singleplayer I.F. works.

Server crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 9/14/18 10:41 PM
Description: Exception in server tick loop

java.lang.SecurityException: read permission error: ../src/main/resources/assets/industrialforegoing/recipes
	at com.hicoria.javaSandBox.Main$CustomSecurityManager.checkRead(Main.java:255)
	at java.io.File.exists(File.java:814)
	at com.buuz135.industrial.utils.RecipeUtils.addShapelessRecipe(RecipeUtils.java:112)
	at com.buuz135.industrial.proxy.ItemRegistry.registerItems(ItemRegistry.java:47)
	at com.buuz135.industrial.proxy.BlockRegistry.registerItems(BlockRegistry.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_434_BlockRegistry_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:743)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.0-3-amd64
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3316740760 bytes (3163 MB) / 3986292736 bytes (3801 MB) up to 3986292736 bytes (3801 MB)
	JVM Flags: 6 total; -Xms3840M -Xmx3840M -Xmn384M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:MaxGCPauseMillis=50
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2707 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                  | Source                                          | Signature                                |
	|:----- |:------------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                      | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                      | 8.0.99.99                | server.jar                                      | None                                     |
	| UCH   | forge                    | 14.23.4.2707             | server.jar                                      | None                                     |
	| UCH   | micdoodlecore            |                          | minecraft.jar                                   | None                                     |
	| UCH   | securitycraft            | v1.8.7                   | [1.12.x]+SecurityCraft+v1.8.7.jar               | None                                     |
	| UCH   | codechickenlib           | 3.1.9.344                | CodeChickenLib-1.12.2-3.1.9.344-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | ancientwarfare           | 1.12.2-2.6.1.285         | ancientwarfare-1.12.2-2.6.1.285.jar             | None                                     |
	| UCH   | buildcraftlib            | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftcore           | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | redstoneflux             | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | ancientwarfareautomation | 1.12.2-2.6.1.285         | ancientwarfare-1.12.2-2.6.1.285.jar             | None                                     |
	| UCH   | ancientwarfarenpc        | 1.12.2-2.6.1.285         | ancientwarfare-1.12.2-2.6.1.285.jar             | None                                     |
	| UCH   | ancientwarfarestructure  | 1.12.2-2.6.1.285         | ancientwarfare-1.12.2-2.6.1.285.jar             | None                                     |
	| UCH   | ancientwarfarevehicle    | 1.12.2-2.6.1.285         | ancientwarfare-1.12.2-2.6.1.285.jar             | None                                     |
	| UCH   | battletowers             | 1.6.1                    | BattleTowers-1.12.jar                           | None                                     |
	| UCH   | biomesoplenty            | 7.0.1.2302               | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar   | None                                     |
	| UCH   | buildcraftbuilders       | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftenergy         | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftfactory        | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftrobotics       | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcrafttransport      | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftsilicon        | 7.99.17                  | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | cdm                      | 0.4.1                    | cdm-0.4.1-mc1.12.2.jar                          | None                                     |
	| UCH   | cfm                      | 5.9.1                    | cfm-5.9.1-mc1.12.2.jar                          | None                                     |
	| UCH   | chameleon                | 1.12-4.1.3               | Chameleon [4.1.3].jar                           | None                                     |
	| UCH   | chickenchunks            | 2.4.1.71                 | ChickenChunks [2.4.1.71].jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | chisel                   | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | cofhcore                 | 4.5.2                    | CoFHCore-1.12.2-4.5.2.19-universal.jar          | None                                     |
	| UCH   | cofhworld                | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | computercraft            | 1.80pr1                  | ComputerCraft-Mod-1.12.1.jar                    | None                                     |
	| UCH   | asielib                  | 1.0.0                    | Computronics-1.12.1-1.6.5.jar                   | None                                     |
	| UCH   | ic2                      | 2.8.16-ex112             | Industrial-Craft-2-Mod-Experimental-1.12.1.jar  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | jei                      | 4.8.5.147                | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UCH   | mekanism                 | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                  | None                                     |
	| UCH   | computronics             | 1.6.5                    | Computronics-1.12.1-1.6.5.jar                   | None                                     |
	| UCH   | customnpcs               | 1.12                     | CustomNPCs_1.12.2(09jul18).jar                  | None                                     |
	| UCH   | elevatorid               | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                    | None                                     |
	| UCH   | enderstorage             | 2.4.0.122                | Ender-Storage-Mod-1.12.jar                      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | energyconverters         | @VERSION@                | energyconverters_1.12.1-1.0.1.2.jar             | None                                     |
	| UCH   | exoticbirds              | 1.0                      | Exotic+Birds+1.12.2-1.4.1.jar                   | None                                     |
	| UCH   | zerocore                 | 1.12-0.1.1.0             | Zerocore [0.1.1.0].jar                          | None                                     |
	| UCH   | bigreactors              | 1.12.2-0.4.5.46          | ExtremeReactors [0.4.5.46].jar                  | None                                     |
	| UCH   | forgelin                 | 1.6.0                    | Forgelin-1.6.0.jar                              | None                                     |
	| UCH   | galacticraftcore         | 4.0.1.181                | GalacticraftCore-1.12.2-4.0.1.181.jar           | None                                     |
	| UCH   | galacticraftplanets      | 4.0.1.181                | Galacticraft-Planets-1.12.2-4.0.1.181.jar       | None                                     |
	| UCH   | llibrary                 | 1.7.15                   | llibrary-1.7.15-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCH   | iceandfire               | 1.5.2                    | iaf-1.5.2.jar                                   | None                                     |
	| UCH   | tesla                    | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | teslacorelib             | 1.0.14                   | tesla-core-lib-1.12.2-1.0.14.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | industrialforegoing      | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.9.2-170.jar        | None                                     |
	| UCH   | inventorytweaks          | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest                | 1.12.2-7.0.40.824        | Ironchest [7.0.40.824].jar                      | None                                     |
	| UCH   | journeymap               | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | mekanismgenerators       | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar        | None                                     |
	| UCH   | minecolonies             | 1.12.2-0.9.1-RELEASE     | minecolonies-1.12.2-0.9.1-RELEASE-universal.jar | None                                     |
	| UCH   | modernlamps              | 1.0.3                    | ModernLights-1.0.3_1.12.jar                     | None                                     |
	| UCH   | morpheus                 | 1.12-3.3.2               | morpheus.jar                                    | None                                     |
	| UCH   | primitivemobs            | 1.1.6                    | primitivemobs-1.1.6_beta.jar                    | None                                     |
	| UCH   | redstonepaste            | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                  | None                                     |
	| UCH   | roguelike                | 1.7.2                    | Roguelike-Dungeons-Mod-1.12.2.jar               | None                                     |
	| UCH   | storagedrawers           | 1.12-5.2.5               | StorageDrawers [5.3.5].jar                      | None                                     |
	| UCH   | thermalfoundation        | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermalexpansion         | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | toroquest                | 1.12.2-5.2               | toroquest-1.12.2-5.2.jar                        | None                                     |
	| UCH   | bspkrscore               | at_0.9                   | TreeCapitator-Mod-1.12.jar                      | None                                     |
	| UCH   | treecapitator            | at_0.9                   | TreeCapitator-Mod-1.12.jar                      | None                                     |
	| UCH   | twilightforest           | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar     | None                                     |
	| UCH   | wearablebackpacks        | 3.1.2                    | WearableBackpacks-1.12.2-3.1.2.jar              | None                                     |
	| UCH   | teslacorelib_registries  | 1.0.14                   | tesla-core-lib-1.12.2-1.0.14.jar                | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Buuz135** [comment]
Thats an issue with your dedicated server
