### ISSUE TITLE
Tree Fluid Extractor doesn't maintain progress

### ISSUE THREAD

**Issue by Intipablo** [Buuz135/Industrial-Foregoing#432]
Industrial Foregoing Version: 1.12.2-1.11.2-212
TeslaCoreLib Version: 1.12.2-1.0.15

Not sure if this is intentional or not but when I leave my world and then rejoin, the tree fluid extractor loses it's progress in consuming the log it's facing, however it still has the latex from consuming it so if you keep logging in and out you essentially have infinite latex (not that anyone would do that but..).

**Comment by Buuz135** [comment]
It's intentional as you might mess up and have a breaking progress for ever.
