### ISSUE TITLE
Feature Request:  Prevent removal of filled bottles until all ingredients are brewed.

### ISSUE THREAD

**Issue by Noogies123** [Buuz135/Industrial-Foregoing#438]
Industrial Foregoing Version: 
TeslaCoreLib Version: 
Crashlog (If Any): 

I am attempting to automate the creation of potions using the Potion Brewer along with Applied Energistics 2.   

My issue is that the bottles are removed as soon as they are filled with water.    And, If I blacklist the removal of bottles of water, then it removes them when they become Awkward Potion, and the Golden carrot can't be added to make Night Vision potion.   I can blacklist removal of Awkward potion, but If i need to make Invisibility potion, the bottles of potion get removed as soon as the night Vision potion is done,   If I blacklist the Night Vision potion so that I can make Invisibility potion, then I am prevented from making plain Night Vision Potion because it never can be removed.   I hope you can see my problem here.

I propose that the Potion Brewer outputs a redstone signal as long as it is brewing.   That way, when the redstone signal disappears when it's done brewing, the ME Export Bus (or Item Servo) can be activated.

Alternately, you can add an(or 3) additional "Output Slot" to stack the completed potion bottles into as they're finished brewing, and make that the one that other mods can remove bottles from.   (as I'm writing this, it seems like this might be the best one.)

**Comment by Buuz135** [comment]
Cant you just whitelist the potions you want?

**Comment by Noogies123** [comment]
If I whitelist Night Vision, then it will be removed before I can brew Invisibility.    Alternately, if i don't whitelist Night vision so that I can brew Invisibility, then when I WANT night vision, it will remain in the output slots. 

A better option would be to either not allow removal until all items are consumed, or issue a redstone signal while brewing is in progress so that removal can be prevented as the redstone signal turns off the Servo, or the ME Import Bus. (or whatever you're using to remove items from the brewer)

In it's current state, items can be removed before brewing is complete, which prevents automation.
