### ISSUE TITLE
Crash on trying to shift right click a fifth water bottle into the Potion Brewer

### ISSUE THREAD

**Issue by LordRayuga** [Buuz135/Industrial-Foregoing#439]
Industrial Foregoing Version: 1.12.2-1.11.2-212
TeslaCoreLib Version: 1.0.15.13
Crashlog (If Any): https://pastebin.com/UENvf1Jz

If i try to shift right click a fifth water bottle into the Potion Brewer the game crashes, and also it crashes every time i try to load up the save.

**Comment by Buuz135** [comment]
Duplicate #413
