### ISSUE TITLE
Machine Performance

### ISSUE THREAD

**Issue by Yamza** [Buuz135/Industrial-Foregoing#440]
Hoping you might be able to look into what's causing the machines to be taking as much resources as they do, even while idle.

Tree Fluid Extractors: https://i.imgur.com/BuNlIbl.png
Bioreactor (2x): https://i.imgur.com/lHnAzqj.png
Tree Fluid Extractor & Latex Processor: https://i.imgur.com/ncEPArt.png
Mob Crusher: https://i.imgur.com/MzDxp7W.png
 Lava Fabricator: https://i.imgur.com/7GHFGYw.png

Industrial Foregoing Version: IntegrationForegoing-1.12.2-1.7.4
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Modpack: ATM3 - Remix 0.1.2

**Comment by Yamza** [comment]
Laggoggles Report: https://i.imgur.com/ifTVAss.png
Bad Video showing contents: (Just showing that the apple to carrot have about 4k items, the cake about 500, the others only 1) https://www.dropbox.com/s/v8n8i7clrnbaa3h/2018-10-14_09-00-24.mp4?dl=0
Spark Profile: https://sparkprofiler.github.io/?IgPAnG1EFt
Sampler Profile attached.
[IF1.zip](https://github.com/Buuz135/Industrial-Foregoing/files/2478741/IF1.zip)

**Comment by Yamza** [comment]
A report from the ATM3 server is attached.
[ATM3-ROfficial1.zip](https://github.com/Buuz135/Industrial-Foregoing/files/2478743/ATM3-ROfficial1.zip)

**Comment by Buuz135** [comment]
Those nps report don't show something excesive that I could really improve. In the worst case it uses a 0.09% or 100ms/106sec of the reports.

**Comment by Buuz135** [comment]
See commits for more info
