### ISSUE TITLE
Potion Brewer Crashes and breaks world

### ISSUE THREAD

**Issue by dbridle** [Buuz135/Industrial-Foregoing#445]
Industrial Foregoing Version: 1.12.2-1.7.4
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): https://pastebin.com/kBhjV6vg

Description of the issue:
Recently upgraded to 1.0.22r1.

Seting up automation for the Potion Brewer to create potions of swiftness. I had Awkward potions automatically being pumped in. As soon as one of the potions hit the brewer, the pack crashed, since then the world has been unable to be opened.

Steps to Recreate:

Add a potion brewer
Use some fluiduct's and a signalum servo, pulling water from a sink, into the potion brewer
Add a stack of nether wart and glass bottles
Awkward potions are made, extract using itemducts and a signalum servo into a chest
Extract from chest using itemducts and a signalum servo back into the brewer
Open the brewer... crash.

It should be noted that I had not configured hte sides correctly, so the potions went into the wrong slot!

**Comment by Buuz135** [comment]
Duplicate #413

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
