### ISSUE TITLE
Black hole tanks storage bus'd to a AE2 system increase data usage by x10 on servers

### ISSUE THREAD

**Issue by idcppl** [Buuz135/Industrial-Foregoing#448]
Industrial Foregoing Version: 1.11.5-125
TeslaCoreLib Version: 1.0.15
Crashlog (If Any): N/A

Black hole tanks that are storage bus'd to an Applied Energistics system raise data usage up to almost x10. I do not know who side this issue is caused on, so I am posting it to both githubs.

**Outside Link**
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3797

**Comment by Buuz135** [comment]
Nothing I can do
