### ISSUE TITLE
Black Hole Dupe (Bees)

### ISSUE THREAD

**Issue by Sunekaer** [Buuz135/Industrial-Foregoing#449]
Industrial Foregoing Version: 1.11.5-215
TeslaCoreLib Version: 1.0.15
Crashlog (If Any): 

**Bug Report**
Black Hole Controller + Black Hole Unit Duplicate/Change Bees Typs

**Steps to Reproduce (for bugs)**
Build Black Hole Controller +Black Hole Unit and Insert 1 or more different Bees
Place other Bees in your Inventory
Insert Bees from Inventory to Black Hole Controller and all other Bees change to the First Insert Bee in the Black Unit.
(Bees from Forestry)
Export from Refined Storage use the First Bee Slot and Change all other Bees...

https://github.com/Sunekaer/stoneBlock/issues/448

**Comment by kaiand1** [comment]
Info
Same Problem with Enchanted Books...
