### ISSUE TITLE
Parsing error loading recipe

### ISSUE THREAD

**Issue by Maxwelljones** [Buuz135/Industrial-Foregoing#456]
Industrial Foregoing Version: 1.12.2-1.11.5-215
TeslaCoreLib Version: 1.0.15
Crashlog (If Any): [latest.log](https://github.com/Buuz135/Industrial-Foregoing/files/2608316/latest.log)

There is no crash, but this is de-activating the recipes.
The items are then not craftable anymore.

**Comment by Buuz135** [comment]
Enable the machine case in tesla core lib config

**Comment by Maxwelljones** [comment]
Thank you <3
