### ISSUE TITLE
[Mob Duplicator] Exact Copy Spawning Broken

### ISSUE THREAD

**Issue by bigbluu722** [Buuz135/Industrial-Foregoing#458]
Industrial Foregoing Version: 1.12.2-1.11.6-216
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): N/A

##Information
So I've enabled this option in the confg for Mob Duplicators, but it still doesn't seem to work. Was intending to use it on animated blocks from Erebus mod, but it still spawns the default stone version rather than the block I would like to make it, even though exact copy spawn is enabled in the config.

Config file here: 
https://pastebin.com/DcJdsUNG

**Comment by Buuz135** [comment]
An it is enabled in the mob duplicator GUI?

**Comment by bigbluu722** [comment]
https://i.imgur.com/5IYYUoW.png doesn't seem to be a button in there to enable it unless I'm vaguely missing something.

**Comment by Buuz135** [comment]
Have you enabled the config in the client?

**Comment by bigbluu722** [comment]
Seems like it's there after a 2nd client reload. Sorry for the troubles.
