### ISSUE TITLE
Plant Recollector - Mystical Agriculture compat

### ISSUE THREAD

**Issue by OrdinatorStouff** [Buuz135/Industrial-Foregoing#46]
https://github.com/AllTheMods/ATM-3/issues/125

1) Mystical Ag inferium seeds have tiers. I recall from discussion regarding the garden cloche code that special compatibility had to be added for the inferium seeds since they are not implemented exactly the same as other growables.

2) Also like the cloche, mystal ag has a config for percent change to drop extra seeds (usually configured to never drop any "extra") to prevent easy duplicating of resource crop seeds. The garden cloche also had this issue of duping seeds even when the config was set to 0% chance to drop extra.

**Comment by OrdinatorStouff** [comment]
issue/commits I found for reference in ImmEng github: https://github.com/BluSunrize/ImmersiveEngineering/issues/2271

looks like Blu 1) made any/all MA crops never drop seeds regardless of MA config settings and 2) created a special MA helper class and hardcoded handling of the MA tiered essence

**Comment by Buuz135** [comment]
https://github.com/Jacky1356400/IntegrationForegoing/commit/c496baba76a3698cfec7d44ede1a027595e82ced
