### ISSUE TITLE
No Certusquartz with laserdrill

### ISSUE THREAD

**Issue by Marlin994** [Buuz135/Industrial-Foregoing#461]
Industrial Foregoing Version: 1.11.6-216
TeslaCoreLib Version: 1.0.15
Crashlog (If Any):  - 

I can't create certusquartz with the laserdrill. It is also not in JEI like the other ores i can generate with the drill. 
Applied Energistics is on version rv6 -4

**Comment by Buuz135** [comment]
Add integration foregoing to your pack
