### ISSUE TITLE
Infinity Drill particle effect causes particles to not test alpha

### ISSUE THREAD

**Issue by gleebtorin** [Buuz135/Industrial-Foregoing#462]
Industrial Foregoing Version: 1.11.7
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): N/A

When carrying the Shiny variation of the Infinity Drill, particles behave strangely, in that they don't seem to be alpha testing as they should be. I have confirmed that this occurs in Minecraft 1.12, with only these mods;
- Forge 12.23.5.2795
- IF 1.11.17
- TeslaCoreLib (and Registries) 1.12.2-1.0.15
- Shadowfacts' Forgelin 1.8.2

I have attached images showing the issue in action.
![minecraft 1 12 2 03_12_2018 01_58_54](https://user-images.githubusercontent.com/4273763/49348746-1bb6d500-f69f-11e8-9489-5efd7f80bf0e.png)
![minecraft 1 12 2 03_12_2018 01_53_19](https://user-images.githubusercontent.com/4273763/49348747-1c4f6b80-f69f-11e8-8da2-99e292797412.png)
![minecraft 1 12 2 03_12_2018 01_54_54](https://user-images.githubusercontent.com/4273763/49348748-1c4f6b80-f69f-11e8-86ea-5757ed7fb1c2.png)

Further, I don't know if this is intended, but it dropped in my Modded SSP world from a chicken in the sea.

**Comment by TheOldOne822** [comment]
I came to report the same.
also mine dropped from a blaze
