### ISSUE TITLE
[GameBreaking]

### ISSUE THREAD

**Issue by LuisAdeur** [Buuz135/Industrial-Foregoing#464]
Industrial Foregoing Version: 1.11.8
TeslaCoreLib Version: 1.0.15.13
Crashlog (If Any): None

I saw a deer from EmberRoot Zoo with some weird particles, i killed it and it gave me the infinity drill artifact . i haven't even been in the world for 10 minutes. what is this...

**Comment by Buuz135** [comment]
Update the mod, you say you are but you arent
