### ISSUE TITLE
[SUGGESTION] include Patchouli support

### ISSUE THREAD

**Issue by Jwigou** [Buuz135/Industrial-Foregoing#465]
I think It would be awesome if you could add Patchouli support for this mod, not saying that the already existing manual isn't cutting it, but Patchouli is more advanced and provides some really nit features that would really benefit this mode, plus it's a fully dedicated mod just for the purpose of providing the best user experience out there.

**Comment by Buuz135** [comment]
Mmmhh no

**Comment by ajakka** [comment]
Well well well... look at you now :)
