### ISSUE TITLE
[Feature] Config option to disable infinity drill drops

### ISSUE THREAD

**Issue by LuisAdeur** [Buuz135/Industrial-Foregoing#467]
Industrial Foregoing Version: 
TeslaCoreLib Version: 
Crashlog (If Any): 

Would be awesome to add a config option to disable mobs dropping the infinity drill and/or make the drill only craftable not obtained by anything else

**Comment by Buuz135** [comment]
Update the mod, also if an issue tracker asks you to provide some information its a good practise to provide it

**Comment by LuisAdeur** [comment]
mod version is 1.11.9, deleted the config so the mod can generate a new one. was this already implemented or am i retarded because i don't see this option. i don't get the "updated the mod" answer since i was suggesting something that i haven't seen in the changelog for the mod updates...
