### ISSUE TITLE
[Request] Config option to change infinity drill drop chance / disable drops completely

### ISSUE THREAD

**Issue by Luke616** [Buuz135/Industrial-Foregoing#475]
Industrial Foregoing Version: 1.11.10-223
TeslaCoreLib Version: 1.0.63
Forge Version: 14.23.5.2796
Minecraft Version: 1.12.2
Crashlog (If Any): n/a

Echoing #467 , not sure why this issue was closed but I'd like to revisit it. As of the most recent version of IF, there is no config option to change the drop rate of the infinity drill or disable it entirely. I would very much appreciate such a feature, as having the drill drop from mobs does not fit well with the theme of my modpack. Please consider this request.

Thank you,
Luke616

**Comment by Buuz135** [comment]
It doesnt drop anymore stop creating issues without testing...

**Comment by Luke616** [comment]
Then what's up with this guy? I thought these particles meant that mobs had a chance of dropping the drill. Apologies for the misunderstanding.
![image](https://user-images.githubusercontent.com/3951604/50308399-16140a00-0469-11e9-97e9-a3c568ad1c4e.png)
Screenshot taken in:
Industrial Foregoing Version: 1.11.10-223
TeslaCoreLib Version: 1.0.63

**Comment by Buuz135** [comment]
There is another method of obtaining the Shiny variant that I wont spoil

**Comment by Luke616** [comment]
Ah, I see. May I change the request to instead ask for a configurable chance of these shiny mobs? They spawn a little too frequently for my tastes, and are confusing players of my pack. Thanks!

**Comment by Luke616** [comment]
Alright, thanks anyway

**Comment by Rsslone** [comment]
@Buuz135  I'd like to ask something in a slightly different way. Is there any chance we can get a config to disable the mob effects? They are indeed really confusing and the effects brightness is constant even at pitch black.
