### ISSUE TITLE
Latex Processing Unit wastes containers of latex

### ISSUE THREAD

**Issue by Mason11987** [Buuz135/Industrial-Foregoing#476]
Industrial Foregoing Version:  1.11.5
TeslaCoreLib Version:  1.12.2-1.0.15
Crashlog (If Any): 

Using Forestry, get a stack of latex cans, put them in the latex processing unit, and it eats the entire stack very quickly and does not dump 64 buckets worth into the machine.  It looks like each tick an item is eaten regardless of whether it's dumped into the machine or not.

Also happens with Buckets of latex, so not Forestry specific.

**Comment by Buuz135** [comment]
Can't replicate in a clean enviroment with Forestry.
