### ISSUE TITLE
crash mc 1.12.2_Forge 2796+IF 1.12.2-1.12.1-225

### ISSUE THREAD

**Issue by JasonKillsUs** [Buuz135/Industrial-Foregoing#478]
Industrial Foregoing Version: 1.12.2-1.12.1-225
TeslaCoreLib Version: 1.0.15.13
Crashlog (If Any): 

"https://paste.ee/p/bTo3T"
thanks for looking into it

**Comment by Buuz135** [comment]
Its an Integration Foregoing issue that has been alread reported
