### ISSUE TITLE
Laser Drill Ores config not loading

### ISSUE THREAD

**Issue by Shadowhunter82** [Buuz135/Industrial-Foregoing#483]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.2-226
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15

The Client starts, but the laser_drill_ores arn´t loaded proberly
I tryed to recreate the laser_drill_ores folder and the JSON file but that didn´t help.

Found this error message in the latest.log [LINK](https://pastebin.com/MdqVrsUz)

**Comment by Buuz135** [comment]
Deleting the folder and starting the game doesnt create the file properly?

**Comment by Shadowhunter82** [comment]
The file is created properly!, The JSON file is valid i check it with an validation tool!
The problem are the lenses some are working some not, it looks like it´s not loading the JSON properly

**Comment by Buuz135** [comment]
Do you specify the Y value to dig in the GUI?

**Comment by Shadowhunter82** [comment]
yes we did! 
I tryed it again in singleplayer and the laser mines (gold, iron, redstone, diamant complete 14ORES) but not silver, tin, copper, lead, bauxit, nickel, aluminium, Cinnabar usw. If i use lenses or change the Y value makes ah yield diference but i dont get the other ores

**Comment by Buuz135** [comment]
Do they show up in JEI?

**Comment by Shadowhunter82** [comment]
yes ... but if  i look at the lenses in JEI on some of the colores the ores show up and in some not! There are 2 screenshots of my jei[LINK](https://imgur.com/a/rYJUShQ)

**Comment by Buuz135** [comment]
Look the uses of the laser lense

**Comment by Shadowhunter82** [comment]
i have (pic1) "light blue lense" there are uses (diamond ore) and on the "orange one" there isn´t ah uses tab (pic2)

**Comment by Buuz135** [comment]
Thats not an orange lense... thats the pink one...

**Comment by Shadowhunter82** [comment]
Ups ... yes ... but if i press U on the pink lense thats the jei menu that comes!
And if i press U on the light blue lense i get the uses tab from the laser

**Comment by Buuz135** [comment]
Maybe there isnt any pink ores... Especially Magenta Laser Lens

**Comment by Shadowhunter82** [comment]
but why than i dont get tin, copper, lead, ... from the laser without a lense ... if i let the laser rund there should some of this ores show up .. (on the old version of the mod it worked fine i was told by my friends who are playing on my server)

**Comment by Buuz135** [comment]
The laser drill needs to be mining a defined Y level to increase the chance using the lens as shown in JEI. Giving the conditions shown there that ore will have the "weight" shown and the lense will increase the chance using that weight. The weight is the chance to spawn.

(The laser drill changed in the latest version)

**Comment by Shadowhunter82** [comment]
@RaveMaker 
THX I changed all ores to the actual item id´s and now everything works.
@Buuz135 
It looks like the laser config cant manage ore:dict ores!

**Comment by LumberWizard** [comment]
To expand and clarify on this, the issue seems to be that once the JSON file encounters an ore that doesn't exist, it doesn't attempt to add laser drill recipes for any subsequent ore listed in the file. For example, the 11th entry of 31 in the JSON was "oreSulfur" which I didn't have an ore for, and it only added drilling recipes for the first 10 ores, despite me having blocks for other ores which appeared after oreSulfur in the file, such as oreCopper or oreSapphire.
