### ISSUE TITLE
Laser Drill, Some Ores neither focusable nor obtainable.

### ISSUE THREAD

**Issue by KirinDave** [Buuz135/Industrial-Foregoing#49]
After about 8 hours of drill operation (and invesitsgion of JEI) I have not observed the laser drill producing AE2's certus quartz, EvilCraft's evil gems, or any Cyclic nether ores.

It'd be really nice if the Certus Quartz and charged certus quartz, could be obtained and focused.

**Comment by Jacky1356400** [comment]
Added via a [new update in Integration Foregoing](https://minecraft.curseforge.com/projects/integration-foregoing/files/2480973).
Unfortunately, I will not be adding support for Cyclic nether ores since they kinda overlaps with vanilla ores.
