### ISSUE TITLE
Potion Brewer causes crash on both SMP and server

### ISSUE THREAD

**Issue by purestone9** [Buuz135/Industrial-Foregoing#492]
Industrial Foregoing Version: 1.12.2-1.12.4-228
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): https://hastebin.com/ucunobajew.md

**Comment by purestone9** [comment]
Yes i have reported the issue to the Stoneblock 2 page aswell
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/209

**Comment by Buuz135** [comment]
Duplicate https://vgy.me/2deRD8.png
