### ISSUE TITLE
Villager trade exchanger interaction with >1 unstackable item trades.

### ISSUE THREAD

**Issue by VeryOriginalName** [Buuz135/Industrial-Foregoing#498]
Industrial Foregoing Version: 1.12.4
TeslaCoreLib Version: 1.12.2-1.0.15

I am currently playing a modpack that comes with the mod Forestry. This mod adds villagers who will trade  to you, among other things, frames that are unstackable. The trade for these frames appears but inserting emeralds doesn't do anything. I would suggest adding an internal buffer to the machine so that it can support trades such as these.

**Comment by Buuz135** [comment]
Not reproducible

**Comment by mthp1999** [comment]
Wondering if this was ever fixed or a workaround found
