### ISSUE TITLE
add more fluid that can convert in the fluid dictionary converter

### ISSUE THREAD

**Issue by freopt** [Buuz135/Industrial-Foregoing#499]
Industrial Foregoing Version: 
it is suggestion
TeslaCoreLib Version: 
Crashlog (If Any): 

Add things that are added by many mods like steam or even things like deuterium and tritium to be able to be converted. Other fluids would by ethanol or diesel which are used by several mods. Thanks.

**Comment by HydrogenC** [comment]
I also hope that the fluid dictionary can convert any fluid from any mod to another fluid that has the same fluid dict name.

**Comment by HydrogenC** [comment]
Please make it universal!

**Comment by TheCodedOne** [comment]
If you think its that simple to make it "universal" please submit a PR. in reality we can't just "make it universal", there is no such thing as a fluid dict, every fluid has to be manually added.

**Comment by Inve1951** [comment]
Please add CT support at least. Perhaps it's already there but not documented in the wiki? https://github.com/Buuz135/Industrial-Foregoing/wiki/Crafttweaker-Support

Maybe something like this?
```zs
mods.industrialforegoing.FluidDictonaryConverter.registerEquals([
  <liquid:for.honey>*1,
  <liquid:honey>*1
])
```

**Comment by Buuz135** [comment]
So like this? https://crafttweaker.readthedocs.io/en/latest/#Mods/Industrial_Foregoing/FluidDictionary/

**Comment by Inve1951** [comment]
Perfect! Thanks.

**Comment by HydrogenC** [comment]
Thanks, CraftTweaker is a good solution!
