### ISSUE TITLE
Possible bug with Machines? (Plant Sower/Plant Recolector)

### ISSUE THREAD

**Issue by Frixon1** [Buuz135/Industrial-Foregoing#5]
Are the machines, in my case the Plant Sower and Plant "Recolector", designed to constantly use energy with no way to turn them off? Or is this a bug? I'd like to know because it drained my power banks before I even finished building the farm itself.

**Comment by Buuz135** [comment]
Yes it is intended, it checks a block after another everytime it does work.

**Comment by Frixon1** [comment]
So in order to make the machines essentially "Idle" you'd have to just stop supplying it with energy?

**Comment by Buuz135** [comment]
Yep, redstone mode is not implemented yet, but next version will.

**Comment by Frixon1** [comment]
Oh, Alright that makes much more sense than what I was understanding from your earlier answer. I was afraid it was a potential design choice. I'm glad its just not implemented yet. XD

**Comment by Buuz135** [comment]
Changed in https://minecraft.curseforge.com/projects/industrial-foregoing/files/2442242
