### ISSUE TITLE
mob slaughter factory

### ISSUE THREAD

**Issue by Panterh3art** [Buuz135/Industrial-Foregoing#50]
it seems that the mob slaughter factory is crashing the server where i am playing when i place it in the overworld

**Comment by Buuz135** [comment]
Crashlog? Version?

**Comment by Panterh3art** [comment]
mod version 
industrialforegoing-1.12-1.3-58
it seems to be server sided since in single player it works
i will get u an crash report later this day

**Comment by FiveEYZ** [comment]
no crash-report is being generated, but here is the server-log just before it closes:
http://madback.nu/paste/view/raw/7895db4d

**Comment by Buuz135** [comment]
Sponge crash, it will be very low priority. It shouldn't have to stop the game for storing null in NBT.
