### ISSUE TITLE
Upgrades can be inserted into Material Stonework Factory using a hopper: is this intentional

### ISSUE THREAD

**Issue by Lothrazar** [Buuz135/Industrial-Foregoing#501]
Industrial Foregoing Version: 1.12.4 
TeslaCoreLib Version:  1.0.15
Crashlog (If Any): 

Exactly as the title says,  IItemHandler :: inventory.insertItem(i, stack, simulate);  will insert upgrades into the upgrade slot such as from a hopper, and im not sure if this is a bug or intentional

The similar function IItemHandler::extractItem blocks access to these slots

See context related to Storage Network:  Which cannot withdraw these upgrades, but putting an upgrade into a storage network will store them in these upgrade slots if available 
https://github.com/Darkosto/SkyFactory4Issues/issues/111

**Comment by Buuz135** [comment]
I will say that this is intentional
