### ISSUE TITLE
sharpness not on axe in echant applyer

### ISSUE THREAD

**Issue by Redd56** [Buuz135/Industrial-Foregoing#502]
Industrial Foregoing Version: 1.12.4
TeslaCoreLib Version: 1.0.15
so in vanilla minecraft and modded you can enchant an axe with sharpness, up to level 5 as per all sharpness enchantable items. but for some reason the enchantment applicator doesnt allow this?.... it just ignores the sharpness enchant on my books
plz fix

**Comment by Buuz135** [comment]
It works https://streamable.com/e1g4t
