### ISSUE TITLE
Item icons missing in black hole controller for items in BH units inside it

### ISSUE THREAD

**Issue by LuciusV** [Buuz135/Industrial-Foregoing#503]
Industrial Foregoing Version:  industrialforegoing-1.12.2-1.12.5-229.jar
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15.jar

Place black hole controller, put 9 bh units inside, try to put any item in - item icon is missing and one cannot retrieve item back

**Comment by Flanks255** [comment]
Yup, this broke in 1.12.5-229, i was just about to open an issue about it myself, it functions correctly in 1.12.4-228.

Also external forces can still extract items correctly(duct work/AE2 storage bus ETC)
