### ISSUE TITLE
[Request] Speed Upgrades

### ISSUE THREAD

**Issue by Quest79** [Buuz135/Industrial-Foregoing#504]
Industrial Foregoing Version: **1.12.4**
TeslaCoreLib Version: **1.12.2 - 1.0.15**

Allow us to stack tesla speed upgrades to 64 in these, please. If the power needed at 64 stacks is 1 billion rf/t so be it, but it would be highly useful and fun to have the option. Currently the alternative is to ugly up the place with dozens of same machines in a small area and this gets very tedious to maintain.

**Comment by Buuz135** [comment]
No
