### ISSUE TITLE
[Feature Request] Add slots for the Tesla core lib upgrades to machines that use them

### ISSUE THREAD

**Issue by calloatti** [Buuz135/Industrial-Foregoing#506]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.4-228
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15

Since the addition of the range and other upgrades and add-ons, there is no way to fit the four tesla core lib upgrades and other upgrades in a machine.

It would be great if you could add four more slots for addons like this:

![image](https://user-images.githubusercontent.com/12817862/52742041-9fe9da80-2fb5-11e9-8547-a6eddf94089a.png)

Also, a Loot upgrade for the Mob Crusher would be great.

**Comment by Buuz135** [comment]
No, that way you need to really think about the upgrades you need
