### ISSUE TITLE
black hole unit dupe

### ISSUE THREAD

**Issue by EthernalVoid** [Buuz135/Industrial-Foregoing#507]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.5-229
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15

>you can put an item into a black hole unit, break it and it will retain said item
>when you put that (full) black hole unit in another black hole unit you can add more (empty) black hole units to get the (full) black hole units 

>FIX: blacklist inventory blocks like black hole units in a black hole unit
Better fix: have black hole units check for complete item data

**Comment by EthernalVoid** [comment]
It would be great if there was a config to add items to the black hole unit / controller blacklist

**Comment by EthernalVoid** [comment]
Or you could add a custom "oreInventory" specifier which would be always blacklisted to which we could add items via crafttweaker scripts ;)

**Comment by EthernalVoid** [comment]
So has it been fixed?

**Comment by Buuz135** [comment]
yes

**Comment by EthernalVoid** [comment]
Awesome :D

**Comment by EthernalVoid** [comment]
Thank you.
