### ISSUE TITLE
Server lag With BHU 

### ISSUE THREAD

**Issue by DirkSch** [Buuz135/Industrial-Foregoing#51]
I have 2 Forestry farms on my server where the item store in Black Hole Units for test.
The server spawns
`[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6409ms behind, skipping 128 tick(s)`
in every seconds.
If I remove the BHU blocks are all normal. The BHU is connect by thermal dynamics itemducts. other mods are in the crashlog below.
And I have server crash if I run a Resourceful Furnace.
https://pastebin.com/8u3NBVZb
I can't also extract essence from Resourceful Furnace. No bucket works.

**Comment by Buuz135** [comment]
Can I get the amount of items they have?

**Comment by DirkSch** [comment]
500.000 Wood and 300.000 saplings are in the BHU.
