### ISSUE TITLE
[Question] Laser Drill depth - how to use it? 

### ISSUE THREAD

**Issue by Giovanni-NL** [Buuz135/Industrial-Foregoing#510]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.4-228
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15

Since no in-game book nor wiki nor reddit seem to have the answer, I hope the mod author could share some insight here...  How exactly does the drill depth setting in de GUI of the laser base work?  Suppose I want to drill for diamonds.  And I have 6 light blue lenses added to the drill base.  Do I then set the drill depth number to 11 to have a good chance of actually drilling diamonds?  Or do I have to take into account the y-level at which I have placed the drill base, and then subtract the number you can set in the GUI to get to 11?

**Comment by Buuz135** [comment]
No, the Y in the gui is the only one that matters
