### ISSUE TITLE
Black Hold Label Not Updating

### ISSUE THREAD

**Issue by IrradiatedChimp** [Buuz135/Industrial-Foregoing#512]
Industrial Foregoing Version: 1.12.2-1.12.4-228
TeslaCoreLib Version: 1.12.2-1.0.15

Not sure if this is a bug or intentional ... The Black Hole Label does not update on it's own, only when I right click on the Black Hole Unit to see how much I have inside.  Not sure if this is intentional or not.  I currently have the Black Hole Units hooked up to external storage from Refined Storage.

**Comment by Buuz135** [comment]
I cant replicate, it works fine in Singleplayer and mmultiplayer

**Comment by HorribleNerd** [comment]
Still happening, I'm using Mekanism's Ultimate Mechanical Pipes to insert Brine, same thing happens with Thermal's Fluiducts and EnderIO's Fluid Conduits.

On a Forge 13.23.5.2847 server, with IF 1.12.13 and TCL 1.12.2-1.0.17

**Comment by HorribleNerd** [comment]
Does this for all liquids, relogging and opening it seem to be the only ways to update it.
