### ISSUE TITLE
Instant crash upon world initialization with Ender IO

### ISSUE THREAD

**Issue by GAsplund** [Buuz135/Industrial-Foregoing#513]
Industrial Foregoing Version: 1.12.5-229
TeslaCoreLib Version: 1.0.15
Crashlog: https://pastebin.com/u3MYgnuB

Seems like an issue between industrial foregoing and Ender IO conduits trying to connect to the latex processing unit. Upon loading the world again using `removeErroringTileEntities=true` conduits are removed but not the processing unit.

**Comment by Buuz135** [comment]
Nothing I can so try redownloading the mods
