### ISSUE TITLE
Pump with replaceFluidWithCobble = false seems to be infinite source

### ISSUE THREAD

**Issue by Dinip** [Buuz135/Industrial-Foregoing#514]
Industrial Foregoing Version: 1.12.2-1.12.5-229
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): 

Hi,
I think I found a "bug". I'm currently playing FTB Ultimate Reloaded but buildcraft has the pump disabled so we are forced to use industrial foregoing pump to get the oil. The problem starts with me going to the config file and changing `replaceFluidWithCobble` from true to false. The idea was to set it false so we can get the oil and when it finishes there was no cobblestone structure where the oil was (I don't like to see "random" and "deformed" structures).
What seems to happen is that without the replacement with cobblestone the fluid never "end", so the oil well was infinite oil. A few days ago when I placed the pump on a "little" lava well the same happened. It was like 10blocks x 10 blocks x 4 blocks and I got ~2000 buckets of lava and there was more left...

Here you have some pictures to show it. The world it the same, copy+paste before starting the test.
First one is with replaceWithCobble set to false
The gif is what seems to happen on the bottom of the oil well
https://gyazo.com/74b3f8750e85f0b5917eb1fa73b6529e
![image](https://user-images.githubusercontent.com/8941012/53420314-7bd5c280-39d3-11e9-9448-ecd7405dde4d.png)
![image](https://user-images.githubusercontent.com/8941012/53420331-81330d00-39d3-11e9-9c0d-1b0df522582d.png)

Then the same world but now with replaceWithCobble set to true
![image](https://user-images.githubusercontent.com/8941012/53420457-c22b2180-39d3-11e9-9208-09d61c258eac.png)
![image](https://user-images.githubusercontent.com/8941012/53420473-c8210280-39d3-11e9-8337-64e35aab34e2.png)

Hope it gets fixed 😄

**Comment by harry-clarke** [comment]
@Buuz135 Bug still exists in 1.12.7, so not sure this is fixed.

**Comment by harry-clarke** [comment]
See https://github.com/MinecraftForge/MinecraftForge/commit/5ace86da121feafd20ed1f2d3e34ad99fee0599a#diff-a27ff85fc320f1d8269b133701c1c5b2
