### ISSUE TITLE
Wither builder rotation

### ISSUE THREAD

**Issue by aerde** [Buuz135/Industrial-Foregoing#515]
Industrial Foregoing Version: 1.12.5
TeslaCoreLib Version: 1.12.2-1.0.15

Wither builder working area always aligned east-west, and can't be rotated. I think, this is not an intended behaviour.

**Comment by Buuz135** [comment]
No matter which rotation you build the wither it will always spawn facing south, so there is no point on rotating it.

**Comment by aerde** [comment]
> No matter which rotation you build the wither it will always spawn facing south, so there is no point on rotating it.

Got it, thanks for fast reply!

**Comment by Minethulhu** [comment]
> No matter which rotation you build the wither it will always spawn facing south, so there is no point on rotating it.

I personally disagree with this for the following reasons:

1) I can manually build the Wither with any orientation (even flat on the ground if I desire), regardless of which orientation the Wither actually spawns in.  I have some expectation that I should be able to just drop this machine into an existing room to replace my manual work (but maybe not the "flat on the ground" option).  The only manual requirement seems to be that I have empty space on either side, but  not front-back or top-bottom (although I have not played around with all options exhaustively).

2) Other Industrial Foregoing machines allow me flexibility in changing their working area to any of the four cardinal points (north, south, east and west).  I assume I can do the same with this machine.  When it doesn't rotate, I assume it is something I am doing wrong.

I would expect I should have at least the two upright orientation options: upright east-west and upright north-south.

**Comment by Punk-Geek** [comment]
> No matter which rotation you build the wither it will always spawn facing south, so there is no point on rotating it.

This neglects to consider the intermediate step of actually placing the blocks. If you have a 1 wide build area (wither proof obsidian or any other option) that happens to be facing the wrong way it's impossible to get the Wither Builder to work.
