### ISSUE TITLE
Duplication bug with Black hole unite/controller 

### ISSUE THREAD

**Issue by runescapejon** [Buuz135/Industrial-Foregoing#516]
Industrial Foregoing Version: 1.12.2-1.12.6-230
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any):  n/a

You would need a Thermal Expansions mod to perform this bug there in it. Obtain the item from Thermal Expansions called "Item Allocator" and place it down right click it. Then on the arrow in orange make it up to 64 stack. Next obtain two items from Industrial Foregoing called "Black Hole Unit" and "Black Hole Controller". place down the Black Hole Controller right click it on the middle row place a black hole unit then grab an item you want to two dupe with one place it on the below black hole unit within the Controller. Then go to your Item allocator and place your second item there and then you start either obtain an extra item(glitches sometimes) or you will automatically have infinite of that item you want to dupe with. Here a video for more information https://www.youtube.com/watch?v=Ie6p4ytNPIM&feature=youtu.be 
Infinite dupe GIF: https://gyazo.com/9fe214f43ce4a56f5c97467e11cf2b38

**Comment by runescapejon** [comment]
Also just found that this issue related to this https://github.com/CoFH/Feedback/issues/1372 but it was never reported to this github

**Comment by TonyTheGOD** [comment]
Ohhh YES i can finally dupe on servers :D FUCK YES
