### ISSUE TITLE
[Bug]Spamming crash-reports when opening face config menu

### ISSUE THREAD

**Issue by fluid-uu-matter** [Buuz135/Industrial-Foregoing#517]
Industrial Foregoing Version: 1.12.6-230
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any):
Too many crash reports, so I only uploaded some of these
[crash-2019-03-04_02.13.06-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/2923487/crash-2019-03-04_02.13.06-client.txt)
[crash-2019-03-04_02.13.07-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/2923488/crash-2019-03-04_02.13.07-client.txt)
[crash-2019-03-04_02.13.08-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/2923489/crash-2019-03-04_02.13.08-client.txt)
[crash-2019-03-04_02.13.09-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/2923490/crash-2019-03-04_02.13.09-client.txt)
[crash-2019-03-04_02.13.10-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/2923491/crash-2019-03-04_02.13.10-client.txt)

When opening machine face config menu, crash-reports are spammed and making Minecraft very laggy:
(I have VanillaFix installed)
![2019-03-04_02 11 50](https://user-images.githubusercontent.com/17115547/53699525-2743a480-3e24-11e9-9699-bdfda83cacc3.png)
VanillaFix problem screen:
![2019-03-04_02 14 22](https://user-images.githubusercontent.com/17115547/53699526-2ad72b80-3e24-11e9-85b2-b1b4c6ffaeca.png)

**Comment by Buuz135** [comment]
Remove Vanilla Fix and check if your mc crashes

**Comment by fluid-uu-matter** [comment]
Not crashing, and also not spamming crash-reports, but I dont want to remove vanillafix because vanillafix let me continue to play after crashing
Maybe I need to config Vanillafix or IndustrialForegoing?

**Comment by fluid-uu-matter** [comment]
But the mod is still spamming logs when VanillaFix is not present, just not crash-reports
[latest.log](https://github.com/Buuz135/Industrial-Foregoing/files/2923556/latest.log)

**Comment by Buuz135** [comment]
I dont see any reference to Industrial Foregoing or Tesla Core lib on those logs, so there is nothing I can fix

**Comment by fluid-uu-matter** [comment]
But the spam only occurs when I opened the face config menu of IF, so it maybe a conflict between IF and another mod?

**Comment by fluid-uu-matter** [comment]
tried with only forgelin, tesla core lib, industrial foregoing and vanillafix installed, no warnings, no spammings.
It mostly be a conflict between IF and another mod.
Check my mod list from the logs I uploaded.
