### ISSUE TITLE
Industrial-Foregoing Machines not accepting RF [Server]

### ISSUE THREAD

**Issue by BlacklightCraft** [Buuz135/Industrial-Foregoing#518]
Industrial Foregoing Version:  1.12.6 (1.12.2-1.12.2)
TeslaCoreLib Version: 1.12.2. - 1.0.15 (1.0.15)
Crashlog (If Any): No log in my case.

I got a probleme on my 1.12.2 Server with the Machines from Industrial Foregoing where they cant accept RF from Thermal Expansion (5.5.3.41 (5.5.3)). But they use the RF produced by the machines of the mod itself. Fluxducts connect without a problem.

I am tired of searching and thought somone can explain wether it is a bug or that i am doing something wrong.

**Comment by Buuz135** [comment]
Show me some pictures of your setup where it doesn't work

**Comment by brnmick** [comment]
Yea im noticing the same issue. I tried using energy conduits from enderio as well as transfer pipes from extra utilities. Either way no RF transfers to any of the industrial foregoing machines. However using a Magmatic Generator from actually additions works. So i know there its a bug. Fyi i am using the enigmatica E2 modpack  2 1.77 (mc ver. 1.12.2)
