### ISSUE TITLE
straw effects are just plain ridiculous

### ISSUE THREAD

**Issue by lag42** [Buuz135/Industrial-Foregoing#52]
everything you drink with the straw that has an effect is magnified ridiculously,
 for example after drinking liquid meat i got an astronomical amount of absorption hearts.
![2017-09-22_08 49 42](https://user-images.githubusercontent.com/22325011/30747580-543a5e4e-9f73-11e7-95dc-08cb9b20145c.png)

**Comment by TheCodedOne** [comment]
How long does it last?

**Comment by lag42** [comment]
1 or 2 seconds, duration doesn't appear to be modified
