### ISSUE TITLE
Infinity Drill restarts block breaking progress while charging wirelessly

### ISSUE THREAD

**Issue by baxcat** [Buuz135/Industrial-Foregoing#526]
Industrial Foregoing Version: **1.12.2-1.12.6-230**
TeslaCoreLib Version: **1.12.2-1.0.15**
Crashlog (If Any): **No crash**

I didn't know if I should submit this to Ender IO or Industrial Foregoing but since the drill is from this mod I figured it would fit better here. I have a wireless charger field *(from Ender IO)* that covers my whole base (a small island) so anytime I want to mine something with the infinity drill, I can't. It works perfectly when outside the charging field, or while the field is charging something else/out of power. Basically any time the drill is consistently getting power, I can't use it. It just tries to mine the block and restarts. Like I'm resetting the item and thus resetting the mining process every few ticks or something. Insta-mine blocks such as itemducts usually do succeed in breaking. I looked around online for this but couldn't find anything related to this issue.

Demonstration: https://www.reddit.com/user/shayhayhay/comments/b1nsh3/drill_example_for_rfeedthebeast/

**Comment by tomek7667** [comment]
this should be reopened
