### ISSUE TITLE
Preformance Increase question

### ISSUE THREAD

**Issue by Xenonix** [Buuz135/Industrial-Foregoing#527]
#Industrial Foregoing Version: 1.12.2-1.9
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): None

I love this mod, just noticed that when machines are full (example using the Latex Processing Unit) that the machine still keep updating eventhough nothing goes in or out. I used LagGoggles to see that idle machines (full but not on pause) use over 300-400 uS when, lets say Thermal Expansion machines, are on 20-40 uS (also full and idle).
Dont know if anybody noticed this or if it can be fixed, would be a great improvement though.

Keep up the good work on this remake of a classic great mod!

**Comment by Buuz135** [comment]
LaggGoggles is unreliable when checking tick time, it will add random amounts to random tiles depending of where they are placed on the chunk. Examples:
https://streamable.com/abtg1
https://streamable.com/odylw
https://streamable.com/xesc1

**Comment by Xenonix** [comment]
Hey, i know its unreliable to look for like differences of 20-50 Us. Just notice that if i "Pause"  the machine with the button in the upper left corner that the amount changes drasticly. (few 100). As if the machine is constant updating eventhough the inputs/outputs are full.
Anyway thx for the verry quick response, and if its nothing then its nothing ;). Just maybe something to check.
