### ISSUE TITLE
Plant sower not working (not ftbutils) (at least I think)

### ISSUE THREAD

**Issue by AutismoMan** [Buuz135/Industrial-Foregoing#528]
Industrial Foregoing Version: 1.12.8-232
TeslaCoreLib Version: 1.0.15
Crashlog (If Any): 

So this has been driving me absolutely crazy for the past few days, but I'm trying to make a tree farm using the plant sower, but when I give it sapplings, power, and put a block over it, it repeatedly makes the sappling planting sound, without planting anything. I've looked everywhere on the internet, and yes I have ftbutils, but my fake player is set to ally, and the plant sower doesnt even work in unclaimed chunks.

Lastly I think this might be useful, but it only does not work on a server. It works perfeclty on a singleplayer world. On the singleplayer world, if I set up ftbutils properly (fake player: ally, block placing: ally) it works. If I set fake player to member or none, then it gives me the same effect as on the server, Any ideas?

**Comment by Buuz135** [comment]
Show me a picture of your setup.

**Comment by AutismoMan** [comment]
Alright so I mean I never really got it to work on my server so I don't have a big or complicated setup where anything could go wrong but heres a basic setup where it doesnt work.
https://imgur.com/xcfwm8t
(Yes im sure there is power and sapplings in the machine and the little start stop button is set to start)

**Comment by Buuz135** [comment]
Try unprotecting it and check if it works, just as a test.

**Comment by AutismoMan** [comment]
Alright so it still didn't work. I tried removing FTBUtils from the server just to be sure that wasn't the cause and it still didn't work.

**Comment by Buuz135** [comment]
What are you trying to plant?

**Comment by AutismoMan** [comment]
Oak saplings

**Comment by Buuz135** [comment]
Please, if you use discord use for better communication. https://github.com/Buuz135/Industrial-Foregoing/issues/529

**Comment by AutismoMan** [comment]
Sure should I just go ask the same question on the mod>industrial foregoing chat?

**Comment by Buuz135** [comment]
Yep
