### ISSUE TITLE
Feature Request:  Extraction Conveyor to harvest single plant?

### ISSUE THREAD

**Issue by Zetharion** [Buuz135/Industrial-Foregoing#530]
Industrial Foregoing Version: 
TeslaCoreLib Version: 
Crashlog (If Any): 

Alright it might sound ridiculous but I figured I'd give it a try.  Can you make it so that an Extraction Conveyor will harvest only the plant that is next to it, or do you think that is too similar to what a base Plant Gatherer does?  I was thinking it could be a poor mans super slow auto single plant farm.

**Comment by Buuz135** [comment]
Yes, it sounds a bit ridiculous 😆. But I don't like it.
