### ISSUE TITLE
Mob duplicator and wither skeleton

### ISSUE THREAD

**Issue by kimsis** [Buuz135/Industrial-Foregoing#532]
Industrial Foregoing Version: 1.12.8-232
TeslaCoreLib Version: 1.0.15
The Mob Duplicator cannot spawn wither skeletons in the overworld (didn't test in other worlds). I have given it 5x5x4(height) space and tried to put the duplicator 1block, 2 blocks, 3 blocks above ground, doesn't work in any of the ocasions. It seems to consume essence and rf, but no skeletons spawned.

**Comment by Buuz135** [comment]
Show me a picture of your setup

**Comment by kimsis** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/23614179/54631380-36f5f680-4a7c-11e9-9d9b-59a9a6a70c83.png)

It works with other mobs, mainly invoker, cuz that's what I use it for

**Comment by Buuz135** [comment]
Have you tried having a 4 blocks high space?

**Comment by kimsis** [comment]
I just did, and it spawned it on top ....

**Comment by Buuz135** [comment]
The mob duplicator checks if there is enough space for a mob to spawn, make sure there is enough for it.

**Comment by kimsis** [comment]
How comes there is enough for an Invoker but not a Wither skeleton?

**Comment by Buuz135** [comment]
Wither skeletons are taller than invoker/villager

**Comment by kimsis** [comment]
The problem lied somewhere else. The duplicator was trying to spawn the skeleton on top of it, however it couldn't because of the enderio conduits I guess, cuz the moment I put the underground, it started working. However I don't know why it was able to spawn evocation villagers (my bad not invokers, too much dota). Maybe when it's bigger than 2 blocks something prevents it from doing that?

**Comment by kimsis** [comment]
Aaand just found why.... I didn't put any upgrades for the working are, sorry for wasting your time, it was just trying to spawn the wither skeleton in the 2 block are that is assigned, but due to the conduits it couldn't do it I guess.
