### ISSUE TITLE
The Plant Interator harvesting problem with SImple Harvest plants

### ISSUE THREAD

**Issue by Fireztonez** [Buuz135/Industrial-Foregoing#535]
On my modapck I have Mystical Agriculture, and I have setup all Mystical Agriculture plants and XL Foods Plants into Simple Harvest to be able to Right-click to harvest. Everithing work's fine with every mods for harvesting but, with the Plant Interactor it collect the things really fast without harvesting anything... So, this caused a big broken game bug... I really enjoy the plant Interator and I really whant to keep in my modpack, but, for sure, I can't keep if that bug exist...

Can you please look to fix the compatibility issue or at least adding a BlackList config if you can't fix it....

Video in action: https://clips.twitch.tv/SmallPuzzledSamosaTBTacoLeft

Industrial Foregoing Version: 1.2.8.232
TeslaCoreLib Version: 1.0.15
SimpleHarvest (By TehNut) 1.2.7-20

Thank you for your amazing mod, I really enjoy playing with!!
Fireztonez

**Comment by Buuz135** [comment]
It has been researched in the Modded Minecraft discord that it is SimpleHarvest issue not reseting the crop state when there are no drops, please report it there
