### ISSUE TITLE
Plant Interactor causing infinite items

### ISSUE THREAD

**Issue by phxe** [Buuz135/Industrial-Foregoing#536]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.8-232.jar
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15.jar
Crashlog (If Any): N/A

The plant interactor is harvesting from crops(tested carrots and wheat) but not resetting the crop afterwards. The machine can continually harvest from a single crop with no time in between. Recreated on a multiplayer server and single-player creative world.

GIF of the issue:
https://gyazo.com/6cab8f8e70f5415d8374cf4b863e0652

**Comment by Buuz135** [comment]
Do you have simple harvest?

**Comment by phxe** [comment]
Yes, and everything else from FTB Ultimate Reloaded.

**Comment by Buuz135** [comment]
Duplicate https://github.com/Buuz135/Industrial-Foregoing/issues/535
