### ISSUE TITLE
Mobs with over 300 health target the mob crusher

### ISSUE THREAD

**Issue by Immortallis1** [Buuz135/Industrial-Foregoing#538]
Industrial Foregoing Version: 1.12.8-232
TeslaCoreLib Version: 1.0.15

Mobs with over 300 health hit by the mob crusher make their way towards it and do nothing.
Haven't tested for mob slaughter factory, may want to test that too.

**Comment by Buuz135** [comment]
Is that an issue? Nothing I can do about it
