### ISSUE TITLE
Configurability of Conveyors

### ISSUE THREAD

**Issue by Vyraal1** [Buuz135/Industrial-Foregoing#539]
Industrial Foregoing Version: 1.12.10
TeslaCoreLib Version: 1.0.15

Hey Buuz can we get configs to remove the conveyor extractor removing armor and weapons from mobs?

**Comment by Saereth** [comment]
to elaborate, armorable mobs and mobs with special enchants like shadow's apotheosis mod are providing players and endless stream of super armors at zero risk with the conveyors. Should we have actually configured armorable mobs to have mobs with end armors players would also have access to those right away, this has far worse implications for other packs than ours. A config would be highly appreciated
