### ISSUE TITLE
Weird rectangle GUI glitch

### ISSUE THREAD

**Issue by Arkyo** [Buuz135/Industrial-Foregoing#54]
![image](https://user-images.githubusercontent.com/25037295/30782081-5ba866d0-a15d-11e7-9164-9232158a7b61.png)

**Comment by Buuz135** [comment]
How much work does it says it has when you hover over the yellow bar?

**Comment by Buuz135** [comment]
Mod Version?

**Comment by Arkyo** [comment]
![image](https://user-images.githubusercontent.com/25037295/30810738-a1adb794-a238-11e7-8e33-ceb1ee27bb62.png)

**Comment by Arkyo** [comment]
@Buuz135
