### ISSUE TITLE
More optimizations

### ISSUE THREAD

**Issue by bigenergy** [Buuz135/Industrial-Foregoing#540]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.10-234
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15

My server is experiencing high loads due to this mod. I suggest adding various settings to improve performance and optimization.
I hope for your help, thank you!
Spark link - https://sparkprofiler.github.io/#Ap18vMI4eW

**Comment by TheCodedOne** [comment]
15% isn't a lot and judging by the number of other things in that list I'd have to assume you have a lot of machines, your server issues are caused by the 40%+ taken up by mekanism.
