### ISSUE TITLE
BlackHole Controller Dupe Bug

### ISSUE THREAD

**Issue by VerdExNeon** [Buuz135/Industrial-Foregoing#541]
Industrial Foregoing Version: 1.12.8-232
TeslaCoreLib Version: 1.0.15

Piping items into a Black Hole Controller will replace whatever item is in the first possible Blackhole Unit with the piped item, as well as keep the original quantity allowing for easy item manipulation.

https://imgur.com/a/sSIWrYn

**Comment by Buuz135** [comment]
Update the mod
