### ISSUE TITLE
"Crash missing method java.lang.NoSuchMethodError: IModel.asVanillaModel()"

### ISSUE THREAD

**Issue by Strykus** [Buuz135/Industrial-Foregoing#542]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.8-232
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): https://paste.dimdev.org/uyiyemetim.mccrash

**Comment by Buuz135** [comment]
Update forge to at least 2806

**Comment by Buuz135** [comment]
Can you edit the title to say "Crash missing method java.lang.NoSuchMethodError: IModel.asVanillaModel()"

**Comment by Blue-Beaker** [comment]
after updating forge:
crashes with no crash-report
https://paste.dimdev.org/kudocabeco.md

**Comment by kencinder** [comment]
Or change your calendar to April 2nd...cause of VERY bad joke.

https://github.com/Buuz135/Industrial-Foregoing/blob/c098c4d32f1c39f3e06ac6edc0d2dc0eb4d430dc/src/main/java/com/buuz135/industrial/proxy/client/event/IFClientEvents.java#L79

**Comment by TheCodedOne** [comment]
People should be using the latest release build of forge in which this does not crash, its not a bad joke its just that you seem to like to use extremely outdated versions.

**Comment by Immortallis1** [comment]
this did not happen before today (April 1).

**Comment by TheCodedOne** [comment]
@Immortallis1 we're aware, update forge like we said.

**Comment by GhEppIO82** [comment]
thank you bro
