### ISSUE TITLE
Startup crash 1.12.2-1.0.15

### ISSUE THREAD

**Issue by Blue-Beaker** [Buuz135/Industrial-Foregoing#543]
Industrial Foregoing Version: 1.12.8-232
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): https://paste.dimdev.org/adibusohed.mccrash

**Comment by Buuz135** [comment]
See #542

**Comment by Blue-Beaker** [comment]
Updated forge but crashes with no crash-report
https://paste.dimdev.org/kudocabeco.md

**Comment by Buuz135** [comment]
That's not an IF issue now

**Comment by Blue-Beaker** [comment]
> That's not an IF issue now

updated optifine, problem solved
