### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ZoeeeeeBell** [Buuz135/Industrial-Foregoing#544]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.10-234
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): https://paste.dimdev.org/epituqudoh.mccrash

(This mod was working for me just yesterday, but only this morning it seems to be the issue minecraft is crashing?)

**Comment by Buuz135** [comment]
See #542

**Comment by ZoeeeeeBell** [comment]
Just crashes right away ?

**Comment by Buuz135** [comment]
See #542 , and do what I said in the response
