### ISSUE TITLE
Suggestion for a machine incompatibility fix!

### ISSUE THREAD

**Issue by SirAron111** [Buuz135/Industrial-Foregoing#545]
The Crusher somehow can cause crashes if it gets attacked by certain mobs from other mods or even if it is swarmed by silverfish. Or when shoot at by a wither skeleton in the nether. Is there a way to fix this? Or could you make it so that it can attack trough walls to enable it to be out at a save place behind a wall so mobs can’t attack it. Or make it do dmg in a way that mobs don’t get agro to the crusher?

**Comment by Buuz135** [comment]
If you don't provide a crash log that's just false accusations. Nothing I can do about it.

**Comment by calloatti** [comment]
>  it can attack trough walls

Also, the mob crusher can already kill mobs behind a wall.
