### ISSUE TITLE
Error with Industrial Foregoing in Galacticcraft

### ISSUE THREAD

**Issue by Blizzard319** [Buuz135/Industrial-Foregoing#547]
Industrial Foregoing Version: 1.12.2-1.12.11
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog: https://paste.dimdev.org/umidopekih.mccrash

**Comment by DeathMouser** [comment]
Also in Galacticraft, launched via Twitch App

Industrial Foregoing Version: 1.12.2-1.12.11
TeslaCoreLib Version: 1.12.2-1.0.15
 Crashlog: https://paste.dimdev.org/oqulegukif.mccrash

**Comment by oreoholic** [comment]
+1

Crashlog: https://paste.dimdev.org/ebudocigij.mccrash

**Comment by Buuz135** [comment]
See #542
