### ISSUE TITLE
[1.12.2]Invalid statistic

### ISSUE THREAD

**Issue by CraftalotReloaded** [Buuz135/Industrial-Foregoing#548]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.11-235.jar 
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15.jar

I got this warning when the server finished loading after updating:
[13:43:36] [Server thread/WARN] [minecraft/StatisticsManagerServer]: Invalid statistic in ./world/stats/d76a52a2-d621-432f-99cc-b05519ac07bd.json: Don't know what stat.craftItem.industrialforegoing.black_hole_controller is

**Comment by Buuz135** [comment]
Does the server crash?

**Comment by CraftalotReloaded** [comment]
It doesn't, but idk what happened but one of the mods we updated causes everyone to timeout when they try to connect

**Comment by Buuz135** [comment]
And you picked IF for just that warning?

**Comment by CraftalotReloaded** [comment]
No, but i reported it regardless of that

**Comment by CraftalotReloaded** [comment]
Turns out his black hole controller broke though
