### ISSUE TITLE
Laser drill lens effects stacking improperly

### ISSUE THREAD

**Issue by zapl** [Buuz135/Industrial-Foregoing#549]
While browsing the code to figure out how lenses stack I noticed that the code that deals with them in `LaserBaseTile#innerUpdate()` is broken since https://github.com/Buuz135/Industrial-Foregoing/commit/663f8bd8d625cbb3ea56d2033b70f987a90219ae

the line https://github.com/Buuz135/Industrial-Foregoing/blob/361924f04fd4704182168a8bfab09b8da34f74e6/src/main/java/com/buuz135/industrial/tile/world/LaserBaseTile.java#L195 does not belong into the `for` loop that iterates over the lenses to calculate the final weight of an ore. It currently adds the item multiple times with increasing weight thus over-amplifying the effect of lenses. Needs simply to be moved 2 down.

**Comment by TomShkurti** [comment]
Made a pull request with a fix for this since it was technically my fault.
