### ISSUE TITLE
Black Hole Controller/Unit - Item Duplication

### ISSUE THREAD

**Issue by TheUntamed** [Buuz135/Industrial-Foregoing#551]
Industrial Foregoing Version: 1.12.8-232
TeslaCoreLib Version: 1.0.15
Modpack: Enigmatica 2 Expert Version: 1.59a
Using Black Hole Units in a Controller (except the first slot of a Controller) duplicates any item that is inserted.
1 Stack is placed in the top slot:
![inserting 1 stack](https://user-images.githubusercontent.com/48363903/55758986-94b4a780-5a58-11e9-8bbb-2c53102de3f6.jpg)
the stack appears in the bottom slot but also remains in the top slot:
![extracting 2 stacks](https://user-images.githubusercontent.com/48363903/55758990-97170180-5a58-11e9-856f-43b04382f556.jpg)
Two Stacks can be extracted. 1 from the top slot and 1 from the bottom slot.

Just the first slot works fine:
![first slot just fine](https://user-images.githubusercontent.com/48363903/55759001-9f6f3c80-5a58-11e9-93c6-81a289a0b9fe.jpg)

**Comment by Buuz135** [comment]
Update the mod...
