### ISSUE TITLE
Crash while loading chunks during respawn

### ISSUE THREAD

**Issue by TomyLobo** [Buuz135/Industrial-Foregoing#556]
This is FTB Interactions 1.1.2, the requested mod versions are:
```
| State  | ID                                   | Version                   | Source                                                    | Signature                                |
|:------ |:------------------------------------ |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
| LCHIJA | teslacorelib                         | 1.0.15                    | tesla-core-lib-1.12.2-1.0.15.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
| LCHIJA | industrialforegoing                  | 1.12.2-1.12.2             | industrialforegoing-1.12.2-1.12.11-235.jar                | None                                     |

```
Crashlog (If Any):
[crash-2019-04-16_09.43.52-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/3083717/crash-2019-04-16_09.43.52-client.txt)

I died.
I clicked respawn.
The game crashed.
This is the conveyor referenced in the crash log:
![image](https://user-images.githubusercontent.com/963797/56193192-5a3aa400-6030-11e9-98f2-d58abc372756.png)
It's behind a chunk boundary from where I died and respawned, so it would be loaded after the rest of the conveyors.
Here's where I died (skull), the spawn (S) and (probably doesn't matter) the position where my tombstone (T) ended up, with the crash location (C) in the background:
![image](https://user-images.githubusercontent.com/963797/56193058-18116280-6030-11e9-92c6-41534874c689.png)

**Comment by TomyLobo** [comment]
Sweet, that was quick :)
How often do you usually release?

**Comment by Buuz135** [comment]
Usually right after stuff is closed

**Comment by TomyLobo** [comment]
Thanks a lot, looks like this is making it into the next FTB Interactions release already :)

**Comment by TomyLobo** [comment]
I was just able to confirm that this fixed my problem. I updated the regular FTB Interactions 1.1.2 pack by setting forge to 2806 and IF to 1.12.12 and I no longer crash in cases where I would once get a guaranteed crash.
Thanks again for that quick fix :)
