### ISSUE TITLE
[Bug] Colliding entity with block

### ISSUE THREAD

**Issue by Yoshisky** [Buuz135/Industrial-Foregoing#558]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.11-235
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): https://gist.github.com/Yoshisky/f6d0658b10d19c9148f9b7d00a6405d0

I was playing FTB-Interactions-1.1.2-stable on my private server and the game crashed unexpectedly. I just remember that someone placed lots of conveyor blocks in order to transfer items and the crashlog shows the problem of the conveyor indeed.

I have no screenshot for this issue because I'm not able to take one before crashes(

Btw optifine is not installed)

**Comment by Buuz135** [comment]
Update the mod
