### ISSUE TITLE
BOOK TYPOS REPORTS HERE

### ISSUE THREAD

**Issue by Buuz135** [Buuz135/Industrial-Foregoing#56]
Please post the book typos here!

**Comment by calloatti** [comment]
Introduction.

"Machines accept any time of power" 

should be:

"Machines accept any type of power"

**Comment by calloatti** [comment]
Lava Fabricator

"When provided with provided with large"

should be

"When provided with large"

**Comment by calloatti** [comment]
Black Hole Controller

"It can can"

should be

"It can"
