### ISSUE TITLE
Auto-Brewer crash (SF4)

### ISSUE THREAD

**Issue by krisjenner** [Buuz135/Industrial-Foregoing#562]
Industrial Foregoing Version: 1.12.2-1.12.11-235
TeslaCoreLib Version: 1.12.2-1.0.15 
Crashlog (If Any): [crash](https://gist.github.com/krisjenner/bca1dfb672d2167adb24ed7d4405819b)

Player right clicked auto-brewer with water bottle and crashed. Him and teammate could not log back in until this block was removed.

**Comment by Buuz135** [comment]
Duplicate https://github.com/Buuz135/Industrial-Foregoing/issues/413
