### ISSUE TITLE
[Feature Request] Laser Drill: Per Biome/Dimension Ores settings

### ISSUE THREAD

**Issue by Motzkiste** [Buuz135/Industrial-Foregoing#577]
Industrial Foregoing Version: 1.12.12-236
TeslaCoreLib Version: 1.0.15.13

___

I already found the `laser_drill_ores` dictionary and looked into the files, but had no idea how i should change them to set ores per dimension.

> **For Example:**
> Ores from a Planet should only be mined on that Planet.
> Or if you mine in Aether the Ores from Aether, Overworld and Nether should be mined.

If this is already possible an entry in Wiki here on GitHub would be nice :)

**Comment by Buuz135** [comment]
Look at the file, there are examples for that.
