### ISSUE TITLE
Blackhole Controller with Blackhole Tanks only outputting fluid of first slot

### ISSUE THREAD

**Issue by segabl** [Buuz135/Industrial-Foregoing#579]
Industrial Foregoing Version: 1.12.2-1.12.11-235
TeslaCoreLib Version: 1.12.2-1.0.15

When connecting an Ender Fluid Conduit from EnderIO (which can transfer any fluid) to a Blackhole Controller that contains multiple Blackhole Tanks, the controller will only output the fluid from its first slot, even if all other tanks receiving that fluid are full and there are other tanks that contain a different fluid that aren't full. Not sure if this is an issue with EnderIO or this mod, could be an edge case since most fluid transfer systems lock their pipes to one fluid and actually contain that fluid, while EnderIO transfer is instant without having any items/fluids in the actual pipes.

**Comment by Buuz135** [comment]
It works fine with other types of extraction methods like Industrial Foregoing conveyors
