### ISSUE TITLE
Doesn't support 1.12 anymore? Only 1.12.1 1.12.2?

### ISSUE THREAD

**Issue by BrendanTA** [Buuz135/Industrial-Foregoing#58]
Industrial Foregoing Version: industrialforegoing-1.12.1-1.4.1-68.jar
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.9.jar
https://i.imgur.com/LR0Wn8U.png

**Comment by Buuz135** [comment]
All 1.12 mods work in 1.12.1, or atleast should. Thats just forge complaining what version I compiled with. Everyone should move one to 1.12
