### ISSUE TITLE
Plant Interactor fails to interact with Pam's Harvestcraft fruits

### ISSUE THREAD

**Issue by Barchtic** [Buuz135/Industrial-Foregoing#580]
Industrial Foregoing Version: 1.12.2-1.12.12-236
TeslaCoreLib Version: 1.12.2-1.0.15

The vertical range of the plant interactor works perfectly with bark-based drops, aka cinnamon, etc.
However, this vertical range fails to affect any planted fruits on trees, requiring to be placed at the same height level as the fruit.

As seen here, the plant interactor does not work in its expected vertical range with this cherry fruit.
![javaw_doiv2avTlw](https://user-images.githubusercontent.com/31119273/60552354-517a7580-9ce3-11e9-8b78-e2b5f7d0f998.png)

However, in this instance, all crops on the same level as the interactor are harvested except for those on a different Y-value.
![javaw_ts6E2dLZRE](https://user-images.githubusercontent.com/31119273/60552382-6ce58080-9ce3-11e9-849c-cf8c7b7cdd5b.png)

**Comment by Buuz135** [comment]
Duplicate #573
