### ISSUE TITLE
Laser drill configuration

### ISSUE THREAD

**Issue by LordEpos** [Buuz135/Industrial-Foregoing#582]
Not sure if I'm asking how to do an already implemented thing, or asking for a new feature to be added, but is there any way I can add or remove entries in the laser drill's registry?

Ideally, I'd like to have the drill available earlyish in my modpack, and then the different laser focuses be upgrades instead of options, changing to rarer ores as you progress, but really if nothing else I'd just like to be able to remove a thing or two from its registry so that ores the player can't get until a postgame dimension can't be obtained early (worst case scenario, I can always make the drill come after everything.)

**Comment by Buuz135** [comment]
Look into `config/laser_drill_ores/`

**Comment by LordEpos** [comment]
Yep, just found this browsing other issues, thanks.
