### ISSUE TITLE
[1.12.12-236] [MP] Placing Black Hole Tank crashes with TeslaCoreLib

### ISSUE THREAD

**Issue by shortybsd** [Buuz135/Industrial-Foregoing#584]
Industrial Foregoing Version: 1.12.2-1.12.12-236
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): https://pastebin.com/8ZBzaAU9
Forge: 2837
Game Type: Multiplayer

Placed down a black hole tank and immediately crashed the server. Restarted several times and googled this issue but everyone was crashing with brewer. Not this case. I placed several at my area with no issues, a friend placed one and killed server. I tried to replicate and cannot do it.

The reason for this (back in January): https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/issues/28#issuecomment-457967397
I will report this to TeslaCoreLib's dev as well.

**To temporarily fix this for anyone else that sees this post:** 
1.) Backup your world.
2.) edit config/forge.cfg
change both of these entries to true

```
B:removeErroringEntities=false
B:removeErroringTileEntities=false
```

3.) Start server, make sure it didn't just wreck the world. (if fixed then go to number 4)
4.) Shut down server.
5.) Change forge.cfg back to false on above 2 entries.
5.) Start server.

**Comment by Buuz135** [comment]
Duplicate #413

**Comment by shortybsd** [comment]
This is not a duplicate of #413. I changed EnderIO's bottle settings both to off and still crashed.
