### ISSUE TITLE
Crash when shift-clicking a bucket into a black hole tank

### ISSUE THREAD

**Issue by al132mc** [Buuz135/Industrial-Foregoing#586]
One of my modpack users reported this bug to me, along with the crashlog below

Industrial Foregoing Version: 1.12.2-1.12.12-236
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): [Pastebin here](https://pastebin.com/8ey9Xz2V)

**Comment by Buuz135** [comment]
Duplicate #413
