### ISSUE TITLE
Mob Slaughter causing my game to crash

### ISSUE THREAD

**Issue by McAsa7** [Buuz135/Industrial-Foregoing#588]
Hello there. I'm having a recent problem. I just got 3 crashes with the same problem (mob_slaughter). I was playing normaly and from nowhere I crashed. Restarted my server and it crashed 2 more times... All 3 times I crashed in the same moment that a mob started to be killed. When I saw the report (https://paste.dimdev.org/oqopahovaw.mccrash) I didn't understand it very well. HELP?

**Comment by McAsa7** [comment]
Crashed again but this time it was a complitly different report: https://paste.dimdev.org/uyeduvicex.mccrash

**Comment by Loucool111** [comment]
Hello, I seem to have a similar problem.
My world crashes pretty much randomly with this report : [link](https://gist.github.com/Loucool111/d2d79395988c487275c6ee96a66c7ac0)
I don't know if the bug comes from Twilight Forest or this mod.
Just wanted to help!

**Comment by Buuz135** [comment]
Duplicate #413

**Comment by McAsa7** [comment]
I'm sorry, but none of those problems was what happened to me! I had 1 mob slaughter with 2 quantum tanks in eatch side connected with transfer pipes. It was running ok for 2 weeks and started to crash from nowhere...
