### ISSUE TITLE
Broken recipes

### ISSUE THREAD

**Issue by Smartaros** [Buuz135/Industrial-Foregoing#59]
I have a huge modpack, in which there are no recipes for crafting all machines. Latest forge, mc 1.12.1

**Comment by Buuz135** [comment]
Can I get the `latest.log` ?

**Comment by Smartaros** [comment]
My mistake, i missed tesla core lib config, there were disabled recipes by default

**Comment by faceofcat** [comment]
@Buuz135, aren't you enabling the needed things from TCL in your mod's construct event?

something like this: https://github.com/faceofcat/Tesla-Powered-Thingies/blob/1.12/src/main/kotlin/net/ndrei/teslapoweredthingies/TeslaThingiesMod.kt#L44-L64
