### ISSUE TITLE
The block placer can dupe items when moved by a piston

### ISSUE THREAD

**Issue by SeRimir** [Buuz135/Industrial-Foregoing#597]
Industrial Foregoing Version: 1.12.2-1.12.13-237
TeslaCoreLib Version: 1.0.15.13
Crashlog (If Any): No crashlog

**Comment by Buuz135** [comment]
This needs more context

**Comment by SeRimir** [comment]
well the problem is from a long time ago, like 8 or 9 months, i was trying to make an automatic placer for the tree extractor but i didn´t have the space so i needed to move the placer and put a pipe, first i tried moving the block placer with a piston to see if i could move it then it dropped the blocks it had inside, when i broke the placer it dropped the items again, i replicated it a couple of times to see if whats the placer or something else, and everytime the placer is moved it drops the items but the items are still inside the placer. 

I am sorry  for the bad english is not my first language, and i reported it now beacause i thinked that you would fix it. Maybe its a mod that i have so i will do it now without other mods.

**Comment by Buuz135** [comment]
Don't move tile entities, another mod enables tile entity moving and it's wrong.

**Comment by SeRimir** [comment]
oh ok, sorry for the trouble
