### ISSUE TITLE
[1.12] Black Hole Unit UI Issue

### ISSUE THREAD

**Issue by Guybrush0** [Buuz135/Industrial-Foregoing#60]
Industrial Foregoing Version: 1.12-1.3.1-61
TeslaCoreLib Version: 1.12-1.0.9

Black Hole Unit updates contents weirdly, will not update item count if items are piped in, but will update if removed, 
example: cobblestone generator, items constantly put in but item count not being updated, items being pulled out will subtract 1 at a time etc... when reopening gui it will fix and show correct item count

**Comment by Buuz135** [comment]
Fixed already in latest
