### ISSUE TITLE
Feature request: make the mob duplicator range configurable to be the same as the crusher/factory.

### ISSUE THREAD

**Issue by calloatti** [Buuz135/Industrial-Foregoing#63]
Right now the mob duplicator has a greater range than the mob crusher or the mob factory, so when you build a 5x5 spawner, mobs spawn outside the spawner walls.

5x5 is a nice size since that is the range of the crusher/factory.

Industrial Foregoing Version: industrialforegoing-1.12.1-1.4.2-69
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.9
Crashlog (If Any): -

**Comment by Buuz135** [comment]
Make a room bigger and push them around

**Comment by Chunkey** [comment]
+1 to OP. Why give us range upgrades if we can't use them? Energy cost can go up or something. Having to push them just seems awkward.

**Comment by calloatti** [comment]
The mob crusher range has been changed to 7x7 in the latest version, vs 9x9 for the duplicator.

It would be great anyway to have configurable ranges, as has been proposed in other issues. Let's see what happens.

**Comment by drivetheory** [comment]
a range addon limiting the range back to 5x5 would be very appreciated, especially on multiplayer servers where chunk claims are limited...

**Comment by delet3r** [comment]
So THIS is why mods get so simple and boring.  People posting on githubs pestering mod devs because its 'awkward' that they have to make some conveyors.  Sheesh.

**Comment by Chunkey** [comment]
It actually doesn't even work right. Mobs will spawn and die on the edge,
leaving loot on the ground. Conveyors don't fix that.
