### ISSUE TITLE
[Bug?/Config Issue] Mob Crusher doesn't collect essence from passive mobs

### ISSUE THREAD

**Issue by Guybrush0** [Buuz135/Industrial-Foregoing#64]
Industrial Foregoing Version: 1.12.1-1.4.2-69
TeslaCoreLib Version: 1.12-1.0.9

if this is intended can there be a config option to allow it

**Comment by Buuz135** [comment]
It is intended, the Mob Crusher collects the dropped experience when mobs are killed and transform it into essence, if a mob doesn't drop experience it won't generate essence.
