### ISSUE TITLE
[1.12+][Feature Request] RedNet

### ISSUE THREAD

**Issue by OneEyeMaker** [Buuz135/Industrial-Foregoing#69]
Hello.
Firstly, great thanks for your work!
I've suggestion for this mod: implement RedNet (from MFR).
There's so little mods (for MC 1.12+), which add *powerful* redstone technology (such as Project Red or Super Circuit Maker), so this feature would be very helpful and it's highly required.

Everything about implementation you can find in original MFR. Also, extending original concept and adding more features is welcome.

P. S. If you need any help - feel free to ask (I'm Java programmer).

**Comment by josephcsible** [comment]
I'm excited for the new mod. Can you mention here (or somewhere else where Industrial Foregoing people will see it) when it happens?
