### ISSUE TITLE
Crash when checking the manual

### ISSUE THREAD

**Issue by Nagapito** [Buuz135/Industrial-Foregoing#71]
Industrial Foregoing Version: 1.12.1-1.4.3-74
TeslaCoreLib Version: 1.12-1.0.9
Crashlog (If Any): https://gist.github.com/Nagapito/1053de745424e9afaf88c6a16637349c

Was browsing the manual noticed the black hole item that can store 9 black holes inside and when I pressed next to see the recipe page, crash

**Comment by Nagapito** [comment]
Just some extra info, since, as you say on the change log, its an hard issue to track, so it might help.

The pack is Modern Skies 2 and I noticed that the items(all the black hole items) which caused the crash were removed with scripts!

Maybe that is the cause, since the recipe is not registered anymore.

**Comment by Buuz135** [comment]
Oh yeah I will check if the recipe exists

**Comment by Nagapito** [comment]
More info... Maybe was already patched on the first commit...

It crashed again and this time the recipe exists, but it was changed by scripts.
