### ISSUE TITLE
Allow to upgrade work area of Hydrator

### ISSUE THREAD

**Issue by OneEyeMaker** [Buuz135/Industrial-Foregoing#73]
Firstly, thank you for this machine! It's very helpful.
And only issue with it: it fertilizes only plants in 3x3 area and doesn't accept any range upgrades.
I suggest just to allow upgrade range of this machine.

Thank you for your work!

// IF 1.5, MC 1.12.2, Forge build 2512

**Comment by Buuz135** [comment]
Well, no, there is a machine that will use bonemeal and similars in a large area and it would be faster.
