### ISSUE TITLE
Plant Gatherer not collecting extras from Integrated Dynamics Menril trees

### ISSUE THREAD

**Issue by coldino** [Buuz135/Industrial-Foregoing#74]
Menril logs should occasionally drop crystallized chunks while the leaves should drop berries. Using the Plant Gatherer I only ever get logs and saplings. Other methods I've tried seem work as expected: Tinker's lumber axe, ore excavation (vein miner), and a clearing quarry builder from RFTools.

_(as an aside there's no UI for the Plant Gatherer since the most recent update - I'm pretty sure it had one before)_

Aside from Forestry, is this is only option for harvesting trees in 1.12 at the moment?
Loving the mod by the way - very polished UI and clean to use especially with mods like XNet.

Industrial Foregoing Version: **1.12.1-1.5.0-83**
TeslaCoreLib Version: **1.12-1.0.10**
Integrated Dynamics Version: **1.12-0.9.3**

Using the ATM 3 v4.2 pack with individual mods updated.

**Comment by Buuz135** [comment]
The Menril Problem is in Integrated Dynamics side, he is using a Deprecated Method here https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.12/src/main/java/org/cyclops/integrateddynamics/block/BlockMenrilLeavesConfig.java#L65 and https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.12/src/main/java/org/cyclops/integrateddynamics/block/BlockMenrilLeavesConfig.java#L65 . Please report it to it's author.

The other issue will be fix later today with an update.

**Comment by josephcsible** [comment]
@Buuz135 You linked to the same method twice. Was there a second deprecated method? If so, what is it?
