### ISSUE TITLE
Villager trade exchanger misses a lot of steps of trading

### ISSUE THREAD

**Issue by josephcsible** [Buuz135/Industrial-Foregoing#76]
Industrial Foregoing Version:  1.12.1-1.5.1-84
TeslaCoreLib Version: 1.12-1.0.10
Crashlog (If Any): N/A

The villager trade exchanger manipulates items directly rather than calling IMerchant.useRecipe(). This causes the following to not work:
- Trades X-ing out when you use them enough times
- Not being able to use X-ed out trades
- New trade tiers becoming available
- The villager being marked as willing to mate
- The villager's wealth going up
- Generating XP

The first three things are the important ones, IMO. If we don't switch to useRecipe, we should add our own code to do at least them.

**Comment by Buuz135** [comment]
Im going to leave it as it is right now and rework it in the future
