### ISSUE TITLE
Trading ignores second item

### ISSUE THREAD

**Issue by josephcsible** [Buuz135/Industrial-Foregoing#77]
Industrial Foregoing Version: 1.12.1-1.5.1-84
TeslaCoreLib Version: 1.12-1.0.10
Crashlog (If Any): N/A

The villager trade exchanger ignores the second item in trades that have two items. For example, if a villager has the trade 6 raw fish + 1 emerald -> 6 cooked fish, the exchanger will let you trade just 6 raw fish for 6 cooked fish.

**Comment by Buuz135** [comment]
Same as #76 there isn't many 2 items recipes.

**Comment by josephcsible** [comment]
As a temporary solution to avoid a really cheaty situation, would you accept a PR that makes 2-item trades not be available at all in the trade exchanger until it gets proper support for them? (Some of them as they stand are quite unbalanced, especially since they'll never X out.)

**Comment by Buuz135** [comment]
Sure
