### ISSUE TITLE
[Question] Config 

### ISSUE THREAD

**Issue by NillerMedDild** [Buuz135/Industrial-Foregoing#79]
Industrial Foregoing Version: 1.12.1-1.5.2-85
TeslaCoreLib Version: 1.12-1.0.10
Crashlog (If Any): 

Hey!

I've been looking through the config to nerf a few machines, and I'm having a hard time understanding what the configs actually change.

For instance `    enchantment_refiner {
        # How much energy needs a machine to work [range: 1 ~ 2147483647, default: 400]
        I:energyForWork=400`
Does that mean it takes 400rf/t? Does one operation cost 400rf?

Also, `        # Energy input rate of a machine [range: 1 ~ 2147483647, default: 10]
        I:energyRate=10`
Does this mean the machine can only accept 10rf/t? Does it consume 10rf/t?

I hope you can clarify for me :)

**Comment by Buuz135** [comment]
energyForWork=The total energy a machine needs to do an operation=Amount of RF
energyRate=How fast it will charge to do the operation=Amount of RF/t

**Comment by NillerMedDild** [comment]
Thank you :)
