### ISSUE TITLE
[Request] Energy Generation configs

### ISSUE THREAD

**Issue by NillerMedDild** [Buuz135/Industrial-Foregoing#80]
Industrial Foregoing Version: 1.12.1-1.5.2-85
TeslaCoreLib Version: 1.12-1.0.10
Crashlog (If Any):

Hey hey.

I'd like to request configs for how much energy the various generators produce per tick, and preferably also how much RF they get out of each "product".

**Comment by Buuz135** [comment]
The only one configurable is the Petrified Fuel Generetor and it will stay that way because it's the only one it doesn't take any effort to use
