### ISSUE TITLE
Mob Crusher generates infinite essence

### ISSUE THREAD

**Issue by ouroborus** [Buuz135/Industrial-Foregoing#81]
Industrial Foregoing Version: 1.12.1-1.5.0-83
TeslaCoreLib Version: 1.12-1.0.9

Built my first mob crusher. Noticed, upon placing it, it was already full with 8000mB essence. Pumping doesn't decrease this. No power is being provided.

**Comment by Buuz135** [comment]
Are you sure there isn't XP in the working area? It will pick up XP and turn it into essence

**Comment by ouroborus** [comment]
Erm... Possibly, but not at that rate. I have a nearby machine throwing bottles o' enchantment for pickup by another machine but this is every 4-5 seconds or so and the mob crusher appears the be generating 8000 essence per tick (i.e.: it appears to always be full, it's not possible to empty it).

**Comment by ouroborus** [comment]
It seems to only effect mob crushers whose effect area intersects with a certain (seemingly random) volume.

![image](https://user-images.githubusercontent.com/392047/32147285-14fa6746-bca2-11e7-95f8-553e55392a6f.png)

In this screen shot, the "something" effecting the mob crushers appear to be towards the center. (All of the mob crusher in the screenshot are effected.) The volume isn't cuboid. The volume seems to be around one block above the floor as crushers placed three blocks into the floor are effected.

**Comment by ouroborus** [comment]
I tried copying the world over to single player so I'd have more freedom to experiment and I can't reproduce it there. It appears to only happen in multiplayer.

**Comment by ouroborus** [comment]
I'm not able to reproduce this any more. I tried copying the world to single player instance and couldn't reproduce the issue. I tried copying the world the another multiplayer instance and couldn't reproduce it. I restarted the original server and the issue stopped happening. (I had rebooted it before and still had the issue. I don't know what changed this time.)

At this point I can only guess what was going on. I notice your code, [here](https://github.com/Buuz135/Industrial-Foregoing/blob/b2c8c330f8b088700f380b3da67adba76180bf3e/src/main/java/com/buuz135/industrial/tile/mob/MobRelocatorTile.java#L65), asks for a list of xp orb entities in the volume, adds essence according to their values, then marks the orb as dead. However, there doesn't seem to be a check to see if the orb is dead in the first place. I think it might be possible for an entity to get "stuck" in a dead state and never cleaned up. If this happened, it might explain what I was seeing.

**Comment by ouroborus** [comment]
I was able to verify my suspicion. The mob crusher is not taking into account if a xp orb is dead or not and so can process a particular orb server times effectively creating a dup'ing situation.

![2017-10-29_19 23 00](https://user-images.githubusercontent.com/392047/32152058-c4b8184a-bcde-11e7-8037-e21d64368535.png)

In the configuration on the left, 10 bottle o' enchanting generate ~30,000mB of essence while, with the configuration on the right, 10 bottles generate 1300mB.

**Comment by Buuz135** [comment]
I will fix it for the next version, thanks for the help
