### ISSUE TITLE
Transporting seeds to Plant Sower doesn't distribute to all slots

### ISSUE THREAD

**Issue by SolidGreenDay** [Buuz135/Industrial-Foregoing#82]
Industrial Foregoing Version:  1.5.1
TeslaCoreLib Version:  1.0.10
Crashlog (If Any): 

When I try automating a farm with a re-collector and sower, the seeds only goes to the first slot and it has to be full until it goes to the next making it so you have to have a minimum of 144 seeds to start an automated farm and I tried to use this mod for Mystical Agriculture and having 144 seeds is too much. I was wondering if there can be a way to solve this.

**Comment by Buuz135** [comment]
Use an item splitter
