### ISSUE TITLE
Laser Beam leaks GL state

### ISSUE THREAD

**Issue by yueh** [Buuz135/Industrial-Foregoing#83]
The laser beam rendering leaks the GL state in [BlockUtils.java#L56](https://github.com/Buuz135/Industrial-Foregoing/blob/1b6751c48217640d3fdbeca443b8a43f06edb1f8/src/main/java/com/buuz135/industrial/utils/BlockUtils.java#L56).

Most notably disabling certain features and never enabling them again.

This is an example of how it affects TD fluiducts
![GL leak](https://i.imgur.com/oVbVUhe.png)

Industrial Foregoing Version: 1.12.1-1.5.2-85
TeslaCoreLib Version: 1.12-1.0.10

**Comment by Buuz135** [comment]
Can you try [this version](https://teamcity.buuz135.com/viewLog.html?buildId=22&buildTypeId=IndustrialForegoing_Build&tab=artifacts) to check if its fixed? I couldn't replicate it so I kinda guessed. 

Join as a guest if you can't access it

**Comment by yueh** [comment]
Yes, seems to have fixed it.

It was/is also depending on the rendering order. So the placement/view angle/etc did affect it. Sometimes it works. Sometimes not. But usually circling around a beam works, if there are other TESRs around it.
