### ISSUE TITLE
Plant Sower lack of automation until "filter" get's full of seeds.

### ISSUE THREAD

**Issue by chameleoon** [Buuz135/Industrial-Foregoing#84]
Industrial Foregoing Version: any
TeslaCoreLib Version:  any

First I would like to thank you for your hard work and very useful mod.
This is not an direct issue/bug but more like a QoL/feature request.

The Plant Sower doesn't have an inventory and so you have to have a minimum of 144 of the seeds you want to be able to automate it﻿ else it's going to be a temporary run back and forth to manually plant your seeds in all the available slots so you get more seeds back.

Please let me know if there is another way of doing this and thanks if you are going to consider adding a feature like MFR's old planter.

**Comment by Buuz135** [comment]
Use Item Splitter

**Comment by chameleoon** [comment]
Ugh, ok got me some time to figure that out, I think you should explain this better in the manual.

Thank you.
