### ISSUE TITLE
[1.12.2] Manual jei Issues

### ISSUE THREAD

**Issue by YOYOK9** [Buuz135/Industrial-Foregoing#85]
Noticed this while building my pack that the jei info from the manual is shifted upwards to far. Some of the text is hard to read because of this.
Picture: https://puu.sh/ydqco/da1b71eb7d.png

Industrial Foregoing Version: 1.12.1-1.5.2-85
TeslaCoreLib Version: 1.12-1.0.10
Minecraft: 1.12.2
Forge: 14.23.0.2528

**Comment by Buuz135** [comment]
If you make the gui smaller it should fix it temporally, I will get it fix for the next version. Does in the manual itself look good?
