### ISSUE TITLE
[Question] Old MFR blocks

### ISSUE THREAD

**Issue by YOYOK9** [Buuz135/Industrial-Foregoing#86]
So figured Id make a new "issue" for this. Would it be possible seeing as this is a port like mod of MFR to possibly bring back the meat blocks was just another thing to do with the liquid meat.? As well as the old rednet controller? If possible that is.

**Comment by Buuz135** [comment]
No need for the block of meat, the meat feeder will feed you and the Rednet will be a part of another mod.

**Comment by YOYOK9** [comment]
Sounds good any news on when Rednet might come out? And the meat block was more as an esthetics item. Some of my players were asking me for it that's all.
