### ISSUE TITLE
Dupe bug with Sponge plugins

### ISSUE THREAD

**Issue by runescapejon** [Buuz135/Industrial-Foregoing#87]
hello
I am currently running
Industrial Foregoing Version:  1.12.2-1.5.3-88
TeslaCoreLib Version: 1.12-1.0.10 
griefprevention-1.12.1-4.3.0.483
spongeforge-1.12.2-2503-7.0.0-BETA-2725
forge-1.12.2-14.23.0.2515
industrialforegoing-1.12.2-1.5.3-88
LuckPerms v3.4.68

here is how the Dupe glitch works
you will need 2 people for this
1 person make a claim
then place a block near the claim that you want to dupe with example place a diamond block on the border of your claim
the second person that not trusted in your claim place down Block breaker from
Industrial Foregoing mod and power it if you don't know how it works then it would be easier to use Extra Utilities 2 Creative Energy Source block next the block breaker and it start duping check inside of the block breaker and you will get dupe items
here a GIF on how to do this

https://gyazo.com/a5a1e344f77af9484b5c579155908d48
as you he place a block breaker next to my diamond block and it start to dupe
you can use any source of power to power block breaker i just use Creative energy source because it was faster to show you, it really shows no logs

EDIT: Phit had pointed this out
https://github.com/Buuz135/Industrial-Foregoing/blob/master/src/main/java/com/buuz135/industrial/tile/world/BlockDestroyerTile.java#L90

Im not sure if it's help

**Comment by JoeSGT** [comment]
Having the same issue
version that i am currently at
is 
Industrial Foregoing Version: 1.12.2-1.5.4-91
TeslaCoreLib Version: 1.12-1.0.11
griefprevention-1.12.1-4.3.0.483
spongeforge-1.12.2-2529-7.0.0-BETA-2730
forge-1.12.2-14.23.0.2529
LuckPerms-Sponge-4.0.4
this is latest version as of this moment and it i can still dupe

**Comment by Buuz135** [comment]
If someone can test this version and tell me if it is fixed I would appreciate it. @JoeSGT @runescapejon 
[industrialforegoing-1.12.2-1.5.5.jar.zip](https://github.com/Buuz135/Industrial-Foregoing/files/1457283/industrialforegoing-1.12.2-1.5.5.jar.zip)

**Comment by JoeSGT** [comment]
tested, don't work
but thanks for trying to fix this

**Comment by Buuz135** [comment]
Soooo, it's fixed?

**Comment by JoeSGT** [comment]
nope it's not fixed i can still dupe with version 1.12.2-1.5.5
the one you just gave us

**Comment by JoeSGT** [comment]
here is proof of the dupe
https://gyazo.com/a4691b903f7e2057517a0403c048de85

**Comment by Buuz135** [comment]
And this one? [industrialforegoing-1.12.2-1.5.5.jar.zip](https://github.com/Buuz135/Industrial-Foregoing/files/1457404/industrialforegoing-1.12.2-1.5.5.jar.zip)

**Comment by JoeSGT** [comment]
this one does not work

**Comment by Buuz135** [comment]
Then I can't fix it, it's on the plugin side, you can disable the machine work in the config.

**Comment by JoeSGT** [comment]
it's been reported on the plugin issue page and he said it's spongeforge side then they said it's your issue
weird im not sure where to go to get this fix
but thanks it seem i have to disable this and ban it

**Comment by Buuz135** [comment]
I do really check anything possible

**Comment by JoeSGT** [comment]
I'm not much of a coder but can you try adding a check here
https://github.com/Buuz135/Industrial-Foregoing/blob/master/src/main/java/com/buuz135/industrial/tile/world/BlockDestroyerTile.java#L69
and see if it work
im not sure if it work or not but it's worth a try

**Comment by Buuz135** [comment]
I check if a fake player can break it. I check if the block has been broken before adding the items to the inventory, nothing more I can do.

**Comment by JoeSGT** [comment]
hm not sure if it help but take a look on what Gabizou said
https://github.com/SpongePowered/SpongeForge/issues/1830

**Comment by Buuz135** [comment]
I dont have to support 3rd party forge programs, there aren't any more checks I can do, I'm using anything forge provides, not what Sponge provides, if there are more Forge known checks just let me know.

**Comment by JoeSGT** [comment]
alright thanks

**Comment by Buuz135** [comment]
@JoeSGT Can you do me a favor and try this version to fix this issue?
[industrialforegoing-1.12.2-1.5.9.jar.zip](https://github.com/Buuz135/Industrial-Foregoing/files/1489514/industrialforegoing-1.12.2-1.5.9.jar.zip)

**Comment by Buuz135** [comment]
Same for @runescapejon

**Comment by JoeSGT** [comment]
great news it break the block and does not dupe
but sadly players can use it for griefing since it bypass the claim's and break the block

**Comment by JoeSGT** [comment]
Sorry it's fixed

**Comment by JoeSGT** [comment]
thanks
