### ISSUE TITLE
Hydrator server crash

### ISSUE THREAD

**Issue by Shinisuryu** [Buuz135/Industrial-Foregoing#88]
Industrial Foregoing Version: 1.5.4-91
TeslaCoreLib Version: 1.0.11
Crashlog (If Any): https://gist.github.com/Shinisuryu/47ae1ff133a97fae5010d3383adae37f

Don't know the specifics since the crash first happened when I was sleeping, Crash happens only when I join the server, I assume the same for any player logged out in that area.

If the player that was there when it crashed has anything important I'll add it when they're online.

Update: They said they had it down, but noticed it wasn't planting in a specific block, and also realized that it needs to be in the center. So they moved it to that center block and the game/server crashed. The only thing notable about that block was there was an Actually Additions worm there either then or previously.

**Comment by Darksilver78** [comment]
Experienced a similar issue.

Player placed Hydrator in world and it crashed the server. Server continued to crash whenever the region where the Hydrator was located was loaded. Continued until block was removed with MCEdit.

Modpack is FTB: Horizons III v1.0.0 (Nothing added/changed)
Crashlog: https://gist.github.com/Darksilver78/26e721a04a4c331ea0f970c3cca9ed41
World DL (Prior to MCEdit): https://mega.nz/#!n8BV0SaB!whi-QDJda6ao54bcqaTBznkiyYPOoZu-p7i0iXJIhZw
