### ISSUE TITLE
Mob Duplicator set to only work on redstone signal does not work when redstone is fed thru block.

### ISSUE THREAD

**Issue by calloatti** [Buuz135/Industrial-Foregoing#89]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.5.4-91
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.11
Crashlog (If Any): 

Place a Mob Duplicator over a stone block, set it to work only on a redstone signal, place a lever in the stone block bottom, flip the lever, nothing happens.

The stone block has a 15 value redstone signal as indicated by The One Probe.

If you place the lever directly on the bottom of the Mob Duplicator, then it works.

**Comment by Buuz135** [comment]
It is known, report it to https://github.com/faceofcat/Tesla-Core-Lib/issues , currently it only accepts Strong Redstone signal and not weak
