### ISSUE TITLE
Enchantment Applicator applies everything

### ISSUE THREAD

**Issue by Lukas45** [Buuz135/Industrial-Foregoing#95]
Industrial Foregoing Version: 1.5.6-93
TeslaCoreLib Version: 1.0.11
Applied a enchanted book with a lot of stuff on it to a pair of boots, and it ended up apply every enchant, despite only 1 of them actually being a valid enchant.
![image](https://user-images.githubusercontent.com/4707702/32995244-0a298aaa-cd72-11e7-91ee-ba8feb39818f.png)
The Mending/Silk Touch is a 2nd book I applied after to test it out.

So dunno if this should count as a bug, or a suggestion, but I'd think it should only apply valid enchants.

**Comment by Buuz135** [comment]
I think I will leave it like that, it might be useful in some situations.

**Comment by Lukas45** [comment]
Yeah like duping enchants :^) I can write another report on that if you want

**Comment by Buuz135** [comment]
How?

**Comment by TheEndless** [comment]
FWIW, I'm on the side of leaving it in.  In the pack I'm currently playing, it's the only way to apply a Fortune V enchantment from a book without it reverting down to Fortune III.

**Comment by Buuz135** [comment]
To make Fortune V you need 4 Fortune III and you need to work a bit to get them so it's not that bad

**Comment by TheEndless** [comment]
I already have a Fortune 5 book made from an enchant I pulled off of another tool.  If I attempt to apply that to a new tool with any means other than the Enchantment Applicator, it applies as Fortune 3.  I assume if you changed the current behavior, it would behave the same as other enchantment methods, like the anvil, and do the same.

**Comment by Buuz135** [comment]
But thats not duping 🤔

**Comment by TheEndless** [comment]
I know.  I was arguing for keeping the current functionality in.  I don't know how you'd use it for duping. @Lukas45 would need to explain that one.

**Comment by Lukas45** [comment]
I'm not against having it able to apply Fortune V without downgrading, it's more that it applies Fortune V to a pair of boots.

As for the dupe, the Enchant Applicator accepts any item, and will apply to any item. So if you put an enchanted book for application with Fortune V, and a stack of sticks (actually only tested with normal books, and not in a standalone client), it will create a stack of sticks enchanted with Fortune V, and each of those sticks can be extracted again.
I did get half a stack of books enchanted (not enchanted books, books with enchants) with what I have on those boots in the picture (excl. the mending/silk touch).

This can also lead to server danger, as I put 4 books (stacked) with enchants into the extractor, and it removed the enchant from all of them (only gave 1 enchanted book, and one book as output), so there was now an unenchanted item in the input slot (still had nbt tag for "no enchants"), which caused the server to crash on ticking entity. It had to be MCEdited out. Can link server crash log tomorrow.

**Comment by Buuz135** [comment]
I will limit the slot amount to 1 on this machines to fix the dupe bug.
